# Downloading Youtube videos

In [1]:
from yt_dlp import YoutubeDL
import os

In [2]:
url = "https://www.youtube.com/watch?v=z3U0udLH974"
output_folder = "downloads"

# Step 1: Download video only (H.264 MP4)
video_opts = {
    'format': 'bestvideo[ext=mp4]',
    'outtmpl': os.path.join(output_folder, '%(title)s.video.mp4')
}

with YoutubeDL(video_opts) as ydl:
    ydl.download([url])

[youtube] Extracting URL: https://www.youtube.com/watch?v=z3U0udLH974
[youtube] z3U0udLH974: Downloading webpage

WARNING: [youtube] No supported JavaScript runtime could be found. Only deno is enabled by default; to use another runtime add  --js-runtimes RUNTIME[:PATH]  to your command/config. YouTube extraction without a JS runtime has been deprecated, and some formats may be missing. See  https://github.com/yt-dlp/yt-dlp/wiki/EJS  for details on installing one

[youtube] z3U0udLH974: Downloading android sdkless player API JSON
[youtube] z3U0udLH974: Downloading web safari player API JSON

WARNING: [youtube] z3U0udLH974: Some web_safari client https formats have been skipped as they are missing a url. YouTube is forcing SABR streaming for this client. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

[youtube] z3U0udLH974: Downloading m3u8 information

WARNING: [youtube] z3U0udLH974: Some web client https formats have been skipped as they are missing a url. YouTube is forcing SABR streaming for this client. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

[info] z3U0udLH974: Downloading 1 format(s): 397
[download] downloads/The two talking cats.video.mp4 has already been downloaded
[download] 100% of    1.06MiB

In [3]:
import yt_dlp
import os

url = "https://www.youtube.com/watch?v=z3U0udLH974"
output_folder = "downloads"
os.makedirs(output_folder, exist_ok=True)

ydl_opts = {
    'format': 'bestaudio/best',  # audio only
    'outtmpl': os.path.join(output_folder, '%(title)s.%(ext)s'),
    'postprocessors': [
        {
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',   # change to 'wav' for WAV
            'preferredquality': '192', # kbps for mp3
        }
    ],
}

with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    ydl.download([url])

print(f"✅ Audio saved in {output_folder} as MP3")

[youtube] Extracting URL: https://www.youtube.com/watch?v=z3U0udLH974
[youtube] z3U0udLH974: Downloading webpage

WARNING: [youtube] No supported JavaScript runtime could be found. Only deno is enabled by default; to use another runtime add  --js-runtimes RUNTIME[:PATH]  to your command/config. YouTube extraction without a JS runtime has been deprecated, and some formats may be missing. See  https://github.com/yt-dlp/yt-dlp/wiki/EJS  for details on installing one

[youtube] z3U0udLH974: Downloading android sdkless player API JSON
[youtube] z3U0udLH974: Downloading web safari player API JSON

WARNING: [youtube] z3U0udLH974: Some web_safari client https formats have been skipped as they are missing a url. YouTube is forcing SABR streaming for this client. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

[youtube] z3U0udLH974: Downloading m3u8 information

WARNING: [youtube] z3U0udLH974: Some web client https formats have been skipped as they are missing a url. YouTube is forcing SABR streaming for this client. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

[info] z3U0udLH974: Downloading 1 format(s): 251
[download] Destination: downloads/The two talking cats.webm
[download] 100% of  633.36KiB in 00:00:00 at 3.21MiB/s
[ExtractAudio] Destination: downloads/The two talking cats.mp3
Deleting original file downloads/The two talking cats.webm (pass -k to keep)
✅ Audio saved in downloads as MP3

# Stealing YouTube videos💃

In [27]:
# First, code for downloading video

In [3]:
def download_video(video_idx: str, output_folder: str = "downloads") -> dict:
    """
    Download a YouTube video and its audio (MP3) safely with progress bar.
    Skips the video if any step fails.
    """
    os.makedirs(output_folder, exist_ok=True)
    url = f"https://www.youtube.com/watch?v={video_idx}"

    # Options for yt-dlp: download best video and audio separately
    ydl_opts = {
        'format': 'bestvideo[ext=mp4]+bestaudio/best',  # separate video & audio
        'outtmpl': os.path.join(output_folder, '%(title)s.%(ext)s'),
        'merge_output_format': 'mp4',
        'progress_hooks': [],  # we will use tqdm manually
        'quiet': True,
        'no_warnings': True,  # <-- suppress warnings
    }

    try:
        with YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            title = info.get('title', 'unknown')
            video_id = info.get('id', video_idx)
        
        # Convert audio to MP3
        audio_opts = {
            'format': 'bestaudio/best',
            'outtmpl': os.path.join(output_folder, f'{title}.mp3'),
            'postprocessors': [{
                'key': 'FFmpegExtractAudio',
                'preferredcodec': 'mp3',
                'preferredquality': '192',
            }],
            'quiet': True,
            'no_warnings': True,  # <-- suppress warnings
        }

        with YoutubeDL(audio_opts) as ydl:
            ydl.download([url])
        
        return {
            "video_id": video_id,
            "video_title": title
        }

    except Exception as e:
        return {}

In [6]:
download_video("sZkB11pO9R8", output_folder="downloads/VideoData")

WARNING: [youtube] No supported JavaScript runtime could be found. Only deno is enabled by default; to use another runtime add  --js-runtimes RUNTIME[:PATH]  to your command/config. YouTube extraction without a JS runtime has been deprecated, and some formats may be missing. See  https://github.com/yt-dlp/yt-dlp/wiki/EJS  for details on installing one
WARNING: [youtube] sZkB11pO9R8: Some web_safari client https formats have been skipped as they are missing a url. YouTube is forcing SABR streaming for this client. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] sZkB11pO9R8: Some web client https formats have been skipped as they are missing a url. YouTube is forcing SABR streaming for this client. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] No supported JavaScript runtime could be found. Only deno is enabled by default; to use another runtime add  --js-runtimes RUNTIME[:PATH]  to your command/config. YouTube extraction without a JS runtime has been deprecated, and some formats may be missing. See  https://github.com/yt-dlp/yt-dlp/wiki/EJS  for details on installing one
WARNING: [youtube] sZkB11pO9R8: Some web_safari client https formats have been skipped as they are missing a url. YouTube is forcing SABR streaming for this client. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] sZkB11pO9R8: Some web client https formats have been skipped as they are missing a url. YouTube is forcing SABR streaming for this client. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

✅ Downloaded 'How a cat works' (sZkB11pO9R8) to downloads/VideoData

In [7]:
# now getting all videos to download

In [18]:
import pandas as pd
import ast

In [15]:
import pandas as pd

balanced_videos_path = "data/video-data/balanced_train_segments.csv"

# Read CSV with Python engine and comma as delimiter
df = pd.read_csv(
    balanced_videos_path, 
    engine='python',   # better for messy CSVs
    skipinitialspace=True,
    quotechar='"'      # respect quoted strings
)

# Remove leading '--' in the YTID column
df['YTID'] = df['YTID'].str.lstrip('-')

# Convert last column (positive_labels) from string to list
df['positive_labels'] = df['positive_labels'].apply(
    lambda s: [x.strip() for x in s.strip('"').split(',')]
)

print(df.head())

        YTID  start_seconds  end_seconds                 positive_labels
0  PJHxphWEs           30.0         40.0          [/m/09x0r, /t/dd00088]
1  ZhevVpy1s           50.0         60.0                     [/m/012xff]
2  aE2O5G5WE            0.0         10.0  [/m/03fwl, /m/04rlf, /m/09x0r]
3  aO5cdqSAg           30.0         40.0        [/t/dd00003, /t/dd00005]
4  aaILOrkII          200.0        210.0          [/m/032s66, /m/073cg4]

In [16]:
# 2️⃣ Load the mapping CSV
label_map_path = "data/video-data/class_labels_indices.csv"
label_df = pd.read_csv(label_map_path)

# Build a dictionary: mid -> display_name
label_dict = dict(zip(label_df['mid'], label_df['display_name']))

# 3️⃣ Map each list of positive_labels to their display names
df['positive_labels_names'] = df['positive_labels'].apply(
    lambda lst: [label_dict.get(mid, mid) for mid in lst]
)

In [17]:
df.sample(5)

,YTID,start_seconds,end_seconds,positive_labels,positive_labels_names
17768,lpHa-S_x1LA,350.0,360.0,"[/m/01p970, /m/026t6, /m/0l14md]","[Tabla, Drum, Percussion]"
7909,J3W0GUqDDag,100.0,110.0,"[/m/025_jnm, /m/09x0r]","[Finger snapping, Speech]"
8343,KL0TWPmezrY,10.0,20.0,"[/m/04rlf, /m/07p6fty, /m/09x0r]","[Music, Shout, Speech]"
18340,nbb8vmfjHJs,220.0,230.0,"[/m/03lty, /m/04rlf, /m/06by7, /t/dd00036]","[Heavy metal, Music, Rock music, Angry music]"
4838,AtdCLd4StZk,130.0,140.0,"[/m/016cjb, /m/04rlf]","[Gospel music, Music]"

In [18]:
df.shape

(22160, 5)

In [44]:
# Filter rows where 'positive_labels_names' contains 'Car' (case-insensitive)
cat_rows = df[df['positive_labels_names'].apply(
    lambda labels: any(label.lower() == "cat" for label in labels)
)]

cat_rows = cat_rows[cat_rows['YTID'].str.len() == 11]

cat_rows.shape

(112, 5)

In [45]:
cat_rows.sample(5)

,YTID,start_seconds,end_seconds,positive_labels,positive_labels_names
1386,29x5I94EBMQ,0.0,9.0,"[/m/01yrx, /m/04rlf, /m/068hy, /m/07r81j2, /m/...","[Cat, Music, Domestic animals, pets, Caterwaul..."
21048,wEmEkLQDl0U,0.0,9.0,"[/m/01yrx, /m/07qrkrw, /m/0jbk]","[Cat, Meow, Animal]"
2643,58yb7qX_pv8,30.0,40.0,"[/m/01yrx, /m/04rlf, /m/068hy, /m/07qrkrw, /m/...","[Cat, Music, Domestic animals, pets, Meow, Cat..."
3252,6c-5b9sj35o,30.0,40.0,"[/m/01yrx, /m/068hy, /m/07qrkrw, /m/07r81j2, /...","[Cat, Domestic animals, pets, Meow, Caterwaul,..."
2909,5lNTPOv9fSE,510.0,520.0,"[/m/01yrx, /m/068hy, /m/07pdhp0, /m/0jbk, /t/d...","[Cat, Domestic animals, pets, Biting, Animal, ..."

In [34]:
from tqdm import tqdm
import json
import os

In [48]:
log_file = "downloading_logs.jsonl"

In [52]:
with open(log_file, "a") as f:
    for idx, row in tqdm(cat_rows.iterrows(), total=len(cat_rows)):
        video_id = str(row["YTID"]).strip("-").strip()  # remove leading '-' or spaces

        if not video_id:  # skip empty IDs
            print(f"⚠️ Skipping empty/truncated ID at row {idx}")
            continue

        try:
            video_info = download_video(
                video_idx=video_id,
                output_folder="downloads/VideoData"
            )

            if video_info is None:
                metadata = {
                    "video_id": row["YTID"],
                    "error" : f"⚠️ No info returned for {video_id}, skipping"
                }
                f.write(json.dumps(metadata, ensure_ascii=False) + "\n")
                continue

            metadata = {
                **video_info,
                "start_seconds": row["start_seconds"],
                "end_seconds": row["end_seconds"],
                "positive_labels": row["positive_labels_names"]
            }

            f.write(json.dumps(metadata, ensure_ascii=False) + "\n")

        except Exception as e:
            metadata = {
                "video_id": row["YTID"],
                "error" : e
            }
            f.write(json.dumps(metadata, ensure_ascii=False) + "\n")
            continue

  0%|          | 0/112 [00:00<?, ?it/s]

  1%|          | 1/112 [00:03<07:01,  3.80s/it]ERROR: unable to download video data: HTTP Error 403: Forbidden
  2%|▏         | 2/112 [00:05<04:10,  2.28s/it]

  3%|▎         | 3/112 [00:07<04:43,  2.60s/it]

  4%|▎         | 4/112 [00:13<06:59,  3.88s/it]

  4%|▍         | 5/112 [00:18<07:26,  4.17s/it]

  5%|▌         | 6/112 [00:22<07:10,  4.07s/it]

  6%|▋         | 7/112 [00:25<06:50,  3.91s/it]

  7%|▋         | 8/112 [00:29<06:33,  3.79s/it]

  8%|▊         | 9/112 [00:33<06:30,  3.79s/it]

  9%|▉         | 10/112 [00:36<06:18,  3.71s/it]ERROR: [youtube] 1Oy7Yha8LOg: Video unavailable
 10%|▉         | 11/112 [00:37<04:35,  2.73s/it]

 11%|█         | 12/112 [00:48<08:59,  5.39s/it]

 12%|█▏        | 13/112 [00:52<08:01,  4.86s/it]

 12%|█▎        | 14/112 [00:55<06:54,  4.23s/it]

 13%|█▎        | 15/112 [01:20<17:19, 10.72s/it]

 14%|█▍        | 16/112 [01:30<16:25, 10.26s/it]

 15%|█▌        | 17/112 [01:33<13:01,  8.23s/it]

 16%|█▌        | 18/112 [01:39<11:34,  7.39s/it]

 17%|█▋        | 19/112 [01:43<10:15,  6.62s/it]

 18%|█▊        | 20/112 [02:05<17:06, 11.16s/it]

 19%|█▉        | 21/112 [02:10<14:04,  9.28s/it]

 20%|█▉        | 22/112 [02:20<14:01,  9.36s/it]

 21%|██        | 23/112 [02:24<11:31,  7.77s/it]

 21%|██▏       | 24/112 [02:28<10:02,  6.85s/it]

 22%|██▏       | 25/112 [02:33<08:44,  6.03s/it]

 23%|██▎       | 26/112 [02:42<10:06,  7.06s/it]

 24%|██▍       | 27/112 [02:45<08:20,  5.89s/it]

 25%|██▌       | 28/112 [02:49<07:12,  5.15s/it]ERROR: [youtube] 5Nmimj-Gycc: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 26%|██▌       | 29/112 [02:49<05:11,  3.75s/it]

 27%|██▋       | 30/112 [02:53<05:04,  3.72s/it]

 28%|██▊       | 31/112 [03:41<23:01, 17.06s/it]

 29%|██▊       | 32/112 [03:46<17:55, 13.45s/it]

 29%|██▉       | 33/112 [03:49<13:49, 10.49s/it]

 30%|███       | 34/112 [03:55<11:40,  8.98s/it]

 31%|███▏      | 35/112 [03:59<09:40,  7.54s/it]

 32%|███▏      | 36/112 [04:03<08:09,  6.45s/it]

 33%|███▎      | 37/112 [04:11<08:27,  6.77s/it]

 34%|███▍      | 38/112 [04:15<07:32,  6.11s/it]

 35%|███▍      | 39/112 [04:19<06:36,  5.43s/it]

 36%|███▌      | 40/112 [04:23<05:52,  4.90s/it]

 37%|███▋      | 41/112 [04:34<08:00,  6.77s/it]

 38%|███▊      | 42/112 [04:39<07:21,  6.31s/it]ERROR: [youtube] 81xMhkd8lCI: Video unavailable. This video contains content from ShallAdoreCats. It is not available in your country.
 38%|███▊      | 43/112 [04:40<05:23,  4.69s/it]

 39%|███▉      | 44/112 [04:44<05:06,  4.51s/it]ERROR: [youtube] 8MX03zX_ubE: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 40%|████      | 45/112 [04:45<03:42,  3.32s/it]

 41%|████      | 46/112 [04:48<03:50,  3.49s/it]

 42%|████▏     | 47/112 [04:53<04:16,  3.94s/it]

 43%|████▎     | 48/112 [04:57<04:13,  3.96s/it]

 44%|████▍     | 49/112 [05:02<04:19,  4.13s/it]

 45%|████▍     | 50/112 [05:09<05:10,  5.00s/it]

 46%|████▌     | 51/112 [05:17<05:57,  5.85s/it]

 46%|████▋     | 52/112 [05:21<05:13,  5.23s/it]ERROR: [youtube] IMDBu-_mRks: Video unavailable
 47%|████▋     | 53/112 [05:21<03:46,  3.83s/it]

 48%|████▊     | 54/112 [05:28<04:31,  4.69s/it]

 49%|████▉     | 55/112 [05:32<04:16,  4.51s/it]ERROR: [youtube] KVyTY6NAXL8: Video unavailable
 50%|█████     | 56/112 [05:32<03:04,  3.30s/it]

 51%|█████     | 57/112 [05:41<04:32,  4.96s/it]ERROR: [youtube] M8L7MYwiba0: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 52%|█████▏    | 58/112 [05:42<03:15,  3.62s/it]

 53%|█████▎    | 59/112 [05:50<04:25,  5.01s/it]

 54%|█████▎    | 60/112 [06:06<07:16,  8.39s/it]

 54%|█████▍    | 61/112 [06:12<06:24,  7.55s/it]ERROR: [youtube] Nd59zdocNuI: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 55%|█████▌    | 62/112 [06:12<04:31,  5.42s/it]

 56%|█████▋    | 63/112 [06:16<04:06,  5.03s/it]

ERROR: unable to download video data: HTTP Error 403: Forbidden
 57%|█████▋    | 64/112 [06:28<05:36,  7.01s/it]

 58%|█████▊    | 65/112 [06:33<05:02,  6.43s/it]ERROR: [youtube] Qt1aCUq51ns: Video unavailable
 59%|█████▉    | 66/112 [06:34<03:35,  4.69s/it]ERROR: [youtube] Rnd7f2AGGuI: Video unavailable
 60%|█████▉    | 67/112 [06:34<02:34,  3.43s/it]

 61%|██████    | 68/112 [06:42<03:33,  4.84s/it]

 62%|██████▏   | 69/112 [06:46<03:17,  4.60s/it]

 62%|██████▎   | 70/112 [06:50<03:06,  4.44s/it]

 63%|██████▎   | 71/112 [06:56<03:17,  4.83s/it]

 64%|██████▍   | 72/112 [07:02<03:28,  5.21s/it]

 65%|██████▌   | 73/112 [07:26<06:57, 10.71s/it]

 66%|██████▌   | 74/112 [07:33<06:04,  9.58s/it]

 67%|██████▋   | 75/112 [07:40<05:26,  8.83s/it]ERROR: [youtube] XNJhMEOpYdE: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 68%|██████▊   | 76/112 [07:40<03:47,  6.32s/it]ERROR: [youtube] Yamxf-UkucM: This video has been removed for violating YouTube's policy on violent or graphic content
 69%|██████▉   | 77/112 [07:41<02:40,  4.57s/it]ERROR: [youtube] _Hy1qLguDbs: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 70%|██████▉   | 78/112 [07:41<01:53,  3.34s/it]

 71%|███████   | 79/112 [07:49<02:30,  4.57s/it]

 71%|███████▏  | 80/112 [07:58<03:13,  6.05s/it]

 72%|███████▏  | 81/112 [08:01<02:40,  5.19s/it]

 73%|███████▎  | 82/112 [08:05<02:25,  4.84s/it]

 74%|███████▍  | 83/112 [08:11<02:26,  5.06s/it]

 75%|███████▌  | 84/112 [08:14<02:07,  4.57s/it]

 76%|███████▌  | 85/112 [08:18<01:51,  4.11s/it]ERROR: [youtube] ekntD-DM2sU: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 77%|███████▋  | 86/112 [08:18<01:18,  3.03s/it]

 78%|███████▊  | 87/112 [08:34<02:52,  6.91s/it]

 79%|███████▊  | 88/112 [08:38<02:28,  6.18s/it]ERROR: [youtube] ggwKZh6TsNU: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 79%|███████▉  | 89/112 [08:39<01:42,  4.48s/it]

 80%|████████  | 90/112 [08:44<01:43,  4.71s/it]

 81%|████████▏ | 91/112 [08:48<01:35,  4.54s/it]

 82%|████████▏ | 92/112 [09:00<02:11,  6.57s/it]ERROR: [youtube] lUP2iPc4i3Q: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 83%|████████▎ | 93/112 [09:00<01:30,  4.75s/it]ERROR: [youtube] lWYgNQCQqIA: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 84%|████████▍ | 94/112 [09:01<01:02,  3.47s/it]

 85%|████████▍ | 95/112 [09:04<00:57,  3.41s/it]ERROR: [youtube] mTywScWhTxI: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 86%|████████▌ | 96/112 [09:04<00:40,  2.54s/it]

 87%|████████▋ | 97/112 [09:08<00:42,  2.81s/it]

 88%|████████▊ | 98/112 [09:12<00:46,  3.34s/it]

 88%|████████▊ | 99/112 [09:21<01:02,  4.80s/it]

 89%|████████▉ | 100/112 [09:31<01:16,  6.34s/it]

 90%|█████████ | 101/112 [09:37<01:09,  6.35s/it]

 91%|█████████ | 102/112 [09:40<00:54,  5.50s/it]

 92%|█████████▏| 103/112 [10:17<02:13, 14.83s/it]

 93%|█████████▎| 104/112 [10:21<01:33, 11.67s/it]

 94%|█████████▍| 105/112 [10:25<01:05,  9.40s/it]

 95%|█████████▍| 106/112 [10:29<00:45,  7.64s/it]

 96%|█████████▌| 107/112 [10:36<00:37,  7.45s/it]

 96%|█████████▋| 108/112 [10:40<00:25,  6.40s/it]ERROR: [youtube] wEmEkLQDl0U: Video unavailable
 97%|█████████▋| 109/112 [10:40<00:13,  4.62s/it]

 98%|█████████▊| 110/112 [10:44<00:08,  4.27s/it]

 99%|█████████▉| 111/112 [10:49<00:04,  4.43s/it]

100%|██████████| 112/112 [10:56<00:00,  5.86s/it]

# Stealing YouTube videos but moooore🕺

In [2]:
import pandas as pd

balanced_videos_path = "data/video-data/unbalanced_train_segments.csv"

# Read CSV with Python engine and comma as delimiter
df = pd.read_csv(
    balanced_videos_path, 
    engine='python',   # better for messy CSVs
    skipinitialspace=True,
    quotechar='"'      # respect quoted strings
)

# Remove leading '--' in the YTID column
df['YTID'] = df['YTID'].str.lstrip('-')

# Convert last column (positive_labels) from string to list
df['positive_labels'] = df['positive_labels'].apply(
    lambda s: [x.strip() for x in s.strip('"').split(',')]
)

df.head()

,YTID,start_seconds,end_seconds,positive_labels
0,1_cCGK4M,0.0,10.0,"[/m/01g50p, /m/0284vy3, /m/06d_3, /m/07jdr, /m..."
1,2_BBVHAA,30.0,40.0,[/m/09x0r]
2,B_v8ZoBY,30.0,40.0,[/m/04rlf]
3,EDNidJUA,30.0,40.0,"[/m/02qldy, /m/02zsn, /m/05zppz, /m/09x0r]"
4,N4cFAE1A,21.0,31.0,"[/m/04rlf, /m/09x0r]"

In [3]:
# 2️⃣ Load the mapping CSV
label_map_path = "data/video-data/class_labels_indices.csv"
label_df = pd.read_csv(label_map_path)

# Build a dictionary: mid -> display_name
label_dict = dict(zip(label_df['mid'], label_df['display_name']))

# 3️⃣ Map each list of positive_labels to their display names
df['positive_labels_names'] = df['positive_labels'].apply(
    lambda lst: [label_dict.get(mid, mid) for mid in lst]
)

In [4]:
df.shape

(2041789, 5)

In [5]:
df.sample(3)

,YTID,start_seconds,end_seconds,positive_labels,positive_labels_names
361279,5Y_WHK8l86Q,30.0,40.0,"[/m/09x0r, /t/dd00125]","[Speech, Inside, small room]"
420268,6uDsMOHpCK8,30.0,40.0,"[/m/04rlf, /m/09x0r]","[Music, Speech]"
951239,M1IC55KxO3I,30.0,40.0,[/m/04rlf],[Music]

In [6]:
# Filter rows where 'positive_labels_names' contains 'Car' (case-insensitive)
cat_rows = df[df['positive_labels_names'].apply(
    lambda labels: any(label.lower() == "cat" for label in labels)
)]

cat_rows = cat_rows[cat_rows['YTID'].str.len() == 11]

cat_rows.shape

(3599, 5)

In [10]:
cat_rows.sample(3)

,YTID,start_seconds,end_seconds,positive_labels,positive_labels_names
1002773,Nh-0sVtY4p8,18.0,28.0,"[/m/01yrx, /m/068hy, /m/07qrkrw, /m/09x0r, /m/...","[Cat, Domestic animals, pets, Meow, Speech, An..."
1990816,xs5wYGHyqhE,60.0,70.0,"[/m/01yrx, /m/02yds9, /m/068hy, /m/0jbk]","[Cat, Purr, Domestic animals, pets, Animal]"
337634,52Pr5Bm3RUQ,6.0,16.0,"[/m/01yrx, /m/068hy, /m/07qrkrw, /m/0jbk]","[Cat, Domestic animals, pets, Meow, Animal]"

In [13]:
from tqdm import tqdm
import json
import os

In [11]:
log_file = "downloading_unbalanced_logs.jsonl"

In [19]:
with open(log_file, "a") as f:
    for idx, row in tqdm(cat_rows.iterrows(), total=len(cat_rows)):
        video_id = str(row["YTID"]).strip("-").strip()  # remove leading '-' or spaces

        if not video_id:  # skip empty IDs
            print(f"⚠️ Skipping empty/truncated ID at row {idx}")
            continue

        try:
            video_info = download_video(
                video_idx=video_id,
                output_folder="downloads/VideoDataUnbalanced"
            )

            if video_info is None:
                metadata = {
                    "video_id": row["YTID"],
                    "error" : f"⚠️ No info returned for {video_id}, skipping"
                }
                f.write(json.dumps(metadata, ensure_ascii=False) + "\n")
                continue

            metadata = {
                **video_info,
                "start_seconds": row["start_seconds"],
                "end_seconds": row["end_seconds"],
                "positive_labels": row["positive_labels_names"]
            }

            f.write(json.dumps(metadata, ensure_ascii=False) + "\n")

        except Exception as e:
            metadata = {
                "video_id": row["YTID"],
                "error" : e
            }
            f.write(json.dumps(metadata, ensure_ascii=False) + "\n")
            continue

  0%|          | 0/3599 [00:00<?, ?it/s]

  0%|          | 1/3599 [00:09<9:33:18,  9.56s/it]ERROR: [youtube] 01C7RT05TfI: Video unavailable
  0%|          | 2/3599 [00:10<4:14:53,  4.25s/it]

  0%|          | 3/3599 [00:14<4:06:09,  4.11s/it]

  0%|          | 4/3599 [00:19<4:44:13,  4.74s/it]

  0%|          | 5/3599 [00:23<4:21:13,  4.36s/it]

  0%|          | 6/3599 [00:27<4:15:15,  4.26s/it]

  0%|          | 7/3599 [00:34<5:04:28,  5.09s/it]

  0%|          | 8/3599 [00:39<5:00:08,  5.01s/it]

  0%|          | 9/3599 [00:43<4:56:59,  4.96s/it]

  0%|          | 10/3599 [00:52<5:53:06,  5.90s/it]

  0%|          | 11/3599 [00:58<6:09:39,  6.18s/it]ERROR: [youtube] 04sf3v7xOzo: Video unavailable
  0%|          | 12/3599 [00:59<4:26:15,  4.45s/it]

  0%|          | 13/3599 [01:07<5:25:46,  5.45s/it]ERROR: [youtube] 05VUKTc3g8A: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
  0%|          | 14/3599 [01:07<3:56:12,  3.95s/it]ERROR: [youtube] 05pgKzVdOxA: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  0%|          | 15/3599 [01:08<2:54:59,  2.93s/it]ERROR: [youtube] 0632OqvXrwg: This video has been removed for violating YouTube's Terms of Service
  0%|          | 16/3599 [01:08<2:11:25,  2.20s/it]ERROR: [youtube] 06Mm032486Q: Video unavailable
  0%|          | 17/3599 [01:09<1:41:26,  1.70s/it]

  1%|          | 18/3599 [01:12<2:12:21,  2.22s/it]

  1%|          | 19/3599 [01:16<2:48:53,  2.83s/it]

  1%|          | 20/3599 [01:20<2:58:22,  2.99s/it]

  1%|          | 21/3599 [01:24<3:24:22,  3.43s/it]

  1%|          | 22/3599 [01:33<5:02:51,  5.08s/it]

  1%|          | 23/3599 [01:37<4:40:18,  4.70s/it]ERROR: [youtube] 0Ahw0J1vneo: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  1%|          | 24/3599 [01:37<3:25:05,  3.44s/it]

  1%|          | 25/3599 [01:44<4:27:57,  4.50s/it]

  1%|          | 26/3599 [01:49<4:26:30,  4.48s/it]

  1%|          | 27/3599 [01:56<5:07:24,  5.16s/it]ERROR: [youtube] 0CEQ565DH_A: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  1%|          | 28/3599 [01:56<3:44:26,  3.77s/it]

  1%|          | 29/3599 [02:00<3:46:00,  3.80s/it]

  1%|          | 30/3599 [02:06<4:31:02,  4.56s/it]

  1%|          | 31/3599 [02:10<4:24:04,  4.44s/it]

  1%|          | 32/3599 [02:20<5:53:45,  5.95s/it]

  1%|          | 33/3599 [02:26<5:47:52,  5.85s/it]

  1%|          | 34/3599 [02:31<5:38:35,  5.70s/it]

  1%|          | 35/3599 [02:38<6:11:02,  6.25s/it]

  1%|          | 36/3599 [02:44<6:01:59,  6.10s/it]

  1%|          | 37/3599 [02:59<8:45:36,  8.85s/it]

  1%|          | 38/3599 [03:04<7:34:40,  7.66s/it]

  1%|          | 39/3599 [03:08<6:25:56,  6.50s/it]

  1%|          | 40/3599 [03:14<6:07:51,  6.20s/it]

  1%|          | 41/3599 [03:18<5:37:02,  5.68s/it]

  1%|          | 42/3599 [03:26<6:10:38,  6.25s/it]

  1%|          | 43/3599 [03:29<5:21:39,  5.43s/it]

  1%|          | 44/3599 [03:33<4:54:27,  4.97s/it]

  1%|▏         | 45/3599 [03:38<4:46:46,  4.84s/it]ERROR: [youtube] 0Hswwzo6W9E: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  1%|▏         | 46/3599 [03:38<3:29:42,  3.54s/it]

  1%|▏         | 47/3599 [03:43<3:58:11,  4.02s/it]ERROR: [youtube] 0JBwMNEkT_Q: Video unavailable
  1%|▏         | 48/3599 [03:44<2:59:13,  3.03s/it]

  1%|▏         | 49/3599 [03:49<3:36:30,  3.66s/it]

  1%|▏         | 50/3599 [03:54<3:52:42,  3.93s/it]

  1%|▏         | 51/3599 [04:00<4:43:16,  4.79s/it]

  1%|▏         | 52/3599 [04:06<4:49:37,  4.90s/it]

  1%|▏         | 53/3599 [04:35<12:10:41, 12.36s/it]ERROR: [youtube] 0LvT0CnBxJg: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
  2%|▏         | 54/3599 [04:36<8:41:11,  8.82s/it]

  2%|▏         | 55/3599 [04:44<8:24:50,  8.55s/it]

  2%|▏         | 56/3599 [04:49<7:19:50,  7.45s/it]ERROR: [youtube] 0NV_lqGSV2s: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  2%|▏         | 57/3599 [04:49<5:16:44,  5.37s/it]

  2%|▏         | 58/3599 [04:55<5:23:29,  5.48s/it]

  2%|▏         | 59/3599 [05:03<6:00:47,  6.12s/it]

  2%|▏         | 60/3599 [05:11<6:37:49,  6.74s/it]

  2%|▏         | 61/3599 [05:17<6:36:29,  6.72s/it]

  2%|▏         | 62/3599 [05:31<8:32:06,  8.69s/it]

  2%|▏         | 63/3599 [05:35<7:10:14,  7.30s/it]

  2%|▏         | 64/3599 [05:40<6:26:12,  6.56s/it]ERROR: [youtube] 0R4uO4Vy9c0: This video has been removed for violating YouTube's Terms of Service
  2%|▏         | 65/3599 [05:40<4:38:46,  4.73s/it]

  2%|▏         | 66/3599 [05:46<4:51:34,  4.95s/it]

  2%|▏         | 67/3599 [05:52<5:15:59,  5.37s/it]

  2%|▏         | 68/3599 [05:59<5:47:46,  5.91s/it]

  2%|▏         | 69/3599 [06:07<6:18:49,  6.44s/it]

  2%|▏         | 70/3599 [06:14<6:24:46,  6.54s/it]

  2%|▏         | 71/3599 [06:18<5:42:25,  5.82s/it]

  2%|▏         | 72/3599 [06:23<5:33:02,  5.67s/it]ERROR: [youtube] 0SyV6B-5WUk: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  2%|▏         | 73/3599 [06:24<4:02:52,  4.13s/it]

  2%|▏         | 74/3599 [06:33<5:31:34,  5.64s/it]

  2%|▏         | 75/3599 [06:38<5:31:45,  5.65s/it]

  2%|▏         | 76/3599 [06:44<5:28:36,  5.60s/it]

  2%|▏         | 77/3599 [06:49<5:21:18,  5.47s/it]

  2%|▏         | 78/3599 [06:54<5:13:23,  5.34s/it]

  2%|▏         | 79/3599 [07:02<6:05:12,  6.23s/it]

  2%|▏         | 80/3599 [07:20<9:32:35,  9.76s/it]

  2%|▏         | 81/3599 [07:27<8:35:05,  8.78s/it]

  2%|▏         | 82/3599 [07:39<9:41:19,  9.92s/it]ERROR: [youtube] 0XBpP1gexGY: Video unavailable
  2%|▏         | 83/3599 [07:40<6:56:21,  7.11s/it]

  2%|▏         | 84/3599 [07:46<6:32:52,  6.71s/it]

  2%|▏         | 85/3599 [07:50<5:55:53,  6.08s/it]

  2%|▏         | 86/3599 [08:16<11:41:33, 11.98s/it]

  2%|▏         | 87/3599 [08:20<9:25:30,  9.66s/it] ERROR: [youtube] 0_df4aMkh5Q: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  2%|▏         | 88/3599 [08:21<6:44:50,  6.92s/it]

  2%|▏         | 89/3599 [08:25<6:02:46,  6.20s/it]

  3%|▎         | 90/3599 [08:30<5:26:54,  5.59s/it]

  3%|▎         | 91/3599 [08:33<4:56:58,  5.08s/it]

  3%|▎         | 92/3599 [09:58<28:08:24, 28.89s/it]ERROR: [youtube] 0bj1ynHjnR8: Video unavailable
  3%|▎         | 93/3599 [09:58<19:51:08, 20.38s/it]

  3%|▎         | 94/3599 [10:03<15:11:20, 15.60s/it]ERROR: [youtube] 0cH_NlhhMAs: Video unavailable
  3%|▎         | 95/3599 [10:04<10:48:20, 11.10s/it]

  3%|▎         | 96/3599 [10:36<16:59:52, 17.47s/it]

  3%|▎         | 97/3599 [10:43<13:52:56, 14.27s/it]

  3%|▎         | 98/3599 [10:48<11:15:04, 11.57s/it]

  3%|▎         | 99/3599 [10:55<9:51:40, 10.14s/it]

  3%|▎         | 100/3599 [11:18<13:33:13, 13.95s/it]

  3%|▎         | 101/3599 [11:22<10:50:27, 11.16s/it]ERROR: [youtube] 0eQE2xtSOAM: Video unavailable
  3%|▎         | 102/3599 [11:23<7:44:26,  7.97s/it]

  3%|▎         | 103/3599 [11:32<8:09:24,  8.40s/it]ERROR: [youtube] 0fbZ0tskFjw: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
  3%|▎         | 104/3599 [11:33<5:52:01,  6.04s/it]

  3%|▎         | 105/3599 [11:48<8:30:28,  8.77s/it]

  3%|▎         | 106/3599 [11:53<7:24:03,  7.63s/it]

  3%|▎         | 107/3599 [12:01<7:26:07,  7.67s/it]ERROR: [youtube] 0hH10rnwBuI: Video unavailable
  3%|▎         | 108/3599 [12:01<5:24:42,  5.58s/it]

  3%|▎         | 109/3599 [12:09<5:56:12,  6.12s/it]

  3%|▎         | 110/3599 [12:13<5:32:31,  5.72s/it]ERROR: [youtube] 0iaK9Evi2_U: Video unavailable. This video is no longer available due to a copyright claim by John Harrington
  3%|▎         | 111/3599 [12:15<4:21:26,  4.50s/it]

  3%|▎         | 112/3599 [12:20<4:26:39,  4.59s/it]

  3%|▎         | 113/3599 [12:27<5:06:58,  5.28s/it]

  3%|▎         | 114/3599 [12:30<4:39:52,  4.82s/it]ERROR: [youtube] 0kN-0Fd438w: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
  3%|▎         | 115/3599 [12:31<3:24:29,  3.52s/it]

  3%|▎         | 116/3599 [12:36<3:51:32,  3.99s/it]ERROR: [youtube] 0kY6vhTc4yE: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  3%|▎         | 117/3599 [12:37<2:52:23,  2.97s/it]

  3%|▎         | 118/3599 [13:30<17:21:42, 17.96s/it]

  3%|▎         | 119/3599 [13:34<13:29:32, 13.96s/it]ERROR: [youtube] 0lNm9pXXHxA: This video has been removed for violating YouTube's Terms of Service
  3%|▎         | 120/3599 [13:35<9:36:23,  9.94s/it]

  3%|▎         | 121/3599 [13:39<7:57:06,  8.23s/it]

  3%|▎         | 122/3599 [13:50<8:47:30,  9.10s/it]ERROR: [youtube] 0nqVe_y7Ckk: This video has been removed for violating YouTube's Terms of Service
  3%|▎         | 123/3599 [13:51<6:20:49,  6.57s/it]

  3%|▎         | 124/3599 [13:56<6:01:29,  6.24s/it]

  3%|▎         | 125/3599 [14:02<5:56:08,  6.15s/it]ERROR: [youtube] 0pwGyKKQRPU: Video unavailable
  4%|▎         | 126/3599 [14:03<4:18:32,  4.47s/it]

  4%|▎         | 127/3599 [14:09<4:46:38,  4.95s/it]

  4%|▎         | 128/3599 [14:14<4:52:37,  5.06s/it]ERROR: [youtube] 0qzvvMd5dvo: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
  4%|▎         | 129/3599 [14:15<3:35:32,  3.73s/it]

  4%|▎         | 130/3599 [14:20<3:53:19,  4.04s/it]ERROR: [youtube] 0s9lF2C_AqE: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
  4%|▎         | 131/3599 [14:20<2:51:59,  2.98s/it]ERROR: [youtube] 0tJBwSNGP5s: Video unavailable
  4%|▎         | 132/3599 [14:21<2:10:38,  2.26s/it]ERROR: [youtube] 0tVL3VFW5Zs: Video unavailable
  4%|▎         | 133/3599 [14:21<1:42:37,  1.78s/it]

  4%|▎         | 134/3599 [14:27<2:47:40,  2.90s/it]

  4%|▍         | 135/3599 [14:31<3:11:58,  3.33s/it]

  4%|▍         | 136/3599 [14:42<5:18:43,  5.52s/it]

  4%|▍         | 137/3599 [14:59<8:38:40,  8.99s/it]

  4%|▍         | 138/3599 [15:03<7:20:36,  7.64s/it]

  4%|▍         | 139/3599 [15:08<6:33:50,  6.83s/it]ERROR: [youtube] 0xhygj2rhpk: Video unavailable
  4%|▍         | 140/3599 [15:09<4:44:49,  4.94s/it]ERROR: [youtube] 0xzbWmrJCa0: Video unavailable
  4%|▍         | 141/3599 [15:09<3:28:19,  3.61s/it]

  4%|▍         | 142/3599 [15:15<3:57:09,  4.12s/it]ERROR: [youtube] 0ylf1enGlGw: Video unavailable
  4%|▍         | 143/3599 [15:15<2:54:52,  3.04s/it]ERROR: [youtube] 0zYmZQGvn70: Video unavailable
  4%|▍         | 144/3599 [15:16<2:11:51,  2.29s/it]

  4%|▍         | 145/3599 [15:20<2:41:17,  2.80s/it]ERROR: [youtube] 0zv4NcZfYhE: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  4%|▍         | 146/3599 [15:20<2:01:55,  2.12s/it]

  4%|▍         | 147/3599 [15:24<2:35:36,  2.70s/it]

  4%|▍         | 148/3599 [15:29<3:14:10,  3.38s/it]

  4%|▍         | 149/3599 [15:45<6:55:04,  7.22s/it]

  4%|▍         | 150/3599 [15:49<5:56:39,  6.20s/it]ERROR: [youtube] 10GZycmQEeI: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  4%|▍         | 151/3599 [15:50<4:19:04,  4.51s/it]

  4%|▍         | 152/3599 [15:55<4:34:23,  4.78s/it]ERROR: [youtube] 11Yjw2H8XsQ: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  4%|▍         | 153/3599 [15:56<3:20:57,  3.50s/it]

  4%|▍         | 154/3599 [16:00<3:34:35,  3.74s/it]ERROR: [youtube] 11rKpXBR_ck: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
  4%|▍         | 155/3599 [16:01<2:39:14,  2.77s/it]

  4%|▍         | 156/3599 [16:05<3:13:29,  3.37s/it]

  4%|▍         | 157/3599 [16:22<7:02:55,  7.37s/it]

  4%|▍         | 158/3599 [16:29<6:52:14,  7.19s/it]

  4%|▍         | 159/3599 [16:37<7:15:53,  7.60s/it]ERROR: [youtube] 141v5oRfUHM: Video unavailable
  4%|▍         | 160/3599 [16:38<5:14:05,  5.48s/it]

  4%|▍         | 161/3599 [16:42<4:53:57,  5.13s/it]

  5%|▍         | 162/3599 [16:47<4:40:33,  4.90s/it]

  5%|▍         | 163/3599 [16:50<4:17:10,  4.49s/it]

  5%|▍         | 164/3599 [16:54<4:13:47,  4.43s/it]

  5%|▍         | 165/3599 [17:02<5:15:45,  5.52s/it]

  5%|▍         | 166/3599 [17:07<5:07:43,  5.38s/it]

  5%|▍         | 167/3599 [17:15<5:38:51,  5.92s/it]

  5%|▍         | 168/3599 [17:25<6:46:40,  7.11s/it]ERROR: [youtube] 17yb2wrvWms: Video unavailable
  5%|▍         | 169/3599 [17:25<4:54:41,  5.16s/it]ERROR: [youtube] 18FN3fDI25A: Sign in to confirm your age. This video may be inappropriate for some users. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  5%|▍         | 170/3599 [17:26<3:48:33,  4.00s/it]

  5%|▍         | 171/3599 [17:31<3:54:04,  4.10s/it]

  5%|▍         | 172/3599 [17:36<4:09:16,  4.36s/it]

  5%|▍         | 173/3599 [17:45<5:29:42,  5.77s/it]

[download] Got error: HTTP Error 500: Internal Server Error
  5%|▍         | 175/3599 [17:57<5:53:27,  6.19s/it]

  5%|▍         | 176/3599 [18:02<5:30:56,  5.80s/it]

  5%|▍         | 177/3599 [18:06<5:04:33,  5.34s/it]

  5%|▍         | 178/3599 [18:10<4:42:38,  4.96s/it]

  5%|▍         | 179/3599 [18:16<4:44:44,  5.00s/it]

  5%|▌         | 180/3599 [18:22<5:08:25,  5.41s/it]

  5%|▌         | 181/3599 [18:30<5:47:13,  6.10s/it]

  5%|▌         | 182/3599 [18:36<5:50:09,  6.15s/it]

  5%|▌         | 183/3599 [18:41<5:40:49,  5.99s/it]

  5%|▌         | 184/3599 [18:47<5:36:32,  5.91s/it]

  5%|▌         | 185/3599 [18:54<5:57:35,  6.28s/it]ERROR: [youtube] 1IjQok7rlEo: Video unavailable
  5%|▌         | 186/3599 [18:55<4:19:42,  4.57s/it]

  5%|▌         | 187/3599 [18:59<4:06:01,  4.33s/it]

  5%|▌         | 188/3599 [19:03<4:01:10,  4.24s/it]ERROR: [youtube] 1KFRlXZfnIA: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  5%|▌         | 189/3599 [19:03<2:57:03,  3.12s/it]

  5%|▌         | 190/3599 [19:17<6:00:05,  6.34s/it]

  5%|▌         | 191/3599 [19:21<5:12:49,  5.51s/it]

  5%|▌         | 192/3599 [19:28<5:36:36,  5.93s/it]

  5%|▌         | 193/3599 [19:32<5:07:53,  5.42s/it]

  5%|▌         | 194/3599 [19:48<8:06:59,  8.58s/it]

  5%|▌         | 195/3599 [19:54<7:28:15,  7.90s/it]

  5%|▌         | 196/3599 [19:59<6:32:00,  6.91s/it]

  5%|▌         | 197/3599 [20:03<5:46:59,  6.12s/it]

  6%|▌         | 198/3599 [20:11<6:11:58,  6.56s/it]

  6%|▌         | 199/3599 [20:17<6:10:13,  6.53s/it]

  6%|▌         | 200/3599 [20:22<5:36:12,  5.93s/it]

  6%|▌         | 201/3599 [20:31<6:35:51,  6.99s/it]

  6%|▌         | 202/3599 [20:35<5:43:37,  6.07s/it]

  6%|▌         | 203/3599 [20:40<5:19:04,  5.64s/it]

  6%|▌         | 204/3599 [20:46<5:40:57,  6.03s/it]

  6%|▌         | 205/3599 [20:57<6:52:13,  7.29s/it]ERROR: [youtube] 1T0iOEd4sy0: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
  6%|▌         | 206/3599 [20:57<4:57:34,  5.26s/it]

  6%|▌         | 207/3599 [21:02<4:45:22,  5.05s/it]ERROR: [youtube] 1U1k-d1x1qw: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  6%|▌         | 208/3599 [21:02<3:29:04,  3.70s/it]

  6%|▌         | 209/3599 [21:10<4:38:23,  4.93s/it]

  6%|▌         | 210/3599 [21:16<4:49:48,  5.13s/it]

  6%|▌         | 211/3599 [21:23<5:33:38,  5.91s/it]

  6%|▌         | 212/3599 [21:28<5:15:04,  5.58s/it]

  6%|▌         | 213/3599 [21:36<5:55:40,  6.30s/it]

  6%|▌         | 214/3599 [21:40<5:14:00,  5.57s/it]

  6%|▌         | 215/3599 [21:48<5:49:02,  6.19s/it]

  6%|▌         | 216/3599 [22:01<7:51:32,  8.36s/it]

  6%|▌         | 217/3599 [22:05<6:30:12,  6.92s/it]

  6%|▌         | 218/3599 [22:09<5:41:05,  6.05s/it]

  6%|▌         | 219/3599 [22:14<5:25:19,  5.78s/it]

  6%|▌         | 220/3599 [22:19<5:08:24,  5.48s/it]

  6%|▌         | 221/3599 [22:26<5:36:28,  5.98s/it]

  6%|▌         | 222/3599 [22:30<5:00:49,  5.34s/it]

  6%|▌         | 223/3599 [22:34<4:46:52,  5.10s/it]

  6%|▌         | 224/3599 [22:39<4:41:03,  5.00s/it]

  6%|▋         | 225/3599 [22:44<4:33:39,  4.87s/it]

  6%|▋         | 226/3599 [22:49<4:43:39,  5.05s/it]

  6%|▋         | 227/3599 [22:54<4:37:30,  4.94s/it]

  6%|▋         | 228/3599 [22:58<4:26:17,  4.74s/it]

  6%|▋         | 229/3599 [23:02<4:17:34,  4.59s/it]ERROR: [youtube] 1_xewpKYwbM: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  6%|▋         | 230/3599 [23:03<3:09:28,  3.37s/it]

  6%|▋         | 231/3599 [23:09<3:54:39,  4.18s/it]

  6%|▋         | 232/3599 [23:13<3:54:36,  4.18s/it]ERROR: [youtube] 1bdZx2gFZ2w: Video unavailable
  6%|▋         | 233/3599 [23:14<2:52:42,  3.08s/it]

  7%|▋         | 234/3599 [23:19<3:27:08,  3.69s/it]

  7%|▋         | 235/3599 [23:36<7:11:14,  7.69s/it]

  7%|▋         | 236/3599 [23:40<6:19:42,  6.77s/it]ERROR: [youtube] 1cSeAysUdek: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
  7%|▋         | 237/3599 [23:41<4:35:28,  4.92s/it]

  7%|▋         | 238/3599 [23:45<4:26:02,  4.75s/it]ERROR: [youtube] 1cmL8faF7W8: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
  7%|▋         | 239/3599 [23:46<3:14:36,  3.48s/it]

  7%|▋         | 240/3599 [23:49<3:18:58,  3.55s/it]

  7%|▋         | 241/3599 [23:55<3:46:13,  4.04s/it]

  7%|▋         | 242/3599 [24:00<3:59:29,  4.28s/it]

  7%|▋         | 243/3599 [24:07<5:01:44,  5.39s/it]

  7%|▋         | 244/3599 [24:13<5:01:10,  5.39s/it]

  7%|▋         | 245/3599 [24:17<4:44:03,  5.08s/it]

  7%|▋         | 246/3599 [24:21<4:29:05,  4.82s/it]ERROR: [youtube] 1hAr0kYvhuY: Video unavailable
  7%|▋         | 247/3599 [24:22<3:17:09,  3.53s/it]

  7%|▋         | 248/3599 [24:30<4:32:18,  4.88s/it]

  7%|▋         | 249/3599 [24:35<4:41:49,  5.05s/it]

  7%|▋         | 250/3599 [24:39<4:25:07,  4.75s/it]

  7%|▋         | 251/3599 [24:45<4:45:34,  5.12s/it]ERROR: [youtube] 1koKc-H8Ehk: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  7%|▋         | 252/3599 [24:46<3:28:20,  3.73s/it]

  7%|▋         | 253/3599 [24:51<3:55:36,  4.23s/it]

  7%|▋         | 254/3599 [24:57<4:14:33,  4.57s/it]

  7%|▋         | 255/3599 [25:03<4:39:49,  5.02s/it]

  7%|▋         | 256/3599 [25:07<4:33:43,  4.91s/it]

  7%|▋         | 257/3599 [25:36<11:11:16, 12.05s/it]

  7%|▋         | 258/3599 [25:42<9:32:05, 10.27s/it]

  7%|▋         | 259/3599 [25:53<9:34:51, 10.33s/it]

  7%|▋         | 260/3599 [26:01<9:02:21,  9.75s/it]ERROR: [youtube] 1owUfrSLOEg: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  7%|▋         | 261/3599 [26:02<6:27:31,  6.97s/it]

  7%|▋         | 262/3599 [26:10<6:56:09,  7.48s/it]

  7%|▋         | 263/3599 [26:19<7:12:49,  7.78s/it]ERROR: [youtube] 1r3zT08hufg: Video unavailable
  7%|▋         | 264/3599 [26:19<5:11:11,  5.60s/it]

  7%|▋         | 265/3599 [26:23<4:42:24,  5.08s/it]ERROR: [youtube] 1rurDIQEr3Q: Video unavailable
  7%|▋         | 266/3599 [26:24<3:30:34,  3.79s/it]

  7%|▋         | 267/3599 [26:29<3:48:50,  4.12s/it]

  7%|▋         | 268/3599 [26:34<4:06:19,  4.44s/it]

  7%|▋         | 269/3599 [26:43<5:26:57,  5.89s/it]

  8%|▊         | 270/3599 [26:47<4:58:10,  5.37s/it]

  8%|▊         | 271/3599 [26:53<5:04:11,  5.48s/it]

  8%|▊         | 272/3599 [26:59<5:06:03,  5.52s/it]

  8%|▊         | 273/3599 [27:06<5:40:54,  6.15s/it]

  8%|▊         | 274/3599 [27:14<6:11:34,  6.71s/it]ERROR: [youtube] 1unwD8sPZfE: Video unavailable
  8%|▊         | 275/3599 [27:15<4:28:48,  4.85s/it]

  8%|▊         | 276/3599 [27:19<4:23:04,  4.75s/it]

  8%|▊         | 277/3599 [27:24<4:26:19,  4.81s/it]

  8%|▊         | 278/3599 [27:29<4:16:54,  4.64s/it]ERROR: [youtube] 1wTYC26te1E: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  8%|▊         | 279/3599 [27:29<3:09:01,  3.42s/it]

  8%|▊         | 280/3599 [27:34<3:26:38,  3.74s/it]

  8%|▊         | 281/3599 [27:37<3:21:12,  3.64s/it]

  8%|▊         | 282/3599 [27:43<4:01:40,  4.37s/it]

  8%|▊         | 283/3599 [27:50<4:42:50,  5.12s/it]

  8%|▊         | 284/3599 [27:58<5:24:55,  5.88s/it]

  8%|▊         | 285/3599 [28:04<5:30:38,  5.99s/it]

  8%|▊         | 286/3599 [28:08<5:04:10,  5.51s/it]ERROR: [youtube] 1zEJWzqb59A: Video unavailable
  8%|▊         | 287/3599 [28:09<3:41:30,  4.01s/it]

  8%|▊         | 288/3599 [28:13<3:49:07,  4.15s/it]

  8%|▊         | 289/3599 [28:26<6:16:04,  6.82s/it]

  8%|▊         | 290/3599 [28:32<5:55:59,  6.45s/it]

  8%|▊         | 291/3599 [28:39<5:58:19,  6.50s/it]

  8%|▊         | 292/3599 [28:47<6:27:39,  7.03s/it]

  8%|▊         | 293/3599 [28:51<5:47:01,  6.30s/it]ERROR: [youtube] 21FtyAydh3Y: Video unavailable
  8%|▊         | 294/3599 [28:52<4:11:13,  4.56s/it]

  8%|▊         | 295/3599 [29:01<5:24:54,  5.90s/it]

  8%|▊         | 296/3599 [29:06<5:12:51,  5.68s/it]

  8%|▊         | 297/3599 [29:10<4:50:50,  5.28s/it]ERROR: [youtube] 22Hfabb4hrY: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  8%|▊         | 298/3599 [29:11<3:35:12,  3.91s/it]

  8%|▊         | 299/3599 [29:38<10:00:22, 10.92s/it]

  8%|▊         | 300/3599 [29:44<8:37:19,  9.41s/it]

  8%|▊         | 301/3599 [29:49<7:18:06,  7.97s/it]

  8%|▊         | 302/3599 [29:53<6:15:38,  6.84s/it]

  8%|▊         | 303/3599 [29:58<5:40:35,  6.20s/it]

  8%|▊         | 304/3599 [30:03<5:18:28,  5.80s/it]

  8%|▊         | 305/3599 [30:10<5:36:48,  6.13s/it]

  9%|▊         | 306/3599 [30:14<5:10:41,  5.66s/it]ERROR: [youtube] 2Awp9Nvsb2A: Video unavailable
  9%|▊         | 307/3599 [30:15<3:46:04,  4.12s/it]

  9%|▊         | 308/3599 [30:20<4:09:42,  4.55s/it]

  9%|▊         | 309/3599 [30:32<6:03:07,  6.62s/it]ERROR: [youtube] 2CT42EaIcm4: Video unavailable
  9%|▊         | 310/3599 [30:32<4:23:44,  4.81s/it]

  9%|▊         | 311/3599 [30:41<5:21:50,  5.87s/it]

  9%|▊         | 312/3599 [30:46<5:07:44,  5.62s/it]

  9%|▊         | 313/3599 [30:50<4:41:29,  5.14s/it]

  9%|▊         | 314/3599 [30:55<4:49:01,  5.28s/it]

  9%|▉         | 315/3599 [31:00<4:42:46,  5.17s/it]

  9%|▉         | 316/3599 [31:14<6:56:16,  7.61s/it]ERROR: [youtube] 2EwfFNiNb6Y: Video unavailable
  9%|▉         | 317/3599 [31:14<5:00:34,  5.49s/it]ERROR: [youtube] 2FLWHYDMedQ: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
  9%|▉         | 318/3599 [31:15<3:44:16,  4.10s/it]

  9%|▉         | 319/3599 [31:19<3:40:50,  4.04s/it]

  9%|▉         | 320/3599 [31:44<9:31:55, 10.47s/it]

  9%|▉         | 321/3599 [31:53<8:55:03,  9.79s/it]ERROR: [youtube] 2HNxLN59O5Y: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
  9%|▉         | 322/3599 [31:53<6:24:16,  7.04s/it]

  9%|▉         | 323/3599 [32:03<7:07:56,  7.84s/it]

  9%|▉         | 324/3599 [32:12<7:27:29,  8.20s/it]

  9%|▉         | 325/3599 [32:20<7:30:52,  8.26s/it]ERROR: [youtube] 2JJ0FOi4b-s: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  9%|▉         | 326/3599 [32:21<5:24:14,  5.94s/it]

  9%|▉         | 327/3599 [32:26<5:14:37,  5.77s/it]

  9%|▉         | 328/3599 [32:34<5:43:58,  6.31s/it]

  9%|▉         | 329/3599 [32:45<6:59:20,  7.69s/it]

  9%|▉         | 330/3599 [32:50<6:27:57,  7.12s/it]ERROR: [youtube] 2KYja87NllQ: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  9%|▉         | 331/3599 [32:51<4:40:23,  5.15s/it]

  9%|▉         | 332/3599 [32:56<4:32:51,  5.01s/it]

  9%|▉         | 333/3599 [33:01<4:40:35,  5.15s/it]

  9%|▉         | 334/3599 [33:08<5:09:48,  5.69s/it]

  9%|▉         | 335/3599 [33:27<8:52:05,  9.78s/it]ERROR: [youtube] 2LPdpxC6KO8: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
  9%|▉         | 336/3599 [33:28<6:22:12,  7.03s/it]ERROR: [youtube] 2LdBI9c3sH4: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  9%|▉         | 337/3599 [33:29<4:35:37,  5.07s/it]

  9%|▉         | 338/3599 [33:33<4:31:01,  4.99s/it]

  9%|▉         | 339/3599 [33:58<9:49:01, 10.84s/it]

  9%|▉         | 340/3599 [34:06<9:11:45, 10.16s/it]

  9%|▉         | 341/3599 [34:12<7:50:27,  8.66s/it]

 10%|▉         | 342/3599 [34:18<7:08:01,  7.89s/it]

 10%|▉         | 343/3599 [34:37<10:20:21, 11.43s/it]ERROR: [youtube] 2P4zD8jYlw8: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 10%|▉         | 344/3599 [34:38<7:22:23,  8.15s/it]

 10%|▉         | 345/3599 [34:52<9:04:31, 10.04s/it]

 10%|▉         | 346/3599 [35:01<8:36:04,  9.52s/it]

 10%|▉         | 347/3599 [35:06<7:21:26,  8.14s/it]

 10%|▉         | 348/3599 [35:12<6:49:06,  7.55s/it]

 10%|▉         | 349/3599 [35:16<6:01:23,  6.67s/it]

 10%|▉         | 350/3599 [35:22<5:52:20,  6.51s/it]

 10%|▉         | 351/3599 [35:27<5:12:17,  5.77s/it]

 10%|▉         | 352/3599 [35:32<5:07:01,  5.67s/it]

 10%|▉         | 353/3599 [35:39<5:24:13,  5.99s/it]

 10%|▉         | 354/3599 [35:51<7:06:09,  7.88s/it]

[download]  13.7% of  141.70MiB at    5.86MiB/s ETA 00:20

ERROR: unable to download video data: HTTP Error 403: Forbidden
 10%|▉         | 355/3599 [36:00<7:20:18,  8.14s/it]ERROR: [youtube] 2ZZcEd3ZvdM: Video unavailable
 10%|▉         | 356/3599 [36:00<5:18:13,  5.89s/it]

 10%|▉         | 357/3599 [36:05<4:59:24,  5.54s/it]

 10%|▉         | 358/3599 [36:10<4:43:08,  5.24s/it]

 10%|▉         | 359/3599 [36:16<4:53:55,  5.44s/it]

 10%|█         | 360/3599 [36:21<4:47:18,  5.32s/it]

 10%|█         | 361/3599 [36:25<4:38:23,  5.16s/it]ERROR: [youtube] 2arEjz11LEc: Video unavailable
 10%|█         | 362/3599 [36:26<3:23:14,  3.77s/it]ERROR: [youtube] 2b0EzAqILu0: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 10%|█         | 363/3599 [36:27<2:32:12,  2.82s/it]

 10%|█         | 364/3599 [36:32<3:13:38,  3.59s/it]

 10%|█         | 365/3599 [36:38<3:56:34,  4.39s/it]

 10%|█         | 366/3599 [36:48<5:20:33,  5.95s/it]

 10%|█         | 367/3599 [36:53<5:05:58,  5.68s/it]

 10%|█         | 368/3599 [36:58<5:01:10,  5.59s/it]

 10%|█         | 369/3599 [37:03<4:48:08,  5.35s/it]ERROR: [youtube] 2ez8hybFtMY: Video unavailable
 10%|█         | 370/3599 [37:03<3:29:55,  3.90s/it]

 10%|█         | 371/3599 [37:08<3:41:59,  4.13s/it]

 10%|█         | 372/3599 [37:12<3:40:52,  4.11s/it]

 10%|█         | 373/3599 [37:16<3:29:23,  3.89s/it]ERROR: [youtube] 2fVTY-74PHI: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 10%|█         | 374/3599 [37:16<2:35:50,  2.90s/it]

 10%|█         | 375/3599 [37:22<3:24:16,  3.80s/it]

 10%|█         | 376/3599 [37:33<5:11:22,  5.80s/it]ERROR: [youtube] 2fxF1KtbEV0: This video has been removed for violating YouTube's Terms of Service
 10%|█         | 377/3599 [37:33<3:47:44,  4.24s/it]

 11%|█         | 378/3599 [37:38<3:50:47,  4.30s/it]

 11%|█         | 379/3599 [37:46<5:01:19,  5.61s/it]

 11%|█         | 380/3599 [38:00<7:05:37,  7.93s/it]

 11%|█         | 381/3599 [38:09<7:25:03,  8.30s/it]

 11%|█         | 382/3599 [38:15<6:55:47,  7.75s/it]ERROR: [youtube] 2icLwF3WjlE: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 11%|█         | 383/3599 [38:16<5:00:12,  5.60s/it]

 11%|█         | 384/3599 [38:21<4:46:08,  5.34s/it]

 11%|█         | 385/3599 [38:28<5:15:40,  5.89s/it]ERROR: [youtube] 2jFRICR24-Q: Video unavailable
 11%|█         | 386/3599 [38:28<3:49:02,  4.28s/it]

 11%|█         | 387/3599 [40:24<33:38:07, 37.70s/it]

 11%|█         | 388/3599 [40:32<25:41:32, 28.80s/it]

 11%|█         | 389/3599 [40:39<19:52:03, 22.28s/it]

 11%|█         | 390/3599 [40:43<14:51:20, 16.67s/it]

 11%|█         | 391/3599 [40:51<12:44:39, 14.30s/it]

 11%|█         | 392/3599 [41:09<13:35:49, 15.26s/it]

 11%|█         | 393/3599 [41:15<11:09:42, 12.53s/it]

 11%|█         | 394/3599 [41:20<9:00:11, 10.11s/it]

 11%|█         | 395/3599 [41:25<7:45:03,  8.71s/it]

 11%|█         | 396/3599 [41:32<7:12:16,  8.10s/it]

 11%|█         | 397/3599 [41:46<8:45:17,  9.84s/it]

 11%|█         | 398/3599 [41:51<7:37:47,  8.58s/it]

 11%|█         | 399/3599 [41:57<6:52:30,  7.73s/it]

 11%|█         | 400/3599 [42:55<20:13:05, 22.75s/it]

[download]  37.1% of   10.78MiB at  946.40KiB/s ETA 00:07

[download] Got error: 4194272 bytes read, 6274029 more expected
 11%|█         | 401/3599 [43:09<17:58:54, 20.24s/it]

 11%|█         | 402/3599 [43:16<14:19:52, 16.14s/it]

 11%|█         | 403/3599 [43:20<11:09:19, 12.57s/it]

 11%|█         | 404/3599 [43:25<9:12:04, 10.37s/it]

 11%|█▏        | 405/3599 [43:30<7:40:24,  8.65s/it]

 11%|█▏        | 406/3599 [43:34<6:34:51,  7.42s/it]

 11%|█▏        | 407/3599 [43:39<5:53:56,  6.65s/it]

 11%|█▏        | 408/3599 [43:45<5:35:15,  6.30s/it]

 11%|█▏        | 409/3599 [43:49<5:10:35,  5.84s/it]

 11%|█▏        | 410/3599 [44:01<6:47:36,  7.67s/it]

 11%|█▏        | 411/3599 [44:07<6:21:43,  7.18s/it]

 11%|█▏        | 412/3599 [44:14<6:10:58,  6.98s/it]

 11%|█▏        | 413/3599 [44:18<5:23:56,  6.10s/it]

 12%|█▏        | 414/3599 [44:26<5:54:10,  6.67s/it]

 12%|█▏        | 415/3599 [44:34<6:11:14,  7.00s/it]

 12%|█▏        | 416/3599 [44:39<5:45:32,  6.51s/it]

 12%|█▏        | 417/3599 [44:48<6:17:59,  7.13s/it]

 12%|█▏        | 418/3599 [44:52<5:33:11,  6.28s/it]ERROR: [youtube] 2yRlkPqa6rQ: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 12%|█▏        | 419/3599 [44:53<4:02:40,  4.58s/it]

 12%|█▏        | 420/3599 [45:33<13:32:42, 15.34s/it]

 12%|█▏        | 421/3599 [45:38<10:43:40, 12.15s/it]

 12%|█▏        | 422/3599 [45:48<10:11:33, 11.55s/it]

 12%|█▏        | 423/3599 [45:52<8:09:39,  9.25s/it]

 12%|█▏        | 424/3599 [45:59<7:31:04,  8.52s/it]

 12%|█▏        | 425/3599 [46:04<6:43:03,  7.62s/it]

 12%|█▏        | 426/3599 [46:09<6:04:16,  6.89s/it]

 12%|█▏        | 427/3599 [46:19<6:40:38,  7.58s/it]

 12%|█▏        | 428/3599 [46:25<6:24:46,  7.28s/it]

 12%|█▏        | 429/3599 [46:30<5:49:17,  6.61s/it]ERROR: [youtube] 33mT0yZLWGU: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 12%|█▏        | 430/3599 [46:31<4:16:06,  4.85s/it]

 12%|█▏        | 431/3599 [46:35<4:10:01,  4.74s/it]

 12%|█▏        | 432/3599 [46:40<4:07:53,  4.70s/it]

 12%|█▏        | 433/3599 [46:45<4:16:09,  4.85s/it]

 12%|█▏        | 434/3599 [46:50<4:08:53,  4.72s/it]

 12%|█▏        | 435/3599 [46:55<4:22:47,  4.98s/it]

 12%|█▏        | 436/3599 [47:09<6:48:33,  7.75s/it]

 12%|█▏        | 437/3599 [47:14<6:01:11,  6.85s/it]ERROR: [youtube] 39KVJLGAFv4: Video unavailable
 12%|█▏        | 438/3599 [47:15<4:20:33,  4.95s/it]

 12%|█▏        | 439/3599 [47:19<4:04:58,  4.65s/it]

 12%|█▏        | 440/3599 [47:25<4:39:28,  5.31s/it]

 12%|█▏        | 441/3599 [47:29<4:13:38,  4.82s/it]

 12%|█▏        | 442/3599 [47:34<4:18:05,  4.91s/it]

 12%|█▏        | 443/3599 [47:43<5:11:52,  5.93s/it]

 12%|█▏        | 444/3599 [47:47<4:48:22,  5.48s/it]

 12%|█▏        | 445/3599 [47:51<4:31:58,  5.17s/it]

 12%|█▏        | 446/3599 [47:56<4:17:27,  4.90s/it]

 12%|█▏        | 447/3599 [48:01<4:19:04,  4.93s/it]ERROR: [youtube] 3ErID1J8Uec: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 12%|█▏        | 448/3599 [48:01<3:11:36,  3.65s/it]

 12%|█▏        | 449/3599 [48:21<7:23:41,  8.45s/it]

 13%|█▎        | 450/3599 [48:27<6:51:14,  7.84s/it]

 13%|█▎        | 451/3599 [48:33<6:07:39,  7.01s/it]

 13%|█▎        | 452/3599 [48:39<5:53:46,  6.75s/it]

 13%|█▎        | 453/3599 [48:44<5:24:51,  6.20s/it]

 13%|█▎        | 454/3599 [48:49<5:05:11,  5.82s/it]

 13%|█▎        | 455/3599 [48:53<4:50:00,  5.53s/it]

 13%|█▎        | 456/3599 [48:58<4:32:27,  5.20s/it]

 13%|█▎        | 457/3599 [49:04<4:54:46,  5.63s/it]ERROR: [youtube] 3JxWLsgWHu8: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 13%|█▎        | 458/3599 [49:05<3:36:17,  4.13s/it]ERROR: [youtube] 3KDtFq09ivA: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 13%|█▎        | 459/3599 [49:06<2:41:48,  3.09s/it]

 13%|█▎        | 460/3599 [49:11<3:16:37,  3.76s/it]

 13%|█▎        | 461/3599 [49:16<3:40:20,  4.21s/it]

 13%|█▎        | 462/3599 [49:22<3:59:33,  4.58s/it]

 13%|█▎        | 463/3599 [49:27<4:14:49,  4.88s/it]

 13%|█▎        | 464/3599 [49:36<5:07:16,  5.88s/it]

 13%|█▎        | 465/3599 [49:40<4:38:07,  5.32s/it]

 13%|█▎        | 466/3599 [49:59<8:15:43,  9.49s/it]

 13%|█▎        | 467/3599 [50:03<6:46:39,  7.79s/it]

 13%|█▎        | 468/3599 [50:09<6:24:08,  7.36s/it]

 13%|█▎        | 469/3599 [50:20<7:16:47,  8.37s/it]

 13%|█▎        | 470/3599 [50:27<6:54:33,  7.95s/it]

 13%|█▎        | 471/3599 [50:32<6:06:27,  7.03s/it]

 13%|█▎        | 472/3599 [50:37<5:47:54,  6.68s/it]

 13%|█▎        | 473/3599 [50:43<5:24:08,  6.22s/it]

 13%|█▎        | 474/3599 [50:48<5:10:32,  5.96s/it]ERROR: [youtube] 3TQ4eE6O6qQ: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 13%|█▎        | 475/3599 [50:48<3:45:17,  4.33s/it]

 13%|█▎        | 476/3599 [50:53<3:43:18,  4.29s/it]

 13%|█▎        | 477/3599 [51:03<5:20:10,  6.15s/it]

 13%|█▎        | 478/3599 [51:08<4:52:28,  5.62s/it]

 13%|█▎        | 479/3599 [51:16<5:39:07,  6.52s/it]

 13%|█▎        | 480/3599 [51:23<5:44:04,  6.62s/it]

 13%|█▎        | 481/3599 [51:31<6:05:55,  7.04s/it]

 13%|█▎        | 482/3599 [51:37<5:48:49,  6.71s/it]ERROR: [youtube] 3W20yc8TE1s: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 13%|█▎        | 483/3599 [51:37<4:11:53,  4.85s/it]

 13%|█▎        | 484/3599 [51:44<4:34:43,  5.29s/it]

 13%|█▎        | 485/3599 [51:52<5:17:23,  6.12s/it]

 14%|█▎        | 486/3599 [51:57<5:07:56,  5.94s/it]ERROR: [youtube] 3Yiskwwoo-g: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 14%|█▎        | 487/3599 [51:58<3:43:22,  4.31s/it]ERROR: [youtube] 3ZJR4_jRYc8: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 14%|█▎        | 488/3599 [51:58<2:44:46,  3.18s/it]

 14%|█▎        | 489/3599 [52:07<4:16:46,  4.95s/it]

 14%|█▎        | 490/3599 [52:12<4:04:16,  4.71s/it]

 14%|█▎        | 491/3599 [52:16<3:56:13,  4.56s/it]

 14%|█▎        | 492/3599 [52:20<3:50:37,  4.45s/it]ERROR: [youtube] 3a364IwJM3E: Video unavailable
 14%|█▎        | 493/3599 [52:21<2:49:56,  3.28s/it]

 14%|█▎        | 494/3599 [52:27<3:30:48,  4.07s/it]ERROR: [youtube] 3a_afMYgSZE: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 14%|█▍        | 495/3599 [52:27<2:36:20,  3.02s/it]

 14%|█▍        | 496/3599 [52:38<4:43:58,  5.49s/it]

 14%|█▍        | 497/3599 [52:46<5:13:35,  6.07s/it]

 14%|█▍        | 498/3599 [52:58<6:54:10,  8.01s/it]

 14%|█▍        | 499/3599 [53:04<6:11:44,  7.20s/it]

 14%|█▍        | 500/3599 [53:08<5:29:01,  6.37s/it]ERROR: [youtube] 3e8bEKxlr_A: Video unavailable
 14%|█▍        | 501/3599 [53:09<3:58:46,  4.62s/it]

 14%|█▍        | 502/3599 [53:13<3:55:02,  4.55s/it]

 14%|█▍        | 503/3599 [53:18<3:57:26,  4.60s/it]

 14%|█▍        | 504/3599 [53:26<4:50:00,  5.62s/it]ERROR: [youtube] 3ehTwni-7sg: Video unavailable
 14%|█▍        | 505/3599 [53:26<3:31:01,  4.09s/it]ERROR: [youtube] 3ejndVEAcmQ: Video unavailable
 14%|█▍        | 506/3599 [53:27<2:37:06,  3.05s/it]

 14%|█▍        | 507/3599 [53:33<3:29:43,  4.07s/it]

 14%|█▍        | 508/3599 [53:41<4:22:09,  5.09s/it]

 14%|█▍        | 509/3599 [53:45<4:11:52,  4.89s/it]

 14%|█▍        | 510/3599 [53:51<4:27:36,  5.20s/it]

 14%|█▍        | 511/3599 [54:00<5:23:26,  6.28s/it]

 14%|█▍        | 512/3599 [54:05<5:11:50,  6.06s/it]

 14%|█▍        | 513/3599 [54:14<5:46:00,  6.73s/it]

 14%|█▍        | 514/3599 [54:23<6:18:21,  7.36s/it]

 14%|█▍        | 515/3599 [54:28<5:42:45,  6.67s/it]

 14%|█▍        | 516/3599 [54:43<7:50:30,  9.16s/it]

 14%|█▍        | 517/3599 [55:00<10:04:00, 11.76s/it]

 14%|█▍        | 518/3599 [55:05<8:15:52,  9.66s/it]

 14%|█▍        | 519/3599 [55:12<7:31:49,  8.80s/it]

 14%|█▍        | 520/3599 [55:36<11:32:42, 13.50s/it]

 14%|█▍        | 521/3599 [55:43<9:48:34, 11.47s/it]

 15%|█▍        | 522/3599 [55:49<8:22:14,  9.79s/it]

 15%|█▍        | 523/3599 [55:53<6:47:09,  7.94s/it]

 15%|█▍        | 524/3599 [55:59<6:16:52,  7.35s/it]

 15%|█▍        | 525/3599 [56:03<5:38:03,  6.60s/it]

 15%|█▍        | 526/3599 [56:08<5:00:51,  5.87s/it]

 15%|█▍        | 527/3599 [56:12<4:39:47,  5.46s/it]

 15%|█▍        | 528/3599 [56:17<4:26:05,  5.20s/it]

 15%|█▍        | 529/3599 [56:21<4:05:33,  4.80s/it]

 15%|█▍        | 530/3599 [56:25<4:05:02,  4.79s/it]

 15%|█▍        | 531/3599 [56:31<4:17:41,  5.04s/it]ERROR: [youtube] 3sIfumQhQ0Q: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 15%|█▍        | 532/3599 [56:32<3:08:17,  3.68s/it]

 15%|█▍        | 533/3599 [56:36<3:25:05,  4.01s/it]

 15%|█▍        | 534/3599 [56:41<3:27:54,  4.07s/it]

 15%|█▍        | 535/3599 [56:46<3:48:38,  4.48s/it]

 15%|█▍        | 536/3599 [56:50<3:46:12,  4.43s/it]

 15%|█▍        | 537/3599 [56:54<3:41:58,  4.35s/it]

 15%|█▍        | 538/3599 [57:00<4:07:43,  4.86s/it]

 15%|█▍        | 539/3599 [57:18<7:16:33,  8.56s/it]

 15%|█▌        | 540/3599 [57:22<6:09:16,  7.24s/it]

 15%|█▌        | 541/3599 [57:32<6:54:19,  8.13s/it]ERROR: [youtube] 3ww-zwFxrtY: Video unavailable
 15%|█▌        | 542/3599 [57:33<4:57:55,  5.85s/it]

 15%|█▌        | 543/3599 [57:37<4:36:13,  5.42s/it]

 15%|█▌        | 544/3599 [57:41<4:17:46,  5.06s/it]

 15%|█▌        | 545/3599 [57:46<4:14:19,  5.00s/it]

 15%|█▌        | 546/3599 [57:50<3:59:24,  4.70s/it]

 15%|█▌        | 547/3599 [57:54<3:52:16,  4.57s/it]

 15%|█▌        | 548/3599 [57:59<3:47:26,  4.47s/it]

 15%|█▌        | 549/3599 [58:03<3:47:04,  4.47s/it]ERROR: [youtube] 414-QkeLHU4: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 15%|█▌        | 550/3599 [58:04<2:46:29,  3.28s/it]

 15%|█▌        | 551/3599 [58:11<3:50:42,  4.54s/it]

 15%|█▌        | 552/3599 [58:15<3:37:52,  4.29s/it]

 15%|█▌        | 553/3599 [58:19<3:41:54,  4.37s/it]

 15%|█▌        | 554/3599 [58:25<4:05:31,  4.84s/it]

 15%|█▌        | 555/3599 [58:39<6:18:00,  7.45s/it]

 15%|█▌        | 556/3599 [58:43<5:24:09,  6.39s/it]

 15%|█▌        | 557/3599 [58:47<4:45:19,  5.63s/it]

 16%|█▌        | 558/3599 [58:55<5:20:57,  6.33s/it]

 16%|█▌        | 559/3599 [59:02<5:38:36,  6.68s/it]

 16%|█▌        | 560/3599 [59:07<5:15:33,  6.23s/it]

 16%|█▌        | 561/3599 [59:11<4:37:26,  5.48s/it]

 16%|█▌        | 562/3599 [59:15<4:19:34,  5.13s/it]

 16%|█▌        | 563/3599 [59:24<5:14:11,  6.21s/it]

 16%|█▌        | 564/3599 [59:28<4:47:04,  5.68s/it]

 16%|█▌        | 565/3599 [59:33<4:36:39,  5.47s/it]

 16%|█▌        | 566/3599 [59:38<4:18:12,  5.11s/it]ERROR: [youtube] 49c_ZAXGdzM: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 16%|█▌        | 567/3599 [59:38<3:09:37,  3.75s/it]ERROR: [youtube] 4Aks20CZBYE: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 16%|█▌        | 568/3599 [59:39<2:21:21,  2.80s/it]

 16%|█▌        | 569/3599 [59:43<2:49:27,  3.36s/it]

 16%|█▌        | 570/3599 [59:50<3:40:58,  4.38s/it]ERROR: [youtube] 4BYvD3hlpBE: Video unavailable
 16%|█▌        | 571/3599 [59:51<2:42:07,  3.21s/it]ERROR: [youtube] 4BZ0TPmuX_Q: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 16%|█▌        | 572/3599 [59:51<2:02:19,  2.42s/it]ERROR: [youtube] 4BiRz0mkjjo: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 16%|█▌        | 573/3599 [59:52<1:34:48,  1.88s/it]

 16%|█▌        | 574/3599 [59:59<2:56:49,  3.51s/it]

 16%|█▌        | 575/3599 [1:00:04<3:20:38,  3.98s/it]

 16%|█▌        | 576/3599 [1:00:10<3:50:31,  4.58s/it]

 16%|█▌        | 577/3599 [1:00:18<4:33:57,  5.44s/it]ERROR: [youtube] 4GGjTtmHbYI: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 16%|█▌        | 578/3599 [1:00:18<3:19:42,  3.97s/it]

 16%|█▌        | 579/3599 [1:00:29<4:58:30,  5.93s/it]

 16%|█▌        | 580/3599 [1:00:34<4:50:15,  5.77s/it]

 16%|█▌        | 581/3599 [1:00:38<4:24:36,  5.26s/it]

 16%|█▌        | 582/3599 [1:00:44<4:28:46,  5.35s/it]

 16%|█▌        | 583/3599 [1:00:48<4:14:02,  5.05s/it]

 16%|█▌        | 584/3599 [1:00:52<3:58:27,  4.75s/it]ERROR: [youtube] 4Lp91mTRdqo: Video unavailable
 16%|█▋        | 585/3599 [1:00:53<2:54:53,  3.48s/it]ERROR: [youtube] 4MA6WZGgh3Q: Video unavailable
 16%|█▋        | 586/3599 [1:00:53<2:12:50,  2.65s/it]

 16%|█▋        | 587/3599 [1:01:01<3:25:55,  4.10s/it]

 16%|█▋        | 588/3599 [1:01:17<6:29:28,  7.76s/it]

 16%|█▋        | 589/3599 [1:01:26<6:40:32,  7.98s/it]ERROR: [youtube] 4OP4FH04PmY: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 16%|█▋        | 590/3599 [1:01:26<4:49:05,  5.76s/it]

 16%|█▋        | 591/3599 [1:01:31<4:31:22,  5.41s/it]

 16%|█▋        | 592/3599 [1:01:36<4:26:56,  5.33s/it]

 16%|█▋        | 593/3599 [1:01:41<4:16:46,  5.13s/it]

 17%|█▋        | 594/3599 [1:01:46<4:22:55,  5.25s/it]

 17%|█▋        | 595/3599 [1:01:51<4:13:22,  5.06s/it]ERROR: [youtube] 4R07AUf2_x4: Video unavailable
 17%|█▋        | 596/3599 [1:01:51<3:06:15,  3.72s/it]

 17%|█▋        | 597/3599 [1:01:57<3:39:08,  4.38s/it]

 17%|█▋        | 598/3599 [1:02:02<3:36:09,  4.32s/it]

 17%|█▋        | 599/3599 [1:02:06<3:32:18,  4.25s/it]ERROR: [youtube] 4SMqcGnhQKU: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 17%|█▋        | 600/3599 [1:02:06<2:36:28,  3.13s/it]

 17%|█▋        | 601/3599 [1:02:10<2:49:08,  3.39s/it]

 17%|█▋        | 602/3599 [1:02:15<3:05:09,  3.71s/it]

 17%|█▋        | 603/3599 [1:02:23<4:21:30,  5.24s/it]

 17%|█▋        | 604/3599 [1:02:42<7:41:09,  9.24s/it]

 17%|█▋        | 605/3599 [1:02:47<6:43:08,  8.08s/it]

 17%|█▋        | 606/3599 [1:02:54<6:26:03,  7.74s/it]

 17%|█▋        | 607/3599 [1:02:59<5:45:52,  6.94s/it]

 17%|█▋        | 608/3599 [1:03:04<5:07:23,  6.17s/it]

 17%|█▋        | 609/3599 [1:03:07<4:26:43,  5.35s/it]ERROR: [youtube] 4XZ499Rf2nM: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 17%|█▋        | 610/3599 [1:03:08<3:14:34,  3.91s/it]

 17%|█▋        | 611/3599 [1:03:13<3:40:05,  4.42s/it]

 17%|█▋        | 612/3599 [1:03:19<4:01:10,  4.84s/it]

 17%|█▋        | 613/3599 [1:03:25<4:17:59,  5.18s/it]ERROR: [youtube] 4Z-aeSrkqFg: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 17%|█▋        | 614/3599 [1:03:26<3:10:05,  3.82s/it]

 17%|█▋        | 615/3599 [1:03:37<5:07:19,  6.18s/it]

 17%|█▋        | 616/3599 [1:03:43<4:58:04,  6.00s/it]

 17%|█▋        | 617/3599 [1:03:53<5:58:01,  7.20s/it]

 17%|█▋        | 618/3599 [1:04:00<5:57:59,  7.21s/it]

 17%|█▋        | 619/3599 [1:04:05<5:16:14,  6.37s/it]

 17%|█▋        | 620/3599 [1:04:32<10:32:03, 12.73s/it]

 17%|█▋        | 621/3599 [1:04:37<8:36:42, 10.41s/it]

 17%|█▋        | 622/3599 [1:05:05<12:58:25, 15.69s/it]ERROR: [youtube] 4aKcrDljKlc: Video unavailable
 17%|█▋        | 623/3599 [1:05:06<9:13:10, 11.15s/it]

 17%|█▋        | 624/3599 [1:05:12<8:00:43,  9.70s/it]

 17%|█▋        | 625/3599 [1:05:19<7:26:02,  9.00s/it]

 17%|█▋        | 626/3599 [1:05:24<6:18:33,  7.64s/it]ERROR: [youtube] 4d4NOpPqTeo: Video unavailable
 17%|█▋        | 627/3599 [1:05:24<4:32:57,  5.51s/it]

 17%|█▋        | 628/3599 [1:05:29<4:13:35,  5.12s/it]ERROR: [youtube] 4eCIbc4sJVI: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 17%|█▋        | 629/3599 [1:05:29<3:05:11,  3.74s/it]

 18%|█▊        | 630/3599 [1:05:33<3:11:51,  3.88s/it]

 18%|█▊        | 631/3599 [1:05:38<3:29:53,  4.24s/it]

 18%|█▊        | 632/3599 [1:05:43<3:34:12,  4.33s/it]

 18%|█▊        | 633/3599 [1:05:47<3:23:21,  4.11s/it]

 18%|█▊        | 634/3599 [1:05:58<5:13:18,  6.34s/it]

 18%|█▊        | 635/3599 [1:06:07<5:50:51,  7.10s/it]

 18%|█▊        | 636/3599 [1:06:11<5:03:13,  6.14s/it]

 18%|█▊        | 637/3599 [1:06:16<4:48:12,  5.84s/it]

 18%|█▊        | 638/3599 [1:06:21<4:29:15,  5.46s/it]

 18%|█▊        | 639/3599 [1:06:25<4:17:56,  5.23s/it]

 18%|█▊        | 640/3599 [1:06:30<4:13:54,  5.15s/it]

 18%|█▊        | 641/3599 [1:06:38<4:54:44,  5.98s/it]

 18%|█▊        | 642/3599 [1:06:43<4:38:43,  5.66s/it]

 18%|█▊        | 643/3599 [1:06:47<4:15:53,  5.19s/it]

 18%|█▊        | 644/3599 [1:06:52<4:08:54,  5.05s/it]ERROR: unable to download video data: HTTP Error 403: Forbidden
 18%|█▊        | 645/3599 [1:06:53<3:16:48,  4.00s/it]

 18%|█▊        | 646/3599 [1:06:58<3:26:37,  4.20s/it]

 18%|█▊        | 647/3599 [1:07:04<3:57:11,  4.82s/it]

 18%|█▊        | 648/3599 [1:07:10<4:14:20,  5.17s/it]

 18%|█▊        | 649/3599 [1:07:16<4:17:46,  5.24s/it]

 18%|█▊        | 650/3599 [1:07:26<5:24:04,  6.59s/it]

 18%|█▊        | 651/3599 [1:07:32<5:27:40,  6.67s/it]

 18%|█▊        | 652/3599 [1:07:38<5:18:11,  6.48s/it]

 18%|█▊        | 653/3599 [1:07:44<4:58:14,  6.07s/it]

 18%|█▊        | 654/3599 [1:07:51<5:23:24,  6.59s/it]

 18%|█▊        | 655/3599 [1:07:56<4:58:06,  6.08s/it]

 18%|█▊        | 656/3599 [1:08:01<4:37:02,  5.65s/it]

 18%|█▊        | 657/3599 [1:08:08<4:52:11,  5.96s/it]

[download]  10.4% of   19.26MiB at    4.81MiB/s ETA 00:03

[download] Got error: 2097136 bytes read, 7949018 more expected
 18%|█▊        | 658/3599 [1:08:16<5:27:09,  6.67s/it]

 18%|█▊        | 659/3599 [1:08:23<5:36:09,  6.86s/it]

 18%|█▊        | 660/3599 [1:08:31<5:51:53,  7.18s/it]

 18%|█▊        | 661/3599 [1:08:36<5:20:10,  6.54s/it]

 18%|█▊        | 662/3599 [1:08:43<5:29:16,  6.73s/it]

 18%|█▊        | 663/3599 [1:08:49<5:19:11,  6.52s/it]

 18%|█▊        | 664/3599 [1:08:54<4:47:00,  5.87s/it]

 18%|█▊        | 665/3599 [1:09:02<5:22:40,  6.60s/it]

 19%|█▊        | 666/3599 [1:09:07<5:01:54,  6.18s/it]

 19%|█▊        | 667/3599 [1:09:12<4:42:30,  5.78s/it]

 19%|█▊        | 668/3599 [1:09:17<4:30:46,  5.54s/it]ERROR: [youtube] 4rqpRFvGHlk: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 19%|█▊        | 669/3599 [1:09:18<3:17:46,  4.05s/it]ERROR: [youtube] 4s22LBX570A: Video unavailable
 19%|█▊        | 670/3599 [1:09:18<2:27:57,  3.03s/it]ERROR: [youtube] 4sR917jf7TI: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 19%|█▊        | 671/3599 [1:09:19<1:52:25,  2.30s/it]ERROR: [youtube] 4sUECwj3Lu0: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 19%|█▊        | 672/3599 [1:09:20<1:27:30,  1.79s/it]

 19%|█▊        | 673/3599 [1:09:26<2:34:38,  3.17s/it]ERROR: [youtube] 4saOJCEUaLE: Video unavailable
 19%|█▊        | 674/3599 [1:09:26<1:55:50,  2.38s/it]ERROR: [youtube] 4uK2iKEBS50: Video unavailable
 19%|█▉        | 675/3599 [1:09:27<1:29:06,  1.83s/it]

 19%|█▉        | 676/3599 [1:09:30<1:50:40,  2.27s/it]ERROR: [youtube] 4vSCafZpEQQ: This video has been removed for violating YouTube's policy on violent or graphic content
 19%|█▉        | 677/3599 [1:09:31<1:24:35,  1.74s/it]

 19%|█▉        | 678/3599 [1:09:35<1:58:32,  2.43s/it]

 19%|█▉        | 679/3599 [1:09:40<2:45:33,  3.40s/it]ERROR: [youtube] 4wMswSfU_vk: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 19%|█▉        | 680/3599 [1:09:41<2:03:28,  2.54s/it]

 19%|█▉        | 681/3599 [1:09:52<4:00:41,  4.95s/it]

 19%|█▉        | 682/3599 [1:09:56<3:53:05,  4.79s/it]

 19%|█▉        | 683/3599 [1:10:01<3:57:26,  4.89s/it]ERROR: [youtube] 4xU9uKPYQu0: Video unavailable
 19%|█▉        | 684/3599 [1:10:02<2:54:00,  3.58s/it]

 19%|█▉        | 685/3599 [1:10:07<3:22:57,  4.18s/it]

 19%|█▉        | 686/3599 [1:10:12<3:33:24,  4.40s/it]

 19%|█▉        | 687/3599 [1:10:16<3:29:50,  4.32s/it]

 19%|█▉        | 688/3599 [1:10:20<3:24:02,  4.21s/it]ERROR: [youtube] 5-4pJcg-N6s: This video has been removed for violating YouTube's Terms of Service
 19%|█▉        | 689/3599 [1:10:21<2:30:16,  3.10s/it]ERROR: [youtube] 5-77GQ1Ts2k: Video unavailable
 19%|█▉        | 690/3599 [1:10:21<1:52:37,  2.32s/it]

 19%|█▉        | 691/3599 [1:10:26<2:24:07,  2.97s/it]

 19%|█▉        | 692/3599 [1:10:32<3:18:36,  4.10s/it]

 19%|█▉        | 693/3599 [1:10:37<3:30:29,  4.35s/it]ERROR: [youtube] 50De20Tk-f8: Video unavailable
 19%|█▉        | 694/3599 [1:10:38<2:35:02,  3.20s/it]

 19%|█▉        | 695/3599 [1:10:43<3:02:22,  3.77s/it]

 19%|█▉        | 696/3599 [1:10:53<4:34:17,  5.67s/it]

 19%|█▉        | 697/3599 [1:11:00<4:51:54,  6.04s/it]

 19%|█▉        | 698/3599 [1:11:05<4:38:24,  5.76s/it]

 19%|█▉        | 699/3599 [1:11:09<4:09:24,  5.16s/it]ERROR: [youtube] 52aEx-HSrgs: Video unavailable
 19%|█▉        | 700/3599 [1:11:09<3:01:31,  3.76s/it]ERROR: [youtube] 52tdbEqLRsM: Video unavailable
 19%|█▉        | 701/3599 [1:11:10<2:15:09,  2.80s/it]

 20%|█▉        | 702/3599 [1:11:21<4:21:50,  5.42s/it]ERROR: [youtube] 53B4zcaZFBE: Video unavailable
 20%|█▉        | 703/3599 [1:11:22<3:11:29,  3.97s/it]

 20%|█▉        | 704/3599 [1:11:40<6:27:03,  8.02s/it]

 20%|█▉        | 705/3599 [1:11:45<5:49:50,  7.25s/it]

 20%|█▉        | 706/3599 [1:11:50<5:11:46,  6.47s/it]

 20%|█▉        | 707/3599 [1:11:56<5:12:09,  6.48s/it]

 20%|█▉        | 708/3599 [1:12:02<5:03:49,  6.31s/it]ERROR: [youtube] 55LL-6jcpcQ: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 20%|█▉        | 709/3599 [1:12:03<3:41:08,  4.59s/it]

 20%|█▉        | 710/3599 [1:12:13<5:08:51,  6.41s/it]

 20%|█▉        | 711/3599 [1:12:18<4:47:00,  5.96s/it]

 20%|█▉        | 712/3599 [1:12:23<4:36:12,  5.74s/it]

 20%|█▉        | 713/3599 [1:12:33<5:37:13,  7.01s/it]

 20%|█▉        | 714/3599 [1:12:40<5:30:00,  6.86s/it]

 20%|█▉        | 715/3599 [1:12:50<6:21:40,  7.94s/it]ERROR: [youtube] 57EaIi3xB-8: Video unavailable
 20%|█▉        | 716/3599 [1:12:51<4:35:31,  5.73s/it]

 20%|█▉        | 717/3599 [1:12:56<4:26:12,  5.54s/it]ERROR: [youtube] 58Xh72PSbSM: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 20%|█▉        | 718/3599 [1:12:57<3:14:01,  4.04s/it]ERROR: [youtube] 5AXA7_vyjnA: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 20%|█▉        | 719/3599 [1:12:57<2:24:17,  3.01s/it]

 20%|██        | 720/3599 [1:13:01<2:38:32,  3.30s/it]

 20%|██        | 721/3599 [1:13:08<3:34:16,  4.47s/it]

 20%|██        | 722/3599 [1:13:13<3:39:22,  4.57s/it]

 20%|██        | 723/3599 [1:13:19<3:56:37,  4.94s/it]

 20%|██        | 724/3599 [1:13:23<3:45:05,  4.70s/it]ERROR: [youtube] 5Di4ovLsdJM: Video unavailable
 20%|██        | 725/3599 [1:13:24<2:46:11,  3.47s/it]

 20%|██        | 726/3599 [1:13:30<3:24:53,  4.28s/it]

 20%|██        | 727/3599 [1:13:37<4:00:29,  5.02s/it]

 20%|██        | 728/3599 [1:13:43<4:12:38,  5.28s/it]

 20%|██        | 729/3599 [1:13:49<4:26:48,  5.58s/it]

 20%|██        | 730/3599 [1:13:54<4:16:10,  5.36s/it]

 20%|██        | 731/3599 [1:14:25<10:36:03, 13.31s/it]

 20%|██        | 732/3599 [1:14:34<9:25:09, 11.83s/it]

 20%|██        | 733/3599 [1:14:38<7:31:19,  9.45s/it]

 20%|██        | 734/3599 [1:14:49<7:53:01,  9.91s/it]

 20%|██        | 735/3599 [1:15:50<20:08:13, 25.31s/it]

 20%|██        | 736/3599 [1:15:56<15:34:44, 19.59s/it]

 20%|██        | 737/3599 [1:16:04<12:44:45, 16.03s/it]

 21%|██        | 738/3599 [1:16:08<9:55:10, 12.48s/it]

 21%|██        | 739/3599 [1:16:14<8:13:17, 10.35s/it]ERROR: [youtube] 5M5TrT9Elpc: Video unavailable
 21%|██        | 740/3599 [1:16:14<5:53:30,  7.42s/it]

 21%|██        | 741/3599 [1:16:25<6:41:02,  8.42s/it]

 21%|██        | 742/3599 [1:16:33<6:43:20,  8.47s/it]

 21%|██        | 743/3599 [1:16:55<9:49:49, 12.39s/it]ERROR: [youtube] 5OX7vWxi2RI: Video unavailable
 21%|██        | 744/3599 [1:16:56<7:00:14,  8.83s/it]

 21%|██        | 745/3599 [1:17:00<6:02:07,  7.61s/it]

 21%|██        | 746/3599 [1:17:04<5:10:20,  6.53s/it]

 21%|██        | 747/3599 [1:17:09<4:37:25,  5.84s/it]

 21%|██        | 748/3599 [1:17:13<4:13:10,  5.33s/it]

 21%|██        | 749/3599 [1:17:22<5:10:52,  6.54s/it]

 21%|██        | 750/3599 [1:17:26<4:35:01,  5.79s/it]

 21%|██        | 751/3599 [1:17:35<5:18:51,  6.72s/it]

 21%|██        | 752/3599 [1:17:38<4:31:41,  5.73s/it]

 21%|██        | 753/3599 [1:17:43<4:23:02,  5.55s/it]

 21%|██        | 754/3599 [1:17:48<4:04:49,  5.16s/it]

 21%|██        | 755/3599 [1:18:01<6:03:05,  7.66s/it]

 21%|██        | 756/3599 [1:18:09<6:07:02,  7.75s/it]

 21%|██        | 757/3599 [1:18:15<5:32:31,  7.02s/it]

 21%|██        | 758/3599 [1:18:22<5:37:50,  7.13s/it]ERROR: [youtube] 5XnjpgURugA: Video unavailable
 21%|██        | 759/3599 [1:18:22<4:04:03,  5.16s/it]

 21%|██        | 760/3599 [1:18:43<7:37:27,  9.67s/it]ERROR: [youtube] 5ZQ_NXEwgmE: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 21%|██        | 761/3599 [1:18:43<5:28:04,  6.94s/it]ERROR: [youtube] 5ZRdc9DgtBA: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 21%|██        | 762/3599 [1:18:44<3:57:13,  5.02s/it]

 21%|██        | 763/3599 [1:18:50<4:09:28,  5.28s/it]

 21%|██        | 764/3599 [1:18:56<4:17:54,  5.46s/it]

 21%|██▏       | 765/3599 [1:19:00<4:06:46,  5.22s/it]

 21%|██▏       | 766/3599 [1:19:04<3:51:09,  4.90s/it]

 21%|██▏       | 767/3599 [1:19:09<3:45:52,  4.79s/it]ERROR: [youtube] 5_XNklNJ0H4: Video unavailable
 21%|██▏       | 768/3599 [1:19:09<2:44:45,  3.49s/it]

 21%|██▏       | 769/3599 [1:19:15<3:20:04,  4.24s/it]

 21%|██▏       | 770/3599 [1:19:23<4:15:13,  5.41s/it]

 21%|██▏       | 771/3599 [1:19:28<3:58:27,  5.06s/it]ERROR: [youtube] 5a_qYZlgIS0: Video unavailable
 21%|██▏       | 772/3599 [1:19:28<2:54:20,  3.70s/it]

 21%|██▏       | 773/3599 [1:19:36<3:56:21,  5.02s/it]ERROR: [youtube] 5b04Vp0loTM: Video unavailable. This video is no longer available due to a copyright claim by スコちゃんズ ちゃんねる
 22%|██▏       | 774/3599 [1:19:37<2:53:00,  3.67s/it]

 22%|██▏       | 775/3599 [1:19:42<3:13:36,  4.11s/it]ERROR: [youtube] 5bCDUoviBys: Video unavailable
 22%|██▏       | 776/3599 [1:19:43<2:26:53,  3.12s/it]

 22%|██▏       | 777/3599 [1:19:48<2:58:13,  3.79s/it]

 22%|██▏       | 778/3599 [1:19:55<3:38:34,  4.65s/it]

 22%|██▏       | 779/3599 [1:19:59<3:27:57,  4.42s/it]ERROR: [youtube] 5cWOyow_Drs: Video unavailable
 22%|██▏       | 780/3599 [1:19:59<2:32:58,  3.26s/it]

 22%|██▏       | 781/3599 [1:20:04<2:59:35,  3.82s/it]

 22%|██▏       | 782/3599 [1:20:18<5:18:42,  6.79s/it]

 22%|██▏       | 783/3599 [1:20:24<5:06:06,  6.52s/it]

 22%|██▏       | 784/3599 [1:20:29<4:45:15,  6.08s/it]

 22%|██▏       | 785/3599 [1:20:33<4:19:46,  5.54s/it]ERROR: [youtube] 5dk12GG2pA0: Video unavailable. This video is no longer available due to a copyright claim by Kiichan Ch. 狐井アキラ
 22%|██▏       | 786/3599 [1:20:34<3:10:19,  4.06s/it]

 22%|██▏       | 787/3599 [1:20:42<4:13:38,  5.41s/it]ERROR: [youtube] 5fRe5Fmn09o: Video unavailable
 22%|██▏       | 788/3599 [1:20:43<3:04:38,  3.94s/it]

 22%|██▏       | 789/3599 [1:20:49<3:33:37,  4.56s/it]

 22%|██▏       | 790/3599 [1:20:54<3:43:03,  4.76s/it]

 22%|██▏       | 791/3599 [1:21:00<3:53:10,  4.98s/it]

 22%|██▏       | 792/3599 [1:21:13<5:45:22,  7.38s/it]ERROR: [youtube] 5imWGr9yI9k: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 22%|██▏       | 793/3599 [1:21:13<4:09:27,  5.33s/it]

 22%|██▏       | 794/3599 [1:21:18<4:06:24,  5.27s/it]

 22%|██▏       | 795/3599 [1:21:24<4:05:26,  5.25s/it]ERROR: [youtube] 5kBiaQEDdW8: Video unavailable
 22%|██▏       | 796/3599 [1:21:24<2:59:20,  3.84s/it]

 22%|██▏       | 797/3599 [1:21:34<4:20:49,  5.59s/it]

 22%|██▏       | 798/3599 [1:21:39<4:08:38,  5.33s/it]

 22%|██▏       | 799/3599 [1:21:50<5:31:59,  7.11s/it]

 22%|██▏       | 800/3599 [1:21:56<5:13:36,  6.72s/it]

 22%|██▏       | 801/3599 [1:22:25<10:34:13, 13.60s/it]

 22%|██▏       | 802/3599 [1:22:31<8:43:26, 11.23s/it] ERROR: [youtube] 5qcEONb4qBg: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 22%|██▏       | 803/3599 [1:22:32<6:13:57,  8.02s/it]

 22%|██▏       | 804/3599 [1:22:39<6:02:39,  7.79s/it]

 22%|██▏       | 805/3599 [1:22:44<5:30:42,  7.10s/it]

 22%|██▏       | 806/3599 [1:22:53<5:48:54,  7.50s/it]

 22%|██▏       | 807/3599 [1:22:57<5:06:48,  6.59s/it]

 22%|██▏       | 808/3599 [1:23:04<5:04:55,  6.56s/it]

 22%|██▏       | 809/3599 [1:23:08<4:38:48,  6.00s/it]

 23%|██▎       | 810/3599 [1:23:14<4:37:22,  5.97s/it]

 23%|██▎       | 811/3599 [1:23:19<4:27:13,  5.75s/it]

 23%|██▎       | 812/3599 [1:23:37<7:13:38,  9.34s/it]

 23%|██▎       | 813/3599 [1:23:42<6:12:02,  8.01s/it]

 23%|██▎       | 814/3599 [1:23:46<5:19:26,  6.88s/it]

 23%|██▎       | 815/3599 [1:24:18<11:08:53, 14.42s/it]

 23%|██▎       | 816/3599 [1:24:25<9:15:53, 11.98s/it]

 23%|██▎       | 817/3599 [1:24:32<8:04:42, 10.45s/it]

 23%|██▎       | 818/3599 [1:24:37<6:57:51,  9.02s/it]

 23%|██▎       | 819/3599 [1:24:42<5:54:18,  7.65s/it]

 23%|██▎       | 820/3599 [1:24:46<5:12:06,  6.74s/it]ERROR: [youtube] 5yb4uWiqzDU: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 23%|██▎       | 821/3599 [1:24:47<3:46:29,  4.89s/it]

 23%|██▎       | 822/3599 [1:24:53<4:00:31,  5.20s/it]

 23%|██▎       | 823/3599 [1:24:57<3:41:53,  4.80s/it]

 23%|██▎       | 824/3599 [1:25:00<3:28:11,  4.50s/it]

 23%|██▎       | 825/3599 [1:25:06<3:40:53,  4.78s/it]

 23%|██▎       | 826/3599 [1:25:14<4:26:38,  5.77s/it]ERROR: [youtube] 62Ayzboyt9I: Video unavailable
 23%|██▎       | 827/3599 [1:25:14<3:14:23,  4.21s/it]

 23%|██▎       | 828/3599 [1:25:21<3:47:21,  4.92s/it]ERROR: [youtube] 63GTDlmz1Ag: Video unavailable
 23%|██▎       | 829/3599 [1:25:22<2:46:21,  3.60s/it]

 23%|██▎       | 830/3599 [1:25:28<3:28:58,  4.53s/it]

 23%|██▎       | 831/3599 [1:25:32<3:19:59,  4.33s/it]ERROR: [youtube] 64T2MnencUY: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 23%|██▎       | 832/3599 [1:25:33<2:27:32,  3.20s/it]

 23%|██▎       | 833/3599 [1:25:39<3:10:13,  4.13s/it]

 23%|██▎       | 834/3599 [1:25:53<5:23:00,  7.01s/it]

 23%|██▎       | 835/3599 [1:25:59<5:14:18,  6.82s/it]

 23%|██▎       | 836/3599 [1:26:04<4:53:31,  6.37s/it]

 23%|██▎       | 837/3599 [1:26:10<4:39:10,  6.06s/it]

 23%|██▎       | 838/3599 [1:26:16<4:40:11,  6.09s/it]

 23%|██▎       | 839/3599 [1:26:19<4:04:18,  5.31s/it]ERROR: [youtube] 66ou6nJPdrk: Video unavailable
 23%|██▎       | 840/3599 [1:26:20<2:58:05,  3.87s/it]ERROR: [youtube] 67RwEkU_CZA: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 23%|██▎       | 841/3599 [1:26:20<2:11:36,  2.86s/it]

 23%|██▎       | 842/3599 [1:26:24<2:27:19,  3.21s/it]

 23%|██▎       | 843/3599 [1:26:30<2:56:46,  3.85s/it]ERROR: [youtube] 68Tl4xC5zMs: Video unavailable
 23%|██▎       | 844/3599 [1:26:30<2:10:49,  2.85s/it]

 23%|██▎       | 845/3599 [1:26:36<2:50:52,  3.72s/it]ERROR: [youtube] 6AVUNt_Id6I: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 24%|██▎       | 846/3599 [1:26:37<2:06:32,  2.76s/it]ERROR: [youtube] 6AwwhtpYn6A: Video unavailable
 24%|██▎       | 847/3599 [1:26:37<1:36:14,  2.10s/it]ERROR: [youtube] 6Caft-Vel14: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 24%|██▎       | 848/3599 [1:26:38<1:14:45,  1.63s/it]

 24%|██▎       | 849/3599 [1:26:42<1:56:41,  2.55s/it]

 24%|██▎       | 850/3599 [1:26:51<3:14:02,  4.24s/it]

 24%|██▎       | 851/3599 [1:26:58<3:53:39,  5.10s/it]

 24%|██▎       | 852/3599 [1:27:02<3:42:02,  4.85s/it]

 24%|██▎       | 853/3599 [1:27:25<7:55:21, 10.39s/it]

 24%|██▎       | 854/3599 [1:27:30<6:35:13,  8.64s/it]

 24%|██▍       | 855/3599 [1:27:40<6:52:29,  9.02s/it]

 24%|██▍       | 856/3599 [1:27:50<7:06:22,  9.33s/it]

 24%|██▍       | 857/3599 [1:28:05<8:26:16, 11.08s/it]

 24%|██▍       | 858/3599 [1:28:12<7:26:37,  9.78s/it]ERROR: [youtube] 6HLyx81_wcA: Video unavailable
 24%|██▍       | 859/3599 [1:28:12<5:19:19,  6.99s/it]

 24%|██▍       | 860/3599 [1:28:16<4:38:58,  6.11s/it]

 24%|██▍       | 861/3599 [1:28:22<4:27:49,  5.87s/it]

 24%|██▍       | 862/3599 [1:28:26<4:10:24,  5.49s/it]

 24%|██▍       | 863/3599 [1:28:30<3:41:26,  4.86s/it]

 24%|██▍       | 864/3599 [1:28:34<3:31:02,  4.63s/it]ERROR: [youtube] 6LSkifxum4I: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 24%|██▍       | 865/3599 [1:28:34<2:38:22,  3.48s/it]

 24%|██▍       | 866/3599 [1:28:44<4:01:41,  5.31s/it]

 24%|██▍       | 867/3599 [1:28:55<5:23:21,  7.10s/it]

 24%|██▍       | 868/3599 [1:29:00<4:44:59,  6.26s/it]

 24%|██▍       | 869/3599 [1:29:04<4:16:52,  5.65s/it]

 24%|██▍       | 870/3599 [1:29:12<4:45:52,  6.29s/it]

 24%|██▍       | 871/3599 [1:29:22<5:45:46,  7.61s/it]

 24%|██▍       | 872/3599 [1:29:28<5:16:25,  6.96s/it]

 24%|██▍       | 873/3599 [1:29:33<4:51:36,  6.42s/it]

 24%|██▍       | 874/3599 [1:29:40<5:06:47,  6.75s/it]

 24%|██▍       | 875/3599 [1:29:45<4:42:04,  6.21s/it]

 24%|██▍       | 876/3599 [1:29:49<4:12:47,  5.57s/it]

 24%|██▍       | 877/3599 [1:29:55<4:10:23,  5.52s/it]

 24%|██▍       | 878/3599 [1:30:02<4:28:54,  5.93s/it]

 24%|██▍       | 879/3599 [1:30:06<4:05:06,  5.41s/it]

 24%|██▍       | 880/3599 [1:30:10<3:52:41,  5.13s/it]

 24%|██▍       | 881/3599 [1:30:15<3:41:20,  4.89s/it]

 25%|██▍       | 882/3599 [1:30:19<3:28:53,  4.61s/it]

 25%|██▍       | 883/3599 [1:30:23<3:29:37,  4.63s/it]

 25%|██▍       | 884/3599 [1:30:31<4:10:29,  5.54s/it]

 25%|██▍       | 885/3599 [1:30:46<6:21:11,  8.43s/it]

ERROR: unable to download video data: HTTP Error 403: Forbidden
 25%|██▍       | 886/3599 [1:31:07<9:13:11, 12.23s/it]

 25%|██▍       | 887/3599 [1:31:12<7:25:53,  9.86s/it]

 25%|██▍       | 888/3599 [1:31:18<6:34:21,  8.73s/it]ERROR: [youtube] 6Vg45tqxA-A: Video unavailable
 25%|██▍       | 889/3599 [1:31:18<4:42:33,  6.26s/it]

 25%|██▍       | 890/3599 [1:31:23<4:17:58,  5.71s/it]

 25%|██▍       | 891/3599 [1:31:29<4:21:40,  5.80s/it]

 25%|██▍       | 892/3599 [1:31:34<4:11:01,  5.56s/it]ERROR: [youtube] 6YJ6rbxSPfs: Video unavailable
 25%|██▍       | 893/3599 [1:31:34<3:03:22,  4.07s/it]ERROR: [youtube] 6Z7IOl3vBqc: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 25%|██▍       | 894/3599 [1:31:35<2:15:06,  3.00s/it]

 25%|██▍       | 895/3599 [1:31:40<2:49:57,  3.77s/it]

 25%|██▍       | 896/3599 [1:31:44<2:55:49,  3.90s/it]

 25%|██▍       | 897/3599 [1:31:49<3:06:55,  4.15s/it]

 25%|██▍       | 898/3599 [1:31:53<3:05:05,  4.11s/it]

 25%|██▍       | 899/3599 [1:31:58<3:10:56,  4.24s/it]

 25%|██▌       | 900/3599 [1:32:05<3:45:52,  5.02s/it]

 25%|██▌       | 901/3599 [1:32:09<3:39:25,  4.88s/it]

 25%|██▌       | 902/3599 [1:32:18<4:35:26,  6.13s/it]

 25%|██▌       | 903/3599 [1:32:27<5:12:22,  6.95s/it]

 25%|██▌       | 904/3599 [1:32:32<4:45:47,  6.36s/it]

 25%|██▌       | 905/3599 [1:32:37<4:26:00,  5.92s/it]

 25%|██▌       | 906/3599 [1:32:46<5:08:12,  6.87s/it]

 25%|██▌       | 907/3599 [1:32:54<5:26:46,  7.28s/it]

 25%|██▌       | 908/3599 [1:33:00<5:09:34,  6.90s/it]

 25%|██▌       | 909/3599 [1:33:13<6:22:08,  8.52s/it]ERROR: [youtube] 6izvKZ1XEtA: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 25%|██▌       | 910/3599 [1:33:13<4:35:21,  6.14s/it]

 25%|██▌       | 911/3599 [1:33:26<6:06:13,  8.17s/it]

 25%|██▌       | 912/3599 [1:33:35<6:16:24,  8.41s/it]

 25%|██▌       | 913/3599 [1:33:39<5:11:05,  6.95s/it]

 25%|██▌       | 914/3599 [1:33:44<4:44:17,  6.35s/it]

 25%|██▌       | 915/3599 [1:33:47<4:09:13,  5.57s/it]

 25%|██▌       | 916/3599 [1:33:54<4:20:31,  5.83s/it]ERROR: [youtube] 6lKAlnNphIs: Video unavailable
 25%|██▌       | 917/3599 [1:33:54<3:09:19,  4.24s/it]ERROR: [youtube] 6oCWv-0r9fQ: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 26%|██▌       | 918/3599 [1:33:55<2:20:06,  3.14s/it]

 26%|██▌       | 919/3599 [1:34:00<2:44:29,  3.68s/it]

 26%|██▌       | 920/3599 [1:34:07<3:27:33,  4.65s/it]

 26%|██▌       | 921/3599 [1:34:20<5:17:40,  7.12s/it]ERROR: [youtube] 6qKK-P5URt0: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 26%|██▌       | 922/3599 [1:34:20<3:49:51,  5.15s/it]

 26%|██▌       | 923/3599 [1:34:25<3:47:15,  5.10s/it]

 26%|██▌       | 924/3599 [1:34:30<3:42:47,  5.00s/it]

 26%|██▌       | 925/3599 [1:34:46<6:05:24,  8.20s/it]

 26%|██▌       | 926/3599 [1:35:21<12:06:55, 16.32s/it]

 26%|██▌       | 927/3599 [1:35:30<10:26:40, 14.07s/it]ERROR: [youtube] 6rzP7h7fSwE: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 26%|██▌       | 928/3599 [1:35:30<7:26:26, 10.03s/it]

 26%|██▌       | 929/3599 [1:35:36<6:32:00,  8.81s/it]

 26%|██▌       | 930/3599 [1:35:45<6:27:04,  8.70s/it]

 26%|██▌       | 931/3599 [1:35:51<5:48:57,  7.85s/it]

 26%|██▌       | 932/3599 [1:35:55<5:00:56,  6.77s/it]

 26%|██▌       | 933/3599 [1:35:59<4:21:44,  5.89s/it]

 26%|██▌       | 934/3599 [1:36:06<4:37:10,  6.24s/it]

 26%|██▌       | 935/3599 [1:36:10<4:17:08,  5.79s/it]

 26%|██▌       | 936/3599 [1:36:18<4:38:54,  6.28s/it]

 26%|██▌       | 937/3599 [1:36:21<4:02:33,  5.47s/it]ERROR: [youtube] 6v9ozzJKLbw: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 26%|██▌       | 938/3599 [1:36:22<2:57:35,  4.00s/it]

 26%|██▌       | 939/3599 [1:36:26<3:00:55,  4.08s/it]

 26%|██▌       | 940/3599 [1:36:32<3:29:04,  4.72s/it]

 26%|██▌       | 941/3599 [1:36:38<3:43:21,  5.04s/it]

 26%|██▌       | 942/3599 [1:36:44<3:53:06,  5.26s/it]

 26%|██▌       | 943/3599 [1:36:50<4:07:13,  5.58s/it]

 26%|██▌       | 944/3599 [1:36:54<3:39:14,  4.95s/it]

 26%|██▋       | 945/3599 [1:36:58<3:30:31,  4.76s/it]

 26%|██▋       | 946/3599 [1:37:07<4:27:15,  6.04s/it]

 26%|██▋       | 947/3599 [1:37:11<3:57:10,  5.37s/it]

 26%|██▋       | 948/3599 [1:37:17<4:11:39,  5.70s/it]

 26%|██▋       | 949/3599 [1:37:26<4:43:10,  6.41s/it]

 26%|██▋       | 950/3599 [1:37:42<6:50:07,  9.29s/it]

 26%|██▋       | 951/3599 [1:37:50<6:40:43,  9.08s/it]

 26%|██▋       | 952/3599 [1:37:58<6:23:55,  8.70s/it]

 26%|██▋       | 953/3599 [1:38:04<5:52:17,  7.99s/it]

 27%|██▋       | 954/3599 [1:38:09<5:03:07,  6.88s/it]

 27%|██▋       | 955/3599 [1:38:12<4:24:18,  6.00s/it]

 27%|██▋       | 956/3599 [1:38:17<4:07:35,  5.62s/it]

 27%|██▋       | 957/3599 [1:38:22<3:56:35,  5.37s/it]

 27%|██▋       | 958/3599 [1:38:43<7:25:54, 10.13s/it]

 27%|██▋       | 959/3599 [1:38:47<6:06:26,  8.33s/it]

 27%|██▋       | 960/3599 [1:38:52<5:12:33,  7.11s/it]

 27%|██▋       | 961/3599 [1:38:55<4:27:32,  6.09s/it]

 27%|██▋       | 962/3599 [1:39:00<4:02:12,  5.51s/it]

 27%|██▋       | 963/3599 [1:39:05<3:55:57,  5.37s/it]

 27%|██▋       | 964/3599 [1:39:10<4:03:01,  5.53s/it]ERROR: [youtube] 76D8aAKnOOg: Video unavailable
 27%|██▋       | 965/3599 [1:39:11<2:57:10,  4.04s/it]ERROR: [youtube] 77T_0D30zik: Video unavailable
 27%|██▋       | 966/3599 [1:39:12<2:11:30,  3.00s/it]

 27%|██▋       | 967/3599 [1:39:15<2:21:21,  3.22s/it]

 27%|██▋       | 968/3599 [1:39:28<4:30:34,  6.17s/it]

 27%|██▋       | 969/3599 [1:39:35<4:40:13,  6.39s/it]

 27%|██▋       | 970/3599 [1:39:45<5:23:26,  7.38s/it]

 27%|██▋       | 971/3599 [1:39:55<6:03:08,  8.29s/it]

 27%|██▋       | 972/3599 [1:40:00<5:19:38,  7.30s/it]

 27%|██▋       | 973/3599 [1:40:08<5:28:42,  7.51s/it]

 27%|██▋       | 974/3599 [1:40:12<4:43:06,  6.47s/it]ERROR: [youtube] 7Ay-gVQ4oSc: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 27%|██▋       | 975/3599 [1:40:13<3:25:35,  4.70s/it]

 27%|██▋       | 976/3599 [1:40:19<3:37:03,  4.96s/it]

 27%|██▋       | 977/3599 [1:40:24<3:44:13,  5.13s/it]

 27%|██▋       | 978/3599 [1:40:30<3:55:05,  5.38s/it]

 27%|██▋       | 979/3599 [1:40:33<3:27:40,  4.76s/it]

 27%|██▋       | 980/3599 [1:40:37<3:19:10,  4.56s/it]

 27%|██▋       | 981/3599 [1:40:44<3:45:44,  5.17s/it]

 27%|██▋       | 982/3599 [1:40:48<3:33:03,  4.88s/it]ERROR: [youtube] 7FAvEQvQirU: Video unavailable
 27%|██▋       | 983/3599 [1:40:49<2:36:20,  3.59s/it]

 27%|██▋       | 984/3599 [1:40:57<3:38:07,  5.00s/it]

 27%|██▋       | 985/3599 [1:41:03<3:50:56,  5.30s/it]ERROR: [youtube] 7Fj1cEaz9lE: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 27%|██▋       | 986/3599 [1:41:04<2:49:15,  3.89s/it]

 27%|██▋       | 987/3599 [1:41:10<3:25:25,  4.72s/it]

 27%|██▋       | 988/3599 [1:41:16<3:39:17,  5.04s/it]

 27%|██▋       | 989/3599 [1:41:21<3:37:27,  5.00s/it]

 28%|██▊       | 990/3599 [1:41:30<4:22:53,  6.05s/it]

 28%|██▊       | 991/3599 [1:41:37<4:46:50,  6.60s/it]

 28%|██▊       | 992/3599 [1:41:42<4:13:45,  5.84s/it]ERROR: [youtube] 7NC2M3GDDy8: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 28%|██▊       | 993/3599 [1:41:42<3:04:57,  4.26s/it]

 28%|██▊       | 994/3599 [1:41:49<3:39:00,  5.04s/it]

 28%|██▊       | 995/3599 [1:41:53<3:23:38,  4.69s/it]

 28%|██▊       | 996/3599 [1:41:58<3:25:41,  4.74s/it]

 28%|██▊       | 997/3599 [1:42:02<3:13:55,  4.47s/it]

 28%|██▊       | 998/3599 [1:42:06<3:19:37,  4.60s/it]

 28%|██▊       | 999/3599 [1:42:10<3:09:40,  4.38s/it]

 28%|██▊       | 1000/3599 [1:42:15<3:19:59,  4.62s/it]

 28%|██▊       | 1001/3599 [1:42:22<3:43:16,  5.16s/it]

 28%|██▊       | 1002/3599 [1:42:26<3:35:21,  4.98s/it]

 28%|██▊       | 1003/3599 [1:42:33<3:53:41,  5.40s/it]ERROR: [youtube] 7XCaCkHgkZM: Video unavailable
 28%|██▊       | 1004/3599 [1:42:33<2:50:05,  3.93s/it]

 28%|██▊       | 1005/3599 [1:42:38<3:04:07,  4.26s/it]ERROR: [youtube] 7YdxSK10d8I: Video unavailable
 28%|██▊       | 1006/3599 [1:42:39<2:18:21,  3.20s/it]

 28%|██▊       | 1007/3599 [1:42:43<2:30:52,  3.49s/it]

 28%|██▊       | 1008/3599 [1:42:50<3:09:23,  4.39s/it]ERROR: [youtube] 7Zg47JZd02Y: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 28%|██▊       | 1009/3599 [1:42:50<2:20:30,  3.26s/it]

 28%|██▊       | 1010/3599 [1:42:55<2:37:48,  3.66s/it]ERROR: [youtube] 7aZIWeI5Dr8: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 28%|██▊       | 1011/3599 [1:42:56<1:57:20,  2.72s/it]

 28%|██▊       | 1012/3599 [1:43:05<3:20:03,  4.64s/it]

 28%|██▊       | 1013/3599 [1:43:10<3:31:17,  4.90s/it]

 28%|██▊       | 1014/3599 [1:43:15<3:25:02,  4.76s/it]ERROR: [youtube] 7ckYfXIvrPk: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 28%|██▊       | 1015/3599 [1:43:15<2:30:02,  3.48s/it]

 28%|██▊       | 1016/3599 [1:43:21<2:58:40,  4.15s/it]

 28%|██▊       | 1017/3599 [1:43:26<3:06:01,  4.32s/it]

 28%|██▊       | 1018/3599 [1:43:30<3:06:05,  4.33s/it]

 28%|██▊       | 1019/3599 [1:43:41<4:30:23,  6.29s/it]

 28%|██▊       | 1020/3599 [1:43:45<4:10:52,  5.84s/it]ERROR: [youtube] 7fKdwIgs990: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 28%|██▊       | 1021/3599 [1:43:46<3:02:45,  4.25s/it]

 28%|██▊       | 1022/3599 [1:43:50<2:53:00,  4.03s/it]

 28%|██▊       | 1023/3599 [1:44:13<6:56:46,  9.71s/it]

 28%|██▊       | 1024/3599 [1:44:19<6:17:48,  8.80s/it]ERROR: [youtube] 7gF6va2iEu0: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 28%|██▊       | 1025/3599 [1:44:20<4:31:24,  6.33s/it]

 29%|██▊       | 1026/3599 [1:44:24<4:00:58,  5.62s/it]

 29%|██▊       | 1027/3599 [1:44:28<3:46:48,  5.29s/it]

 29%|██▊       | 1028/3599 [1:44:34<3:47:08,  5.30s/it]

 29%|██▊       | 1029/3599 [1:44:40<3:57:20,  5.54s/it]

 29%|██▊       | 1030/3599 [1:44:48<4:32:12,  6.36s/it]

 29%|██▊       | 1031/3599 [1:44:53<4:11:29,  5.88s/it]ERROR: [youtube] 7kj2JBMir30: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 29%|██▊       | 1032/3599 [1:44:53<3:04:53,  4.32s/it]

 29%|██▊       | 1033/3599 [1:45:01<3:50:42,  5.39s/it]

 29%|██▊       | 1034/3599 [1:45:08<4:13:26,  5.93s/it]

 29%|██▉       | 1035/3599 [1:45:13<4:00:59,  5.64s/it]

 29%|██▉       | 1036/3599 [1:45:20<4:19:10,  6.07s/it]

 29%|██▉       | 1037/3599 [1:45:24<3:51:36,  5.42s/it]

 29%|██▉       | 1038/3599 [1:45:41<6:12:39,  8.73s/it]

 29%|██▉       | 1039/3599 [1:45:46<5:22:00,  7.55s/it]

 29%|██▉       | 1040/3599 [1:45:51<4:51:24,  6.83s/it]

 29%|██▉       | 1041/3599 [1:45:56<4:36:23,  6.48s/it]

 29%|██▉       | 1042/3599 [1:46:02<4:26:21,  6.25s/it]

 29%|██▉       | 1043/3599 [1:46:08<4:17:54,  6.05s/it]

 29%|██▉       | 1044/3599 [1:46:15<4:29:16,  6.32s/it]

 29%|██▉       | 1045/3599 [1:46:19<4:00:00,  5.64s/it]

 29%|██▉       | 1046/3599 [1:46:23<3:41:11,  5.20s/it]

 29%|██▉       | 1047/3599 [1:46:31<4:17:37,  6.06s/it]

 29%|██▉       | 1048/3599 [1:46:36<4:02:58,  5.71s/it]

 29%|██▉       | 1049/3599 [1:46:40<3:45:00,  5.29s/it]ERROR: [youtube] 7sQqOFuknxM: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 29%|██▉       | 1050/3599 [1:46:41<2:44:37,  3.88s/it]

 29%|██▉       | 1051/3599 [1:46:46<3:01:41,  4.28s/it]

 29%|██▉       | 1052/3599 [1:46:57<4:26:00,  6.27s/it]ERROR: [youtube] 7vZ1DuLDx54: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 29%|██▉       | 1053/3599 [1:46:57<3:12:52,  4.55s/it]

 29%|██▉       | 1054/3599 [1:47:14<5:44:55,  8.13s/it]

 29%|██▉       | 1055/3599 [1:47:21<5:35:05,  7.90s/it]ERROR: [youtube] 7xP1I0s9c6g: Video unavailable
 29%|██▉       | 1056/3599 [1:47:22<4:00:46,  5.68s/it]

 29%|██▉       | 1057/3599 [1:47:26<3:48:02,  5.38s/it]

 29%|██▉       | 1058/3599 [1:47:31<3:33:59,  5.05s/it]

 29%|██▉       | 1059/3599 [1:47:36<3:37:18,  5.13s/it]

 29%|██▉       | 1060/3599 [1:47:43<3:53:50,  5.53s/it]

 29%|██▉       | 1061/3599 [1:47:48<3:52:55,  5.51s/it]

 30%|██▉       | 1062/3599 [1:47:53<3:46:40,  5.36s/it]

 30%|██▉       | 1063/3599 [1:48:04<4:57:40,  7.04s/it]

 30%|██▉       | 1064/3599 [1:48:09<4:31:07,  6.42s/it]

 30%|██▉       | 1065/3599 [1:48:17<4:57:11,  7.04s/it]

 30%|██▉       | 1066/3599 [1:48:22<4:29:33,  6.39s/it]

 30%|██▉       | 1067/3599 [1:48:31<4:57:49,  7.06s/it]

 30%|██▉       | 1068/3599 [1:48:37<4:41:18,  6.67s/it]ERROR: [youtube] 84K95N2l16s: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 30%|██▉       | 1069/3599 [1:48:37<3:24:27,  4.85s/it]

 30%|██▉       | 1070/3599 [1:48:44<3:42:08,  5.27s/it]

 30%|██▉       | 1071/3599 [1:48:53<4:38:09,  6.60s/it]ERROR: [youtube] 863STpyfGB0: Video unavailable
 30%|██▉       | 1072/3599 [1:48:54<3:21:45,  4.79s/it]

 30%|██▉       | 1073/3599 [1:49:01<3:47:33,  5.41s/it]ERROR: [youtube] 88AWuXFZkTU: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 30%|██▉       | 1074/3599 [1:49:01<2:46:15,  3.95s/it]

 30%|██▉       | 1075/3599 [1:49:06<3:00:52,  4.30s/it]

 30%|██▉       | 1076/3599 [1:49:11<3:02:20,  4.34s/it]ERROR: [youtube] 88id3bEvC4s: Video unavailable
 30%|██▉       | 1077/3599 [1:49:11<2:16:11,  3.24s/it]

 30%|██▉       | 1078/3599 [1:49:17<2:42:38,  3.87s/it]ERROR: [youtube] 89iaXmMRQ20: Video unavailable
 30%|██▉       | 1079/3599 [1:49:17<2:00:11,  2.86s/it]

 30%|███       | 1080/3599 [1:49:22<2:22:53,  3.40s/it]

 30%|███       | 1081/3599 [1:49:28<2:59:07,  4.27s/it]

 30%|███       | 1082/3599 [1:49:32<2:57:55,  4.24s/it]

 30%|███       | 1083/3599 [1:49:44<4:29:58,  6.44s/it]

 30%|███       | 1084/3599 [1:49:49<4:14:42,  6.08s/it]

 30%|███       | 1085/3599 [1:49:52<3:39:24,  5.24s/it]

 30%|███       | 1086/3599 [1:49:58<3:43:42,  5.34s/it]

 30%|███       | 1087/3599 [1:50:07<4:29:03,  6.43s/it]

 30%|███       | 1088/3599 [1:50:12<4:07:44,  5.92s/it]

 30%|███       | 1089/3599 [1:50:21<4:48:03,  6.89s/it]

 30%|███       | 1090/3599 [1:50:32<5:39:22,  8.12s/it]

 30%|███       | 1091/3599 [1:50:39<5:32:39,  7.96s/it]

 30%|███       | 1092/3599 [1:50:46<5:08:28,  7.38s/it]

 30%|███       | 1093/3599 [1:50:59<6:26:32,  9.25s/it]ERROR: [youtube] 8Ewzh_yt0qc: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 30%|███       | 1094/3599 [1:51:00<4:37:39,  6.65s/it]

 30%|███       | 1095/3599 [1:51:05<4:18:53,  6.20s/it]

 30%|███       | 1096/3599 [1:51:20<6:11:57,  8.92s/it]

 30%|███       | 1097/3599 [1:51:29<6:12:35,  8.94s/it]

 31%|███       | 1098/3599 [1:51:38<6:08:58,  8.85s/it]

 31%|███       | 1099/3599 [1:51:42<5:08:39,  7.41s/it]

 31%|███       | 1100/3599 [1:51:47<4:40:14,  6.73s/it]ERROR: [youtube] 8IDK38GpZKg: Video unavailable
 31%|███       | 1101/3599 [1:51:48<3:24:23,  4.91s/it]

 31%|███       | 1102/3599 [1:51:58<4:31:49,  6.53s/it]ERROR: [youtube] 8InQJ0Nng0M: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 31%|███       | 1103/3599 [1:51:58<3:17:17,  4.74s/it]

 31%|███       | 1104/3599 [1:52:13<5:18:07,  7.65s/it]

 31%|███       | 1105/3599 [1:52:26<6:28:51,  9.36s/it]

 31%|███       | 1106/3599 [1:52:32<5:45:00,  8.30s/it]ERROR: [youtube] 8KCx42Bi12g: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 31%|███       | 1107/3599 [1:52:33<4:08:34,  5.99s/it]

 31%|███       | 1108/3599 [1:52:38<4:05:51,  5.92s/it]

 31%|███       | 1109/3599 [1:52:50<5:21:33,  7.75s/it]

 31%|███       | 1110/3599 [1:52:58<5:23:14,  7.79s/it]

 31%|███       | 1111/3599 [1:53:07<5:36:51,  8.12s/it]

 31%|███       | 1112/3599 [1:53:22<6:57:05, 10.06s/it]

 31%|███       | 1113/3599 [1:53:26<5:46:33,  8.36s/it]

 31%|███       | 1114/3599 [1:53:32<5:18:29,  7.69s/it]

 31%|███       | 1115/3599 [1:53:37<4:45:48,  6.90s/it]

 31%|███       | 1116/3599 [1:53:44<4:35:57,  6.67s/it]

 31%|███       | 1117/3599 [1:53:47<4:00:32,  5.81s/it]

 31%|███       | 1118/3599 [1:53:56<4:30:04,  6.53s/it]

 31%|███       | 1119/3599 [1:54:04<4:54:38,  7.13s/it]

 31%|███       | 1120/3599 [1:54:09<4:23:20,  6.37s/it]

 31%|███       | 1121/3599 [1:54:13<4:01:17,  5.84s/it]

 31%|███       | 1122/3599 [1:54:18<3:45:06,  5.45s/it]

 31%|███       | 1123/3599 [1:54:24<3:59:03,  5.79s/it]

 31%|███       | 1124/3599 [1:54:30<3:59:20,  5.80s/it]

 31%|███▏      | 1125/3599 [1:54:35<3:45:01,  5.46s/it]

 31%|███▏      | 1126/3599 [1:54:40<3:36:07,  5.24s/it]

 31%|███▏      | 1127/3599 [1:54:44<3:19:57,  4.85s/it]ERROR: [youtube] 8TtyZNBSQFw: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 31%|███▏      | 1128/3599 [1:54:44<2:26:52,  3.57s/it]

 31%|███▏      | 1129/3599 [1:54:49<2:39:54,  3.88s/it]

 31%|███▏      | 1130/3599 [1:54:56<3:16:12,  4.77s/it]

 31%|███▏      | 1131/3599 [1:55:03<3:42:50,  5.42s/it]

 31%|███▏      | 1132/3599 [1:55:07<3:31:02,  5.13s/it]

 31%|███▏      | 1133/3599 [1:55:11<3:13:13,  4.70s/it]

 32%|███▏      | 1134/3599 [1:55:17<3:35:04,  5.24s/it]

 32%|███▏      | 1135/3599 [1:55:23<3:37:54,  5.31s/it]

 32%|███▏      | 1136/3599 [1:55:49<8:01:52, 11.74s/it]

 32%|███▏      | 1137/3599 [1:55:55<6:39:52,  9.75s/it]

 32%|███▏      | 1138/3599 [1:56:00<5:42:40,  8.35s/it]

 32%|███▏      | 1139/3599 [1:56:03<4:41:00,  6.85s/it]

 32%|███▏      | 1140/3599 [1:56:09<4:25:12,  6.47s/it]

 32%|███▏      | 1141/3599 [1:56:13<3:58:29,  5.82s/it]

 32%|███▏      | 1142/3599 [1:56:18<3:52:47,  5.68s/it]

 32%|███▏      | 1143/3599 [1:56:23<3:40:28,  5.39s/it]

 32%|███▏      | 1144/3599 [1:56:28<3:39:18,  5.36s/it]ERROR: [youtube] 8aODU_lTEos: Video unavailable
 32%|███▏      | 1145/3599 [1:56:29<2:43:13,  3.99s/it]

 32%|███▏      | 1146/3599 [1:56:36<3:20:32,  4.91s/it]

 32%|███▏      | 1147/3599 [1:56:40<3:03:46,  4.50s/it]

 32%|███▏      | 1148/3599 [1:56:47<3:42:43,  5.45s/it]

 32%|███▏      | 1149/3599 [1:56:52<3:31:55,  5.19s/it]

 32%|███▏      | 1150/3599 [1:57:09<6:02:31,  8.88s/it]

 32%|███▏      | 1151/3599 [1:57:14<5:10:00,  7.60s/it]ERROR: [youtube] 8cJL0VjIXzM: Video unavailable
 32%|███▏      | 1152/3599 [1:57:14<3:43:23,  5.48s/it]

 32%|███▏      | 1153/3599 [1:57:25<4:48:29,  7.08s/it]

 32%|███▏      | 1154/3599 [1:57:30<4:21:10,  6.41s/it]

 32%|███▏      | 1155/3599 [1:57:39<4:50:29,  7.13s/it]ERROR: [youtube] 8ee-bCZtc_g: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 32%|███▏      | 1156/3599 [1:57:40<3:30:11,  5.16s/it]

 32%|███▏      | 1157/3599 [1:57:44<3:27:21,  5.09s/it]

 32%|███▏      | 1158/3599 [1:57:48<3:11:35,  4.71s/it]

 32%|███▏      | 1159/3599 [1:57:53<3:11:23,  4.71s/it]

 32%|███▏      | 1160/3599 [1:57:58<3:19:43,  4.91s/it]

 32%|███▏      | 1161/3599 [1:58:03<3:16:04,  4.83s/it]

 32%|███▏      | 1162/3599 [1:58:08<3:21:54,  4.97s/it]

 32%|███▏      | 1163/3599 [1:58:15<3:40:46,  5.44s/it]

 32%|███▏      | 1164/3599 [1:58:20<3:33:44,  5.27s/it]

 32%|███▏      | 1165/3599 [1:58:24<3:16:13,  4.84s/it]

 32%|███▏      | 1166/3599 [1:58:28<3:14:17,  4.79s/it]

 32%|███▏      | 1167/3599 [1:58:33<3:17:20,  4.87s/it]

 32%|███▏      | 1168/3599 [1:58:38<3:12:11,  4.74s/it]

 32%|███▏      | 1169/3599 [1:58:43<3:23:56,  5.04s/it]

 33%|███▎      | 1170/3599 [1:58:49<3:35:21,  5.32s/it]

 33%|███▎      | 1171/3599 [1:58:54<3:21:02,  4.97s/it]ERROR: [youtube] 8s7RjeW0BiA: Video unavailable
 33%|███▎      | 1172/3599 [1:58:54<2:27:08,  3.64s/it]ERROR: [youtube] 8spZIVyokz8: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 33%|███▎      | 1173/3599 [1:58:55<1:49:43,  2.71s/it]

 33%|███▎      | 1174/3599 [1:59:09<4:06:38,  6.10s/it]ERROR: [youtube] 8tkL9td7E1A: Video unavailable
 33%|███▎      | 1175/3599 [1:59:09<2:59:42,  4.45s/it]

 33%|███▎      | 1176/3599 [1:59:16<3:26:04,  5.10s/it]ERROR: [youtube] 8uC7ntLrm7k: Video unavailable
 33%|███▎      | 1177/3599 [1:59:16<2:31:09,  3.74s/it]

 33%|███▎      | 1178/3599 [1:59:20<2:31:36,  3.76s/it]

 33%|███▎      | 1179/3599 [1:59:24<2:37:16,  3.90s/it]

 33%|███▎      | 1180/3599 [1:59:29<2:46:30,  4.13s/it]

 33%|███▎      | 1181/3599 [1:59:34<2:54:57,  4.34s/it]

 33%|███▎      | 1182/3599 [1:59:40<3:12:32,  4.78s/it]

 33%|███▎      | 1183/3599 [1:59:45<3:15:24,  4.85s/it]

 33%|███▎      | 1184/3599 [1:59:52<3:43:04,  5.54s/it]

ERROR: unable to download video data: HTTP Error 403: Forbidden
 33%|███▎      | 1185/3599 [2:00:08<5:49:24,  8.68s/it]

 33%|███▎      | 1186/3599 [2:00:12<4:54:59,  7.34s/it]

 33%|███▎      | 1187/3599 [2:00:17<4:22:54,  6.54s/it]

 33%|███▎      | 1188/3599 [2:00:22<4:01:24,  6.01s/it]

 33%|███▎      | 1189/3599 [2:00:27<3:48:46,  5.70s/it]

 33%|███▎      | 1190/3599 [2:00:31<3:33:19,  5.31s/it]

 33%|███▎      | 1191/3599 [2:00:37<3:39:47,  5.48s/it]ERROR: [youtube] 92GM757etiI: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 33%|███▎      | 1192/3599 [2:00:37<2:40:16,  4.00s/it]

 33%|███▎      | 1193/3599 [2:00:43<3:04:25,  4.60s/it]

 33%|███▎      | 1194/3599 [2:00:48<3:06:13,  4.65s/it]

 33%|███▎      | 1195/3599 [2:00:54<3:14:40,  4.86s/it]

 33%|███▎      | 1196/3599 [2:00:57<3:03:38,  4.59s/it]

 33%|███▎      | 1197/3599 [2:01:03<3:15:47,  4.89s/it]ERROR: [youtube] 97jqYhgP4LE: Video unavailable
 33%|███▎      | 1198/3599 [2:01:04<2:23:45,  3.59s/it]

 33%|███▎      | 1199/3599 [2:01:08<2:37:54,  3.95s/it]

 33%|███▎      | 1200/3599 [2:01:26<5:20:23,  8.01s/it]

 33%|███▎      | 1201/3599 [2:02:06<11:42:52, 17.59s/it]

 33%|███▎      | 1202/3599 [2:02:15<9:56:23, 14.93s/it]

 33%|███▎      | 1203/3599 [2:02:20<8:07:55, 12.22s/it]

 33%|███▎      | 1204/3599 [2:02:25<6:37:01,  9.95s/it]

 33%|███▎      | 1205/3599 [2:02:37<7:00:37, 10.54s/it]

ERROR: unable to download video data: HTTP Error 403: Forbidden
 34%|███▎      | 1206/3599 [2:02:41<5:47:29,  8.71s/it]

 34%|███▎      | 1207/3599 [2:02:47<5:08:21,  7.73s/it]

 34%|███▎      | 1208/3599 [2:02:52<4:42:24,  7.09s/it]ERROR: [youtube] 9I9-5SUSVxc: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 34%|███▎      | 1209/3599 [2:02:53<3:24:30,  5.13s/it]

 34%|███▎      | 1210/3599 [2:02:59<3:29:35,  5.26s/it]

 34%|███▎      | 1211/3599 [2:03:03<3:17:56,  4.97s/it]

 34%|███▎      | 1212/3599 [2:03:08<3:15:12,  4.91s/it]ERROR: [youtube] 9TQvlEdK_C8: Video unavailable
 34%|███▎      | 1213/3599 [2:03:08<2:23:03,  3.60s/it]

 34%|███▎      | 1214/3599 [2:03:15<2:59:37,  4.52s/it]

 34%|███▍      | 1215/3599 [2:03:29<4:48:07,  7.25s/it]

 34%|███▍      | 1216/3599 [2:03:38<5:14:55,  7.93s/it]

 34%|███▍      | 1217/3599 [2:03:44<4:56:48,  7.48s/it]

 34%|███▍      | 1218/3599 [2:03:51<4:45:22,  7.19s/it]

 34%|███▍      | 1219/3599 [2:03:57<4:34:20,  6.92s/it]

 34%|███▍      | 1220/3599 [2:04:02<4:12:27,  6.37s/it]ERROR: [youtube] 9lIKn0pKBMU: Video unavailable
 34%|███▍      | 1221/3599 [2:04:03<3:02:59,  4.62s/it]

 34%|███▍      | 1222/3599 [2:04:12<3:56:50,  5.98s/it]

 34%|███▍      | 1223/3599 [2:04:16<3:28:17,  5.26s/it]

 34%|███▍      | 1224/3599 [2:04:20<3:22:37,  5.12s/it]

 34%|███▍      | 1225/3599 [2:04:28<3:56:47,  5.98s/it]ERROR: unable to download video data: HTTP Error 403: Forbidden
 34%|███▍      | 1226/3599 [2:04:30<3:05:18,  4.69s/it]ERROR: [youtube] 9pn4U1Yi2gc: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 34%|███▍      | 1227/3599 [2:04:31<2:15:46,  3.43s/it]

 34%|███▍      | 1228/3599 [2:05:13<9:52:27, 14.99s/it]

 34%|███▍      | 1229/3599 [2:05:17<7:41:36, 11.69s/it]

 34%|███▍      | 1230/3599 [2:05:22<6:31:39,  9.92s/it]

 34%|███▍      | 1231/3599 [2:05:37<7:24:12, 11.26s/it]ERROR: [youtube] 9vckbanAcik: Video unavailable
 34%|███▍      | 1232/3599 [2:05:37<5:17:54,  8.06s/it]

 34%|███▍      | 1233/3599 [2:05:43<4:53:25,  7.44s/it]

 34%|███▍      | 1234/3599 [2:05:47<4:12:37,  6.41s/it]

 34%|███▍      | 1235/3599 [2:06:33<11:59:57, 18.27s/it]

 34%|███▍      | 1236/3599 [2:06:54<12:29:54, 19.04s/it]ERROR: [youtube] A-dhYOS3PII: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 34%|███▍      | 1237/3599 [2:06:55<8:51:00, 13.49s/it] ERROR: [youtube] A1J0-jh3pis: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 34%|███▍      | 1238/3599 [2:06:55<6:18:23,  9.62s/it]

 34%|███▍      | 1239/3599 [2:07:00<5:19:04,  8.11s/it]ERROR: [youtube] A69fpuHZYpY: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 34%|███▍      | 1240/3599 [2:07:00<3:49:52,  5.85s/it]

 34%|███▍      | 1241/3599 [2:07:05<3:32:59,  5.42s/it]

 35%|███▍      | 1242/3599 [2:07:09<3:15:55,  4.99s/it]ERROR: [youtube] A9v6zNdWN20: Video unavailable
 35%|███▍      | 1243/3599 [2:07:09<2:23:15,  3.65s/it]

 35%|███▍      | 1244/3599 [2:07:43<8:20:47, 12.76s/it]

 35%|███▍      | 1245/3599 [2:07:49<7:02:11, 10.76s/it]

 35%|███▍      | 1246/3599 [2:07:58<6:31:19,  9.98s/it]

 35%|███▍      | 1247/3599 [2:08:05<5:57:14,  9.11s/it]

 35%|███▍      | 1248/3599 [2:08:12<5:39:20,  8.66s/it]

 35%|███▍      | 1249/3599 [2:08:19<5:11:20,  7.95s/it]

 35%|███▍      | 1250/3599 [2:08:24<4:42:55,  7.23s/it]

 35%|███▍      | 1251/3599 [2:08:31<4:40:18,  7.16s/it]

 35%|███▍      | 1252/3599 [2:08:37<4:20:25,  6.66s/it]ERROR: [youtube] AMhz60Na5Zs: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 35%|███▍      | 1253/3599 [2:08:37<3:10:15,  4.87s/it]

 35%|███▍      | 1254/3599 [2:08:43<3:19:00,  5.09s/it]

 35%|███▍      | 1255/3599 [2:08:48<3:14:06,  4.97s/it]

 35%|███▍      | 1256/3599 [2:08:53<3:22:41,  5.19s/it]ERROR: [youtube] AQ3J03yzNNs: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 35%|███▍      | 1257/3599 [2:08:54<2:28:26,  3.80s/it]

 35%|███▍      | 1258/3599 [2:09:04<3:37:15,  5.57s/it]

 35%|███▍      | 1259/3599 [2:09:08<3:21:08,  5.16s/it]ERROR: [youtube] AUcGyblhyH8: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 35%|███▌      | 1260/3599 [2:09:08<2:29:07,  3.83s/it]

 35%|███▌      | 1261/3599 [2:09:14<2:46:15,  4.27s/it]

 35%|███▌      | 1262/3599 [2:09:34<5:51:43,  9.03s/it]ERROR: [youtube] AYeAcr2OFCk: Video unavailable
 35%|███▌      | 1263/3599 [2:09:34<4:12:26,  6.48s/it]

 35%|███▌      | 1264/3599 [2:09:39<3:44:34,  5.77s/it]ERROR: [youtube] A_e1X2mV45M: Video unavailable
 35%|███▌      | 1265/3599 [2:09:39<2:43:18,  4.20s/it]

 35%|███▌      | 1266/3599 [2:09:58<5:31:50,  8.53s/it]

 35%|███▌      | 1267/3599 [2:10:05<5:15:42,  8.12s/it]ERROR: [youtube] AdpH42R1qp4: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 35%|███▌      | 1268/3599 [2:10:05<3:48:13,  5.87s/it]

 35%|███▌      | 1269/3599 [2:10:11<3:44:07,  5.77s/it]

 35%|███▌      | 1270/3599 [2:10:16<3:37:47,  5.61s/it]

 35%|███▌      | 1271/3599 [2:10:21<3:23:56,  5.26s/it]ERROR: [youtube] AfppI-_coj0: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 35%|███▌      | 1272/3599 [2:10:21<2:29:50,  3.86s/it]

 35%|███▌      | 1273/3599 [2:10:27<2:50:37,  4.40s/it]

 35%|███▌      | 1274/3599 [2:10:38<4:04:19,  6.30s/it]

 35%|███▌      | 1275/3599 [2:10:42<3:42:17,  5.74s/it]

 35%|███▌      | 1276/3599 [2:10:47<3:28:09,  5.38s/it]ERROR: [youtube] AnHSgjsk-PE: This video has been removed for violating YouTube's Terms of Service
 35%|███▌      | 1277/3599 [2:10:47<2:32:40,  3.94s/it]

 36%|███▌      | 1278/3599 [2:10:54<3:09:51,  4.91s/it]

 36%|███▌      | 1279/3599 [2:11:04<3:59:52,  6.20s/it]

 36%|███▌      | 1280/3599 [2:11:08<3:39:11,  5.67s/it]

 36%|███▌      | 1281/3599 [2:11:12<3:24:24,  5.29s/it]ERROR: [youtube] Aoy3LDCVbq4: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 36%|███▌      | 1282/3599 [2:11:13<2:29:03,  3.86s/it]

 36%|███▌      | 1283/3599 [2:11:18<2:44:57,  4.27s/it]

 36%|███▌      | 1284/3599 [2:11:22<2:38:33,  4.11s/it]

 36%|███▌      | 1285/3599 [2:11:28<3:02:41,  4.74s/it]

 36%|███▌      | 1286/3599 [2:11:42<4:50:30,  7.54s/it]

 36%|███▌      | 1287/3599 [2:11:47<4:18:59,  6.72s/it]

 36%|███▌      | 1288/3599 [2:11:52<3:55:54,  6.12s/it]

 36%|███▌      | 1289/3599 [2:11:55<3:26:22,  5.36s/it]ERROR: [youtube] Ayp6zpiTu4Q: Video unavailable
 36%|███▌      | 1290/3599 [2:11:56<2:30:12,  3.90s/it]ERROR: [youtube] B0FvzyLOfJI: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 36%|███▌      | 1291/3599 [2:11:56<1:51:09,  2.89s/it]ERROR: [youtube] B1rNxfrHU40: Video unavailable
 36%|███▌      | 1292/3599 [2:11:57<1:23:22,  2.17s/it]

 36%|███▌      | 1293/3599 [2:12:01<1:46:02,  2.76s/it]

 36%|███▌      | 1294/3599 [2:12:06<2:15:25,  3.53s/it]

 36%|███▌      | 1295/3599 [2:12:11<2:29:39,  3.90s/it]

 36%|███▌      | 1296/3599 [2:12:16<2:36:38,  4.08s/it]

 36%|███▌      | 1297/3599 [2:12:22<3:05:36,  4.84s/it]

 36%|███▌      | 1298/3599 [2:12:30<3:41:51,  5.79s/it]ERROR: [youtube] B94gmaO5zSY: Video unavailable. This video contains content from ShallAdoreCats. It is not available in your country.
 36%|███▌      | 1299/3599 [2:12:31<2:44:37,  4.29s/it]

 36%|███▌      | 1300/3599 [2:12:36<2:51:31,  4.48s/it]

 36%|███▌      | 1301/3599 [2:12:42<3:13:28,  5.05s/it]

 36%|███▌      | 1302/3599 [2:12:47<3:12:01,  5.02s/it]

 36%|███▌      | 1303/3599 [2:12:53<3:24:05,  5.33s/it]

 36%|███▌      | 1304/3599 [2:12:58<3:12:25,  5.03s/it]

 36%|███▋      | 1305/3599 [2:13:13<5:16:24,  8.28s/it]

 36%|███▋      | 1306/3599 [2:14:10<14:32:01, 22.82s/it]

 36%|███▋      | 1307/3599 [2:14:16<11:16:54, 17.72s/it]

 36%|███▋      | 1308/3599 [2:14:20<8:40:44, 13.64s/it]

 36%|███▋      | 1309/3599 [2:14:30<7:59:03, 12.55s/it]

 36%|███▋      | 1310/3599 [2:14:35<6:25:02, 10.09s/it]

 36%|███▋      | 1311/3599 [2:14:40<5:26:52,  8.57s/it]

 36%|███▋      | 1312/3599 [2:14:44<4:39:10,  7.32s/it]

 36%|███▋      | 1313/3599 [2:14:50<4:27:15,  7.01s/it]

 37%|███▋      | 1314/3599 [2:14:56<4:16:23,  6.73s/it]

 37%|███▋      | 1315/3599 [2:15:26<8:40:44, 13.68s/it]

 37%|███▋      | 1316/3599 [2:15:31<7:00:56, 11.06s/it]

 37%|███▋      | 1317/3599 [2:15:36<5:53:27,  9.29s/it]

 37%|███▋      | 1318/3599 [2:16:02<9:03:52, 14.31s/it]

 37%|███▋      | 1319/3599 [2:16:13<8:20:19, 13.17s/it]

 37%|███▋      | 1320/3599 [2:16:23<7:48:12, 12.33s/it]

 37%|███▋      | 1321/3599 [2:16:32<7:12:15, 11.39s/it]

 37%|███▋      | 1322/3599 [2:16:39<6:18:03,  9.96s/it]

 37%|███▋      | 1323/3599 [2:16:44<5:17:38,  8.37s/it]

 37%|███▋      | 1324/3599 [2:17:00<6:48:01, 10.76s/it]

 37%|███▋      | 1325/3599 [2:17:10<6:41:02, 10.58s/it]ERROR: [youtube] BeGmDyvHM0Y: Video unavailable
 37%|███▋      | 1326/3599 [2:17:11<4:47:52,  7.60s/it]

 37%|███▋      | 1327/3599 [2:17:16<4:16:30,  6.77s/it]

 37%|███▋      | 1328/3599 [2:17:23<4:22:39,  6.94s/it]

 37%|███▋      | 1329/3599 [2:17:28<4:05:38,  6.49s/it]

 37%|███▋      | 1330/3599 [2:17:57<8:19:47, 13.22s/it]

 37%|███▋      | 1331/3599 [2:18:02<6:47:30, 10.78s/it]

 37%|███▋      | 1332/3599 [2:18:08<5:47:32,  9.20s/it]

 37%|███▋      | 1333/3599 [2:18:12<4:48:50,  7.65s/it]ERROR: [youtube] Bqc2kj9Pe5A: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 37%|███▋      | 1334/3599 [2:18:13<3:28:16,  5.52s/it]

 37%|███▋      | 1335/3599 [2:18:20<3:46:21,  6.00s/it]

 37%|███▋      | 1336/3599 [2:18:27<4:00:56,  6.39s/it]ERROR: [youtube] BwW9-OK7AVc: Video unavailable
 37%|███▋      | 1337/3599 [2:18:28<2:55:03,  4.64s/it]ERROR: [youtube] BzCJsRjDv-I: Video unavailable
 37%|███▋      | 1338/3599 [2:18:28<2:08:32,  3.41s/it]

 37%|███▋      | 1339/3599 [2:18:36<2:59:45,  4.77s/it]ERROR: [youtube] C2VOE1ty_6A: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 37%|███▋      | 1340/3599 [2:18:37<2:11:26,  3.49s/it]

 37%|███▋      | 1341/3599 [2:18:42<2:29:56,  3.98s/it]

 37%|███▋      | 1342/3599 [2:18:47<2:43:09,  4.34s/it]ERROR: [youtube] C57UbkNAsGU: Video unavailable
 37%|███▋      | 1343/3599 [2:18:47<2:00:08,  3.20s/it]

 37%|███▋      | 1344/3599 [2:18:54<2:37:49,  4.20s/it]

 37%|███▋      | 1345/3599 [2:18:58<2:36:48,  4.17s/it]

 37%|███▋      | 1346/3599 [2:19:03<2:41:04,  4.29s/it]

 37%|███▋      | 1347/3599 [2:19:36<8:13:11, 13.14s/it]

 37%|███▋      | 1348/3599 [2:19:41<6:33:50, 10.50s/it]

 37%|███▋      | 1349/3599 [2:19:45<5:22:49,  8.61s/it]

 38%|███▊      | 1350/3599 [2:19:50<4:47:15,  7.66s/it]

 38%|███▊      | 1351/3599 [2:19:55<4:07:34,  6.61s/it]

 38%|███▊      | 1352/3599 [2:20:00<3:49:38,  6.13s/it]ERROR: [youtube] CEQZY5l_u4s: This video has been removed for violating YouTube's policy on violent or graphic content
 38%|███▊      | 1353/3599 [2:20:00<2:47:15,  4.47s/it]

 38%|███▊      | 1354/3599 [2:20:16<4:58:14,  7.97s/it]

 38%|███▊      | 1355/3599 [2:20:22<4:38:22,  7.44s/it]

 38%|███▊      | 1356/3599 [2:20:27<4:04:01,  6.53s/it]

 38%|███▊      | 1357/3599 [2:20:34<4:05:19,  6.57s/it]

 38%|███▊      | 1358/3599 [2:20:38<3:42:04,  5.95s/it]

 38%|███▊      | 1359/3599 [2:20:47<4:17:35,  6.90s/it]

 38%|███▊      | 1360/3599 [2:20:56<4:37:56,  7.45s/it]

 38%|███▊      | 1361/3599 [2:21:09<5:37:32,  9.05s/it]

 38%|███▊      | 1362/3599 [2:21:17<5:29:08,  8.83s/it]ERROR: [youtube] CVcdeZskaXk: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 38%|███▊      | 1363/3599 [2:21:18<3:56:05,  6.34s/it]ERROR: [youtube] CWdknkJbs2Q: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 38%|███▊      | 1364/3599 [2:21:18<2:51:05,  4.59s/it]

 38%|███▊      | 1365/3599 [2:21:23<2:59:24,  4.82s/it]ERROR: [youtube] CXKHEiMPMgA: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 38%|███▊      | 1366/3599 [2:21:24<2:11:37,  3.54s/it]

 38%|███▊      | 1367/3599 [2:22:18<11:33:59, 18.66s/it]

 38%|███▊      | 1368/3599 [2:22:22<8:49:57, 14.25s/it]

 38%|███▊      | 1369/3599 [2:22:28<7:15:40, 11.72s/it]ERROR: [youtube] CdwDAvZB6-w: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 38%|███▊      | 1370/3599 [2:22:28<5:10:49,  8.37s/it]

 38%|███▊      | 1371/3599 [2:22:35<4:58:05,  8.03s/it]

 38%|███▊      | 1372/3599 [2:22:41<4:33:18,  7.36s/it]

 38%|███▊      | 1373/3599 [2:22:46<4:01:44,  6.52s/it]

 38%|███▊      | 1374/3599 [2:22:50<3:36:12,  5.83s/it]

 38%|███▊      | 1375/3599 [2:22:59<4:09:03,  6.72s/it]

 38%|███▊      | 1376/3599 [2:23:11<5:12:51,  8.44s/it]

[download] Got error: HTTP Error 500: Internal Server Error
 38%|███▊      | 1377/3599 [2:23:29<6:54:17, 11.19s/it]ERROR: [youtube] CsQoVjwQO5s: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 38%|███▊      | 1378/3599 [2:23:29<4:56:17,  8.00s/it]

 38%|███▊      | 1379/3599 [2:23:36<4:41:27,  7.61s/it]

 38%|███▊      | 1380/3599 [2:23:40<3:56:40,  6.40s/it]

 38%|███▊      | 1381/3599 [2:23:45<3:46:37,  6.13s/it]

 38%|███▊      | 1382/3599 [2:24:32<11:20:48, 18.43s/it]

 38%|███▊      | 1383/3599 [2:24:39<9:05:30, 14.77s/it]

 38%|███▊      | 1384/3599 [2:24:45<7:34:09, 12.30s/it]

 38%|███▊      | 1385/3599 [2:24:52<6:35:12, 10.71s/it]

 39%|███▊      | 1386/3599 [2:25:00<6:07:10,  9.96s/it]

 39%|███▊      | 1387/3599 [2:25:24<8:43:38, 14.20s/it]

 39%|███▊      | 1388/3599 [2:25:28<6:44:42, 10.98s/it]

[download] Got error: HTTP Error 500: Internal Server ErrorR:
 39%|███▊      | 1390/3599 [2:25:50<6:32:40, 10.67s/it]

 39%|███▊      | 1391/3599 [2:25:54<5:25:24,  8.84s/it]

 39%|███▊      | 1392/3599 [2:25:59<4:46:07,  7.78s/it]

 39%|███▊      | 1393/3599 [2:26:04<4:06:28,  6.70s/it]ERROR: [youtube] DCGiQdKDi18: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 39%|███▊      | 1394/3599 [2:26:04<2:59:39,  4.89s/it]

 39%|███▉      | 1395/3599 [2:26:10<3:05:36,  5.05s/it]

 39%|███▉      | 1396/3599 [2:26:14<2:59:43,  4.90s/it]

 39%|███▉      | 1397/3599 [2:26:22<3:25:16,  5.59s/it]ERROR: [youtube] DJYnn3-kpug: Video unavailable
 39%|███▉      | 1398/3599 [2:26:22<2:29:21,  4.07s/it]

 39%|███▉      | 1399/3599 [2:26:27<2:38:58,  4.34s/it]

 39%|███▉      | 1400/3599 [2:26:34<3:13:13,  5.27s/it]ERROR: [youtube] DMk7AW6OWH0: Video unavailable
 39%|███▉      | 1401/3599 [2:26:35<2:20:48,  3.84s/it]

 39%|███▉      | 1402/3599 [2:27:10<8:08:18, 13.34s/it]

 39%|███▉      | 1403/3599 [2:27:15<6:36:05, 10.82s/it]

 39%|███▉      | 1404/3599 [2:27:21<5:35:51,  9.18s/it]ERROR: [youtube] DQJPySJXq44: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 39%|███▉      | 1405/3599 [2:27:21<4:01:24,  6.60s/it]

 39%|███▉      | 1406/3599 [2:27:34<5:09:53,  8.48s/it]

 39%|███▉      | 1407/3599 [2:27:39<4:34:30,  7.51s/it]ERROR: [youtube] DXEafWngPdM: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 39%|███▉      | 1408/3599 [2:27:40<3:18:30,  5.44s/it]

 39%|███▉      | 1409/3599 [2:27:46<3:24:43,  5.61s/it]

 39%|███▉      | 1410/3599 [2:27:50<3:09:04,  5.18s/it]

 39%|███▉      | 1411/3599 [2:27:56<3:15:53,  5.37s/it]

 39%|███▉      | 1412/3599 [2:28:00<3:02:37,  5.01s/it]

 39%|███▉      | 1413/3599 [2:28:07<3:20:03,  5.49s/it]

 39%|███▉      | 1414/3599 [2:28:12<3:14:41,  5.35s/it]

 39%|███▉      | 1415/3599 [2:28:16<2:58:54,  4.92s/it]

 39%|███▉      | 1416/3599 [2:28:20<2:48:04,  4.62s/it]

 39%|███▉      | 1417/3599 [2:28:24<2:43:08,  4.49s/it]

 39%|███▉      | 1418/3599 [2:28:29<2:53:30,  4.77s/it]

 39%|███▉      | 1419/3599 [2:28:34<2:50:34,  4.69s/it]ERROR: [youtube] DmDsQI1o9w0: Video unavailable
 39%|███▉      | 1420/3599 [2:28:34<2:05:23,  3.45s/it]ERROR: [youtube] DoAUtTdhRuA: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 39%|███▉      | 1421/3599 [2:28:35<1:33:28,  2.57s/it]ERROR: [youtube] DoRiNf26jjM: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 40%|███▉      | 1422/3599 [2:28:35<1:11:17,  1.96s/it]

 40%|███▉      | 1423/3599 [2:28:40<1:43:50,  2.86s/it]

 40%|███▉      | 1424/3599 [2:28:46<2:12:14,  3.65s/it]

 40%|███▉      | 1425/3599 [2:28:54<3:04:21,  5.09s/it]

 40%|███▉      | 1426/3599 [2:29:01<3:19:19,  5.50s/it]ERROR: [youtube] E-9IFd4xWTs: Video unavailable
 40%|███▉      | 1427/3599 [2:29:01<2:25:20,  4.02s/it]

 40%|███▉      | 1428/3599 [2:29:20<5:04:24,  8.41s/it]

 40%|███▉      | 1429/3599 [2:29:27<4:51:45,  8.07s/it]

 40%|███▉      | 1430/3599 [2:29:32<4:10:30,  6.93s/it]ERROR: [youtube] E2uKxZtwofo: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 40%|███▉      | 1431/3599 [2:29:32<3:01:56,  5.04s/it]

 40%|███▉      | 1432/3599 [2:29:36<2:44:49,  4.56s/it]

 40%|███▉      | 1433/3599 [2:29:41<2:50:37,  4.73s/it]

 40%|███▉      | 1434/3599 [2:29:44<2:39:55,  4.43s/it]

 40%|███▉      | 1435/3599 [2:29:50<2:52:58,  4.80s/it]

 40%|███▉      | 1436/3599 [2:29:56<3:04:44,  5.12s/it]

 40%|███▉      | 1437/3599 [2:30:08<4:13:51,  7.05s/it]

 40%|███▉      | 1438/3599 [2:30:13<3:56:19,  6.56s/it]

 40%|███▉      | 1439/3599 [2:30:18<3:40:05,  6.11s/it]

 40%|████      | 1440/3599 [2:30:28<4:16:31,  7.13s/it]

 40%|████      | 1441/3599 [2:30:34<4:13:39,  7.05s/it]

 40%|████      | 1442/3599 [2:30:40<3:56:22,  6.57s/it]

 40%|████      | 1443/3599 [2:30:44<3:29:21,  5.83s/it]

 40%|████      | 1444/3599 [2:30:51<3:42:00,  6.18s/it]ERROR: [youtube] EOlDFflt0SI: Video unavailable
 40%|████      | 1445/3599 [2:30:52<2:41:14,  4.49s/it]

 40%|████      | 1446/3599 [2:30:59<3:10:09,  5.30s/it]

 40%|████      | 1447/3599 [2:31:05<3:21:08,  5.61s/it]ERROR: [youtube] EQf-w-Q36cY: Video unavailable
 40%|████      | 1448/3599 [2:31:06<2:26:30,  4.09s/it]

 40%|████      | 1449/3599 [2:31:10<2:31:56,  4.24s/it]

 40%|████      | 1450/3599 [2:31:14<2:32:19,  4.25s/it]

 40%|████      | 1451/3599 [2:31:21<2:59:14,  5.01s/it]

 40%|████      | 1452/3599 [2:31:27<3:04:03,  5.14s/it]

 40%|████      | 1453/3599 [2:31:33<3:15:17,  5.46s/it]

 40%|████      | 1454/3599 [2:31:46<4:42:32,  7.90s/it]

 40%|████      | 1455/3599 [2:32:01<5:48:13,  9.74s/it]

 40%|████      | 1456/3599 [2:32:35<10:12:17, 17.14s/it]

 40%|████      | 1457/3599 [2:32:39<7:57:20, 13.37s/it] ERROR: [youtube] EYDVqYUdnYY: Video unavailable
 41%|████      | 1458/3599 [2:32:40<5:39:37,  9.52s/it]

 41%|████      | 1459/3599 [2:32:48<5:24:53,  9.11s/it]

 41%|████      | 1460/3599 [2:32:52<4:31:37,  7.62s/it]

 41%|████      | 1461/3599 [2:32:57<4:02:16,  6.80s/it]

 41%|████      | 1462/3599 [2:33:03<3:50:42,  6.48s/it]

 41%|████      | 1463/3599 [2:33:18<5:25:12,  9.14s/it]

 41%|████      | 1464/3599 [2:33:27<5:24:01,  9.11s/it]

 41%|████      | 1465/3599 [2:33:34<4:53:57,  8.26s/it]

 41%|████      | 1466/3599 [2:33:44<5:21:48,  9.05s/it]

 41%|████      | 1467/3599 [2:33:50<4:48:12,  8.11s/it]

 41%|████      | 1468/3599 [2:33:56<4:23:53,  7.43s/it]ERROR: [youtube] EfTYJDFgcjM: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 41%|████      | 1469/3599 [2:33:57<3:10:06,  5.35s/it]

 41%|████      | 1470/3599 [2:34:01<2:57:39,  5.01s/it]

 41%|████      | 1471/3599 [2:34:06<3:01:15,  5.11s/it]

 41%|████      | 1472/3599 [2:34:20<4:28:42,  7.58s/it]

 41%|████      | 1473/3599 [2:34:24<3:49:21,  6.47s/it]

 41%|████      | 1474/3599 [2:34:29<3:40:17,  6.22s/it]

 41%|████      | 1475/3599 [2:34:37<3:56:00,  6.67s/it]

 41%|████      | 1476/3599 [2:34:41<3:25:09,  5.80s/it]

 41%|████      | 1477/3599 [2:34:45<3:12:46,  5.45s/it]

 41%|████      | 1478/3599 [2:34:57<4:22:44,  7.43s/it]

 41%|████      | 1479/3599 [2:35:06<4:34:53,  7.78s/it]

 41%|████      | 1480/3599 [2:35:10<3:58:42,  6.76s/it]ERROR: [youtube] F7CqvjjkHyA: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 41%|████      | 1481/3599 [2:35:11<2:52:26,  4.89s/it]

 41%|████      | 1482/3599 [2:35:22<3:55:05,  6.66s/it]

 41%|████      | 1483/3599 [2:35:26<3:28:05,  5.90s/it]

 41%|████      | 1484/3599 [2:35:35<4:04:06,  6.92s/it]ERROR: [youtube] F8XFcinocYQ: Video unavailable
 41%|████▏     | 1485/3599 [2:35:36<2:56:01,  5.00s/it]

 41%|████▏     | 1486/3599 [2:35:40<2:47:06,  4.75s/it]

 41%|████▏     | 1487/3599 [2:35:45<2:50:48,  4.85s/it]ERROR: [youtube] FBVC0E-F0GY: Video unavailable
 41%|████▏     | 1488/3599 [2:35:45<2:04:53,  3.55s/it]ERROR: [youtube] FCvQ_YQSFFQ: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 41%|████▏     | 1489/3599 [2:35:46<1:33:56,  2.67s/it]ERROR: [youtube] FIUyQJK7QY0: Video unavailable
 41%|████▏     | 1490/3599 [2:35:47<1:11:40,  2.04s/it]

 41%|████▏     | 1491/3599 [2:35:51<1:38:53,  2.81s/it]

 41%|████▏     | 1492/3599 [2:35:57<2:08:44,  3.67s/it]

 41%|████▏     | 1493/3599 [2:36:04<2:45:23,  4.71s/it]

 42%|████▏     | 1494/3599 [2:36:07<2:31:17,  4.31s/it]

 42%|████▏     | 1495/3599 [2:36:13<2:44:02,  4.68s/it]

 42%|████▏     | 1496/3599 [2:36:18<2:51:47,  4.90s/it]

 42%|████▏     | 1497/3599 [2:36:27<3:33:08,  6.08s/it]ERROR: [youtube] FXGw5wYOgmM: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 42%|████▏     | 1498/3599 [2:36:28<2:34:44,  4.42s/it]

 42%|████▏     | 1499/3599 [2:36:35<3:05:56,  5.31s/it]

 42%|████▏     | 1500/3599 [2:37:07<7:46:22, 13.33s/it]

 42%|████▏     | 1501/3599 [2:37:13<6:23:11, 10.96s/it]

 42%|████▏     | 1502/3599 [2:37:19<5:39:16,  9.71s/it]

 42%|████▏     | 1503/3599 [2:37:31<5:56:19, 10.20s/it]ERROR: [youtube] Fge5Fhh-My4: Sign in to confirm your age. This video may be inappropriate for some users. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 42%|████▏     | 1504/3599 [2:37:32<4:23:55,  7.56s/it]

 42%|████▏     | 1505/3599 [2:37:46<5:32:40,  9.53s/it]

 42%|████▏     | 1506/3599 [2:37:51<4:47:19,  8.24s/it]

 42%|████▏     | 1507/3599 [2:37:58<4:29:27,  7.73s/it]

 42%|████▏     | 1508/3599 [2:38:09<5:03:15,  8.70s/it]

 42%|████▏     | 1509/3599 [2:38:15<4:33:26,  7.85s/it]

 42%|████▏     | 1510/3599 [2:38:25<4:53:22,  8.43s/it]ERROR: [youtube] FtNV_Gq62l8: Video unavailable
 42%|████▏     | 1511/3599 [2:38:25<3:30:23,  6.05s/it]

 42%|████▏     | 1512/3599 [2:38:32<3:34:37,  6.17s/it]

 42%|████▏     | 1513/3599 [2:38:43<4:31:58,  7.82s/it]

 42%|████▏     | 1514/3599 [2:38:51<4:29:59,  7.77s/it]

 42%|████▏     | 1515/3599 [2:38:56<3:58:42,  6.87s/it]

 42%|████▏     | 1516/3599 [2:39:00<3:35:16,  6.20s/it]ERROR: [youtube] G0aNYeQ6tI8: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 42%|████▏     | 1517/3599 [2:39:01<2:35:57,  4.49s/it]

 42%|████▏     | 1518/3599 [2:39:10<3:23:30,  5.87s/it]ERROR: [youtube] GBqr91Gadsw: Video unavailable
 42%|████▏     | 1519/3599 [2:39:10<2:27:41,  4.26s/it]

 42%|████▏     | 1520/3599 [2:39:16<2:40:42,  4.64s/it]

 42%|████▏     | 1521/3599 [2:39:20<2:31:33,  4.38s/it]

 42%|████▏     | 1522/3599 [2:39:25<2:38:44,  4.59s/it]

 42%|████▏     | 1523/3599 [2:39:30<2:44:30,  4.75s/it]

 42%|████▏     | 1524/3599 [2:39:36<2:54:54,  5.06s/it]

 42%|████▏     | 1525/3599 [2:39:42<3:06:21,  5.39s/it]

 42%|████▏     | 1526/3599 [2:39:47<3:07:37,  5.43s/it]

 42%|████▏     | 1527/3599 [2:39:55<3:32:31,  6.15s/it]

 42%|████▏     | 1528/3599 [2:39:59<3:11:00,  5.53s/it]

 42%|████▏     | 1529/3599 [2:40:05<3:13:49,  5.62s/it]

 43%|████▎     | 1530/3599 [2:40:10<3:06:55,  5.42s/it]

 43%|████▎     | 1531/3599 [2:40:15<3:05:43,  5.39s/it]

 43%|████▎     | 1532/3599 [2:40:23<3:28:35,  6.05s/it]

[download]  63.9% of   10.77MiB at  997.08KiB/s ETA 00:03

[download] Got error: HTTPSConnectionPool(host='rr3---sn-4g5e6ns6.googlevideo.com', port=443): Read timed out.
 43%|████▎     | 1533/3599 [3:49:37<717:41:28, 1250.58s/it]

[download]  37.0% of   63.10MiB at    4.32MiB/s ETA 00:09

[download] Got error: 5982043 bytes read, 3983611 more expected
 43%|████▎     | 1534/3599 [6:43:28<2296:59:52, 4004.45s/it]

 43%|████▎     | 1535/3599 [6:43:36<1608:38:00, 2805.76s/it]

[download]  18.8% of   21.26MiB at    1.56MiB/s ETA 00:11

[download] Got error: HTTPSConnectionPool(host='rr1---sn-3c27sn7l.googlevideo.com', port=443): Read timed out.
 43%|████▎     | 1536/3599 [8:45:30<2382:54:23, 4158.25s/it]

[download] Got error: HTTP Error 500: Internal Server Error]ERROR:
 43%|████▎     | 1538/3599 [8:45:40<1167:50:25, 2039.90s/it]ERROR: [youtube] Ge1u1DOgeHo: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 43%|████▎     | 1539/3599 [8:45:40<817:11:42, 1428.11s/it]

[download]   9.3% of   21.42MiB at    1.87MiB/s ETA 00:10

[download] Got error: HTTPSConnectionPool(host='rr10---sn-3c27sne7.googlevideo.com', port=443): Read timed out.
 43%|████▎     | 1540/3599 [9:46:47<1200:58:15, 2099.80s/it]

 43%|████▎     | 1541/3599 [10:21:46<1200:11:54, 2099.47s/it]ERROR: [youtube] Gj2JlDcJ51g: Video unavailable
 43%|████▎     | 1542/3599 [10:21:47<839:50:11, 1469.82s/it] ERROR: [youtube] GjIFrmfEGWw: Video unavailable
 43%|████▎     | 1543/3599 [10:21:47<587:41:18, 1029.03s/it]ERROR: [youtube] GjhwpbMYj3k: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 43%|████▎     | 1544/3599 [10:21:48<411:16:22, 720.48s/it] ERROR: [youtube] GlAH_A9k_PA: Video unavailable
 43%|████▎     | 1545/3599 [10:21:48<287:50:28, 504.49s/it]

 43%|████▎     | 1546/3599 [10:21:55<202:36:19, 355.27s/it]

[download]  63.0% of   78.92MiB at    4.47MiB/s ETA 00:06

[download] Got error: HTTPSConnectionPool(host='rr4---sn-4g5ednre.googlevideo.com', port=443): Read timed out.
[download] Got error: HTTPSConnectionPool(host='rr2---sn-8vq54vox03g-afve.googlevideo.com', port=443): Read timed out. (read timeout=20.0)
 43%|████▎     | 1548/3599 [14:02:25<2129:03:39, 3737.02s/it]

 43%|████▎     | 1549/3599 [14:04:00<1505:43:42, 2644.21s/it]

[download]  27.7% of   50.15MiB at    4.71MiB/s ETA 00:07

[download] Got error: HTTPSConnectionPool(host='rr5---sn-4g5e6nsr.googlevideo.com', port=443): Read timed out.
 43%|████▎     | 1550/3599 [17:20:49<3069:54:12, 5393.68s/it]

 43%|████▎     | 1551/3599 [17:20:54<2148:42:49, 3777.04s/it]

 43%|████▎     | 1552/3599 [19:20:18<2725:30:46, 4793.28s/it]

 43%|████▎     | 1553/3599 [19:20:22<1907:31:59, 3356.36s/it]

 43%|████▎     | 1554/3599 [19:20:25<1335:13:18, 2350.51s/it]

 43%|████▎     | 1555/3599 [19:20:32<935:18:58, 1647.33s/it] ERROR: unable to download video data: HTTP Error 403: Forbidden
 43%|████▎     | 1556/3599 [19:20:33<654:36:24, 1153.49s/it]

 43%|████▎     | 1557/3599 [19:46:47<725:50:36, 1279.65s/it]

[download]  56.5% of   24.14MiB at    8.33MiB/s ETA 00:01

[download] Got error: 4234215 bytes read, 6162669 more expected
 43%|████▎     | 1558/3599 [21:15:16<1410:45:42, 2488.36s/it]ERROR: [youtube] H40OxsccelQ: Video unavailable
 43%|████▎     | 1559/3599 [21:15:16<987:08:21, 1742.01s/it]

 43%|████▎     | 1560/3599 [21:15:26<692:16:16, 1222.25s/it]

 43%|████▎     | 1561/3599 [21:15:32<485:19:59, 857.31s/it]

 43%|████▎     | 1562/3599 [21:15:39<340:51:02, 602.39s/it]

 43%|████▎     | 1563/3599 [21:15:43<239:05:36, 422.76s/it]

 43%|████▎     | 1564/3599 [21:47:46<493:26:15, 872.91s/it]ERROR: [youtube] HCz9FsQiX_A: Video unavailable. This video contains content from TOMATO1969. It is not available in your country.
 43%|████▎     | 1565/3599 [21:47:47<345:22:01, 611.27s/it]ERROR: [youtube] HDbHLTBDLx0: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 44%|████▎     | 1566/3599 [21:47:47<241:42:56, 428.03s/it]

 44%|████▎     | 1567/3599 [21:47:58<170:55:45, 302.83s/it]ERROR: [youtube] HEvhgrvbJh8: Video unavailable
 44%|████▎     | 1568/3599 [21:47:58<119:41:02, 212.14s/it]

 44%|████▎     | 1569/3599 [21:48:03<84:27:46, 149.79s/it]

[download]  22.5% of   52.88MiB at    8.87MiB/s ETA 00:04

[download] Got error: HTTPSConnectionPool(host='rr3---sn-8vq54vox03g-afve.googlevideo.com', port=443): Read timed out.
 44%|████▎     | 1570/3599 [25:51:25<2528:08:11, 4485.60s/it]

 44%|████▎     | 1571/3599 [25:51:42<1771:37:44, 3144.90s/it]

 44%|████▎     | 1572/3599 [25:51:46<1240:17:08, 2202.78s/it]

 44%|████▎     | 1573/3599 [25:51:51<868:34:18, 1543.37s/it]

[download]  60.5% of    6.61MiB at    5.69MiB/s ETA 00:00

[download] Got error: HTTPSConnectionPool(host='rr1---sn-4g5lznez.googlevideo.com', port=443): Read timed out.
 44%|████▎     | 1574/3599 [27:53:40<1840:59:59, 3272.89s/it]

[download] Got error: HTTPSConnectionPool(host='rr2---sn-8vq54vox03g-afve.googlevideo.com', port=443): Read timed out. (read timeout=20.0)
 44%|████▍     | 1575/3599 [28:54:37<1905:00:32, 3388.36s/it]

[download]   7.4% of  421.12KiB at  565.64KiB/s ETA 00:00

[download] Got error: HTTPSConnectionPool(host='rr5---sn-4g5lznez.googlevideo.com', port=443): Read timed out.
 44%|████▍     | 1576/3599 [30:56:23<2564:32:46, 4563.70s/it]ERROR: [youtube] HYDvHXhEt5w: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 44%|████▍     | 1577/3599 [30:56:25<1794:29:32, 3194.94s/it]

 44%|████▍     | 1578/3599 [30:56:30<1256:27:21, 2238.12s/it]

 44%|████▍     | 1579/3599 [30:56:43<881:13:43, 1570.51s/it]

 44%|████▍     | 1580/3599 [32:45:31<1714:56:09, 3057.84s/it]ERROR: [youtube] HZWNNMZ8zxY: This video has been removed for violating YouTube's Terms of Service
 44%|████▍     | 1581/3599 [32:45:32<1199:57:59, 2140.67s/it]

 44%|████▍     | 1582/3599 [32:45:42<841:13:18, 1501.44s/it]

 44%|████▍     | 1583/3599 [32:45:47<589:30:25, 1052.69s/it]

[download]   1.8% of  978.03MiB at    4.63MiB/s ETA 03:27

[download] Got error: HTTPSConnectionPool(host='rr2---sn-3c27sn7r.googlevideo.com', port=443): Read timed out.
 44%|████▍     | 1584/3599 [33:59:36<1156:10:32, 2065.62s/it]

[download]  35.3% of    5.67MiB at    3.63MiB/s ETA 00:01

[download] Got error: HTTPSConnectionPool(host='rr3---sn-4g5ednkz.googlevideo.com', port=443): Read timed out.
 44%|████▍     | 1585/3599 [35:00:26<1421:24:59, 2540.76s/it]

 44%|████▍     | 1586/3599 [35:00:31<995:20:21, 1780.04s/it]

 44%|████▍     | 1587/3599 [35:00:39<697:43:40, 1248.42s/it]

 44%|████▍     | 1588/3599 [37:02:28<1712:58:23, 3066.49s/it]

[download]  23.5% of   58.06MiB at    4.59MiB/s ETA 00:09

[download] Got error: 4653875 bytes read, 5603155 more expected
 44%|████▍     | 1589/3599 [38:03:22<1810:37:10, 3242.90s/it]ERROR: [youtube] Hj_F6t8XitM: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 44%|████▍     | 1590/3599 [38:03:23<1266:58:19, 2270.33s/it]

 44%|████▍     | 1591/3599 [38:03:30<887:31:07, 1591.17s/it] ERROR: [youtube] HkmQ-EPACQc: Video unavailable
 44%|████▍     | 1592/3599 [38:03:30<621:02:09, 1113.97s/it]

 44%|████▍     | 1593/3599 [39:01:50<1019:40:12, 1829.92s/it]

 44%|████▍     | 1594/3599 [41:57:39<2475:58:14, 4445.63s/it]

[download]  16.8% of  375.27KiB at    5.20MiB/s ETA 00:00

[download] Got error: HTTPSConnectionPool(host='rr2---sn-8vq54vox03g-afve.googlevideo.com', port=443): Read timed out.
 44%|████▍     | 1595/3599 [43:58:25<2942:15:13, 5285.49s/it]

 44%|████▍     | 1596/3599 [43:58:29<2059:19:27, 3701.23s/it]

 44%|████▍     | 1597/3599 [43:58:38<1442:13:10, 2593.40s/it]

 44%|████▍     | 1598/3599 [44:59:40<1619:39:50, 2913.94s/it]ERROR: [youtube] HsShknbuIK4: Requested format is not available. Use --list-formats for a list of available formats
 44%|████▍     | 1599/3599 [46:00:26<1740:58:00, 3133.74s/it]ERROR: [youtube] Hsa5i8HhGaM: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR: [youtube] HsssV4KdITk: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
 44%|████▍     | 1601/3599 [46:00:26<936:31:28, 1687.43s/it] ERROR: [youtube] Ht0eiaWhATE: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR: [youtube] Hw5YHMpAFB8: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
 45%|████▍     | 1603/3599 [46:00:26<563:50:37, 1016.95s/it]ERROR: [youtube] HyQ3xt8LU2Y: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR: [youtube] HzCkNtnL0B0: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
 45%|████▍     | 1605/3599 [46:00:27<359:19:38, 648.74s/it] ERROR: [youtube] I4as-Z8JbXk: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR: [youtube] I4gPpHlwhWg: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
 45%|████▍     | 1607/3599 [46:00:27<236:35:44, 427.58s/it]ERROR: [youtube] I6_Jz8e0K7s: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR: [youtube] I9DM2EBBuQ4: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
 45%|████▍     | 1609/3599 [46:00:27<158:57:20, 287.56s/it]ERROR: [youtube] IB7K2NL97Zw: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR: [youtube] IFLkLYj2Rlg: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
 45%|████▍     | 1611/3599 [46:00:27<108:11:23, 195.92s/it]ERROR: [youtube] IG0FPMcURIw: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR: [youtube] IIpGeLlMfj4: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
 45%|████▍     | 1613/3599 [46:00:27<74:16:26, 134.64s/it] ERROR: [youtube] IJRtkMihqgQ: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR: [youtube] IJtLxh3lMKA: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
 45%|████▍     | 1615/3599 [46:00:27<51:17:18, 93.06s/it] ERROR: [youtube] IMdLanfYWmM: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR: [youtube] IN_sIxaaRsY: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
 45%|████▍     | 1617/3599 [46:00:27<35:33:33, 64.59s/it]ERROR: [youtube] IQ_mQin_vH0: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR: [youtube] IQr4QzJ2t7c: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
 45%|████▍     | 1619/3599 [46:00:27<24:43:24, 44.95s/it]ERROR: [youtube] IRadvOo2680: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR: [youtube] ITaqvzpNW88: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
 45%|████▌     | 1621/3599 [46:00:27<17:13:28, 31.35s/it]ERROR: [youtube] IUqUmLMHcmI: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR: [youtube] IYrOC6TEw2o: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
 45%|████▌     | 1623/3599 [46:00:28<12:01:07, 21.90s/it]ERROR: [youtube] IZ_vm9x9uvo: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR: [youtube] I_tDt5W2x2Y: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
 45%|████▌     | 1625/3599 [46:00:28<8:23:48, 15.31s/it] ERROR: [youtube] Ib65n55TEMs: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR: [youtube] IfShh9nos4s: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
 45%|████▌     | 1627/3599 [46:00:28<5:52:23, 10.72s/it]ERROR: [youtube] If_kLmrKz-Q: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR: [youtube] IjhlkNmYNoo: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
 45%|████▌     | 1629/3599 [46:00:28<4:06:45,  7.52s/it]ERROR: [youtube] InzMxF1T__8: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR: [youtube] IwdgCPMRCBk: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
 45%|████▌     | 1631/3599 [46:00:28<2:53:01,  5.28s/it]ERROR: [youtube] IyBazGaHPeo: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR: [youtube] J-4vV4YQcl8: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
 45%|████▌     | 1633/3599 [46:00:28<2:01:32,  3.71s/it]ERROR: [youtube] J04XOgiFb7Q: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR: [youtube] J07ctCGSmM4: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
 45%|████▌     | 1635/3599 [46:00:28<1:25:34,  2.61s/it]ERROR: [youtube] J0Z2aNJs8Xw: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR: [youtube] J0kaliuNSiA: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
 45%|████▌     | 1637/3599 [46:00:28<1:00:27,  1.85s/it]ERROR: [youtube] J1ieQAzOGmc: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR: [youtube] J2Z5_PM83mg: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
 46%|████▌     | 1639/3599 [46:00:29<42:53,  1.31s/it]  ERROR: [youtube] J40El--OXFM: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR: [youtube] J46MfOrZLAk: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
 46%|████▌     | 1641/3599 [46:00:29<30:38,  1.06it/s]ERROR: [youtube] J4Rp6bhwwpw: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR: [youtube] J4vZDJJJ9HU: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
 46%|████▌     | 1643/3599 [46:00:29<22:05,  1.48it/s]ERROR: [youtube] J6tmXY_K7AI: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR: [youtube] J7-1pSO0ETE: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
 46%|████▌     | 1645/3599 [46:00:29<16:07,  2.02it/s]ERROR: [youtube] J77N8Fd5Plc: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR: [youtube] J8QcH3dqOYI: Unable to download API page: HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known) (caused by TransportError("HTTPSConnection(host='www.youtube.com', port=443): Failed to resolve 'www.youtube.com' ([Errno 8] nodename nor servname provided, or not known)"))

 61%|██████    | 2183/3599 [48:47:30<51:06,  2.17s/it]

[download]  25.4% of   68.95MiB at    3.64MiB/s ETA 00:14

[download] Got error: HTTPSConnectionPool(host='rr2---sn-8vq54vox03g-afve.googlevideo.com', port=443): Read timed out.
 61%|██████    | 2184/3599 [48:52:36<21:59:24, 55.95s/it]

 61%|██████    | 2185/3599 [48:52:43<18:01:43, 45.90s/it]

 61%|██████    | 2186/3599 [48:52:49<14:31:26, 37.00s/it]

 61%|██████    | 2187/3599 [48:52:53<11:23:07, 29.03s/it]ERROR: [youtube] V9cjrhBTdUw: This video has been removed for violating YouTube's policy on nudity or sexual content
 61%|██████    | 2188/3599 [48:52:53<8:30:36, 21.71s/it]

 61%|██████    | 2189/3599 [48:52:59<6:50:08, 17.45s/it]ERROR: [youtube] VB03y7gaVx8: Video unavailable
 61%|██████    | 2190/3599 [48:53:00<4:59:49, 12.77s/it]

 61%|██████    | 2191/3599 [48:53:03<3:58:11, 10.15s/it]

 61%|██████    | 2192/3599 [48:53:31<5:58:31, 15.29s/it]

 61%|██████    | 2193/3599 [48:53:35<4:43:40, 12.11s/it]

 61%|██████    | 2194/3599 [48:53:42<4:01:43, 10.32s/it]ERROR: unable to download video data: HTTP Error 403: Forbidden
 61%|██████    | 2195/3599 [48:53:43<3:02:15,  7.79s/it]

 61%|██████    | 2196/3599 [48:53:53<3:15:49,  8.37s/it]ERROR: [youtube] VMFE-ZJjXJc: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 61%|██████    | 2197/3599 [48:53:54<2:21:32,  6.06s/it]ERROR: [youtube] VOBsIJpi3P8: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 61%|██████    | 2198/3599 [48:53:54<1:43:34,  4.44s/it]

 61%|██████    | 2199/3599 [48:53:59<1:46:44,  4.57s/it]

 61%|██████    | 2200/3599 [48:54:07<2:07:30,  5.47s/it]

 61%|██████    | 2201/3599 [48:54:19<2:57:40,  7.63s/it]

 61%|██████    | 2202/3599 [48:54:27<2:55:42,  7.55s/it]ERROR: [youtube] VV1xS9u1ayU: Video unavailable
 61%|██████    | 2203/3599 [48:54:27<2:06:54,  5.45s/it]

 61%|██████    | 2204/3599 [48:54:32<2:02:50,  5.28s/it]

 61%|██████▏   | 2205/3599 [48:54:39<2:10:00,  5.60s/it]

 61%|██████▏   | 2206/3599 [48:54:46<2:19:53,  6.03s/it]

 61%|██████▏   | 2207/3599 [48:54:51<2:15:49,  5.85s/it]

 61%|██████▏   | 2208/3599 [48:54:57<2:13:31,  5.76s/it]

 61%|██████▏   | 2209/3599 [48:55:04<2:23:52,  6.21s/it]

 61%|██████▏   | 2210/3599 [48:55:10<2:26:13,  6.32s/it]

 61%|██████▏   | 2211/3599 [48:55:27<3:39:48,  9.50s/it]

 61%|██████▏   | 2212/3599 [48:55:48<4:55:11, 12.77s/it]

 61%|██████▏   | 2213/3599 [48:55:54<4:11:22, 10.88s/it]

 62%|██████▏   | 2214/3599 [48:56:01<3:45:40,  9.78s/it]

 62%|██████▏   | 2215/3599 [48:56:19<4:40:46, 12.17s/it]

 62%|██████▏   | 2216/3599 [48:56:24<3:53:20, 10.12s/it]

 62%|██████▏   | 2217/3599 [48:56:34<3:46:19,  9.83s/it]

 62%|██████▏   | 2218/3599 [48:56:38<3:08:50,  8.20s/it]

 62%|██████▏   | 2219/3599 [48:56:49<3:25:48,  8.95s/it]

 62%|██████▏   | 2220/3599 [48:56:58<3:31:11,  9.19s/it]ERROR: [youtube] Vsw3n0QU_9w: Video unavailable
 62%|██████▏   | 2221/3599 [48:56:59<2:32:45,  6.65s/it]ERROR: [youtube] Vu0EQwXV3J0: Video unavailable
 62%|██████▏   | 2222/3599 [48:57:00<1:55:45,  5.04s/it]

 62%|██████▏   | 2223/3599 [48:57:05<1:53:07,  4.93s/it]

 62%|██████▏   | 2224/3599 [48:57:10<1:53:32,  4.95s/it]

 62%|██████▏   | 2225/3599 [48:57:21<2:33:09,  6.69s/it]

 62%|██████▏   | 2226/3599 [48:57:28<2:38:07,  6.91s/it]

 62%|██████▏   | 2227/3599 [48:57:36<2:41:13,  7.05s/it]

 62%|██████▏   | 2228/3599 [48:57:42<2:33:05,  6.70s/it]ERROR: [youtube] VyCNWy2t4tk: Video unavailable. This video contains content from Dreamworks Animation, who has blocked it on copyright grounds
 62%|██████▏   | 2229/3599 [48:57:42<1:53:03,  4.95s/it]

 62%|██████▏   | 2230/3599 [48:57:51<2:17:11,  6.01s/it]

 62%|██████▏   | 2231/3599 [48:57:58<2:24:29,  6.34s/it]ERROR: [youtube] W-HSA1Uf7fY: Video unavailable
 62%|██████▏   | 2232/3599 [48:57:59<1:44:56,  4.61s/it]

[download]   5.0% of   39.70MiB at    2.80MiB/s ETA 00:13

[download] Got error: 2097136 bytes read, 7937430 more expected
[download] Got error: HTTP Error 500: Internal Server ErrorOR:
 62%|██████▏   | 2234/3599 [48:58:26<3:28:19,  9.16s/it]ERROR: [youtube] W5mzgd6pVH8: This video has been removed for violating YouTube's policy on violent or graphic content
 62%|██████▏   | 2235/3599 [48:58:26<2:30:53,  6.64s/it]

 62%|██████▏   | 2236/3599 [48:58:36<2:48:15,  7.41s/it]

 62%|██████▏   | 2237/3599 [48:58:50<3:35:46,  9.51s/it]

 62%|██████▏   | 2238/3599 [48:58:57<3:16:38,  8.67s/it]ERROR: [youtube] WBj3newOQDI: This video has been removed for violating YouTube's policy on violent or graphic content
 62%|██████▏   | 2239/3599 [48:58:57<2:21:09,  6.23s/it]

 62%|██████▏   | 2240/3599 [48:59:05<2:32:19,  6.73s/it]ERROR: [youtube] WCHRrvSHiv8: Video unavailable
 62%|██████▏   | 2241/3599 [48:59:06<1:50:59,  4.90s/it]

 62%|██████▏   | 2242/3599 [48:59:13<2:07:30,  5.64s/it]

 62%|██████▏   | 2243/3599 [48:59:46<5:13:27, 13.87s/it]ERROR: [youtube] WIsdD6To5MM: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 62%|██████▏   | 2244/3599 [48:59:47<3:43:14,  9.89s/it]

ERROR: unable to download video data: HTTP Error 403: Forbidden
 62%|██████▏   | 2245/3599 [48:59:54<3:22:40,  8.98s/it]

 62%|██████▏   | 2246/3599 [49:00:02<3:18:07,  8.79s/it]

 62%|██████▏   | 2247/3599 [49:00:06<2:49:13,  7.51s/it]

 62%|██████▏   | 2248/3599 [49:00:14<2:51:26,  7.61s/it]

 62%|██████▏   | 2249/3599 [49:01:28<10:17:56, 27.46s/it]

 63%|██████▎   | 2250/3599 [49:01:32<7:38:21, 20.39s/it]

 63%|██████▎   | 2251/3599 [49:01:39<6:07:07, 16.34s/it]ERROR: [youtube] WUzcgFzCi-k: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 63%|██████▎   | 2252/3599 [49:01:39<4:20:23, 11.60s/it]

 63%|██████▎   | 2253/3599 [49:01:52<4:29:41, 12.02s/it]

 63%|██████▎   | 2254/3599 [49:02:02<4:11:17, 11.21s/it]

 63%|██████▎   | 2255/3599 [49:02:08<3:40:12,  9.83s/it]

 63%|██████▎   | 2256/3599 [49:02:20<3:49:30, 10.25s/it]

 63%|██████▎   | 2257/3599 [49:02:26<3:21:09,  8.99s/it]ERROR: [youtube] Wd4O-trb4hc: Video unavailable
 63%|██████▎   | 2258/3599 [49:02:26<2:24:45,  6.48s/it]

 63%|██████▎   | 2259/3599 [49:02:30<2:08:36,  5.76s/it]

 63%|██████▎   | 2260/3599 [49:02:36<2:06:49,  5.68s/it]

 63%|██████▎   | 2261/3599 [49:02:57<3:49:31, 10.29s/it]

 63%|██████▎   | 2262/3599 [49:03:02<3:16:41,  8.83s/it]ERROR: [youtube] Wl3OM-FOYYI: This video has been removed for violating YouTube's policy on violent or graphic content
 63%|██████▎   | 2263/3599 [49:03:03<2:21:21,  6.35s/it]ERROR: [youtube] WmgcBU_cPh4: Video unavailable
 63%|██████▎   | 2264/3599 [49:03:03<1:42:36,  4.61s/it]

 63%|██████▎   | 2265/3599 [49:03:21<3:09:52,  8.54s/it]ERROR: [youtube] Wny4DyZeuMA: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 63%|██████▎   | 2266/3599 [49:03:22<2:16:11,  6.13s/it]

 63%|██████▎   | 2267/3599 [49:03:28<2:18:34,  6.24s/it]

 63%|██████▎   | 2268/3599 [49:03:35<2:19:46,  6.30s/it]

 63%|██████▎   | 2269/3599 [49:04:03<4:46:41, 12.93s/it]

 63%|██████▎   | 2270/3599 [49:04:14<4:31:53, 12.27s/it]

 63%|██████▎   | 2271/3599 [49:04:19<3:46:44, 10.24s/it]

 63%|██████▎   | 2272/3599 [49:04:23<3:03:28,  8.30s/it]

 63%|██████▎   | 2273/3599 [49:04:36<3:37:51,  9.86s/it]

 63%|██████▎   | 2274/3599 [49:04:41<3:02:26,  8.26s/it]

 63%|██████▎   | 2275/3599 [49:04:52<3:22:19,  9.17s/it]

 63%|██████▎   | 2276/3599 [49:04:58<2:56:50,  8.02s/it]ERROR: [youtube] X48NY2DGHZo: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 63%|██████▎   | 2277/3599 [49:04:58<2:09:17,  5.87s/it]

 63%|██████▎   | 2278/3599 [49:05:04<2:08:31,  5.84s/it]ERROR: [youtube] X5HHIJiGI38: Video unavailable
 63%|██████▎   | 2279/3599 [49:05:05<1:33:44,  4.26s/it]

 63%|██████▎   | 2280/3599 [49:05:14<2:07:46,  5.81s/it]

 63%|██████▎   | 2281/3599 [49:05:22<2:23:05,  6.51s/it]

 63%|██████▎   | 2282/3599 [49:05:28<2:18:22,  6.30s/it]ERROR: [youtube] XEVCBvmbVuw: Video unavailable
 63%|██████▎   | 2283/3599 [49:05:29<1:43:11,  4.71s/it]

 63%|██████▎   | 2284/3599 [49:05:43<2:40:02,  7.30s/it]

 63%|██████▎   | 2285/3599 [49:05:48<2:26:31,  6.69s/it]

 64%|██████▎   | 2286/3599 [49:06:12<4:20:27, 11.90s/it]

 64%|██████▎   | 2287/3599 [49:06:17<3:36:37,  9.91s/it]ERROR: [youtube] XK_yX7Q6ClU: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 64%|██████▎   | 2288/3599 [49:06:18<2:35:00,  7.09s/it]

 64%|██████▎   | 2289/3599 [49:06:26<2:39:55,  7.32s/it]

 64%|██████▎   | 2290/3599 [49:06:31<2:28:04,  6.79s/it]

 64%|██████▎   | 2291/3599 [49:06:40<2:41:28,  7.41s/it]

 64%|██████▎   | 2292/3599 [49:06:45<2:23:42,  6.60s/it]ERROR: [youtube] XPeu6M-BNbI: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 64%|██████▎   | 2293/3599 [49:06:45<1:44:15,  4.79s/it]

 64%|██████▎   | 2294/3599 [49:06:51<1:52:48,  5.19s/it]

 64%|██████▍   | 2295/3599 [49:06:55<1:44:43,  4.82s/it]

 64%|██████▍   | 2296/3599 [49:07:23<4:16:32, 11.81s/it]

 64%|██████▍   | 2297/3599 [49:07:29<3:38:55, 10.09s/it]

 64%|██████▍   | 2298/3599 [49:07:36<3:13:35,  8.93s/it]

 64%|██████▍   | 2299/3599 [49:07:42<2:59:01,  8.26s/it]

 64%|██████▍   | 2300/3599 [49:07:48<2:42:12,  7.49s/it]

 64%|██████▍   | 2301/3599 [49:07:56<2:44:12,  7.59s/it]

 64%|██████▍   | 2302/3599 [49:08:02<2:32:25,  7.05s/it]

 64%|██████▍   | 2303/3599 [49:08:07<2:19:51,  6.47s/it]

 64%|██████▍   | 2304/3599 [49:08:13<2:14:56,  6.25s/it]

 64%|██████▍   | 2305/3599 [49:08:18<2:09:21,  6.00s/it]

 64%|██████▍   | 2306/3599 [49:08:35<3:21:58,  9.37s/it]

 64%|██████▍   | 2307/3599 [49:08:41<2:55:29,  8.15s/it]

 64%|██████▍   | 2308/3599 [49:08:56<3:44:35, 10.44s/it]

 64%|██████▍   | 2309/3599 [49:08:59<2:57:33,  8.26s/it]

 64%|██████▍   | 2310/3599 [49:09:21<4:24:47, 12.33s/it]ERROR: [youtube] Xouhayu-IHM: Video unavailable
 64%|██████▍   | 2311/3599 [49:09:22<3:09:03,  8.81s/it]

 64%|██████▍   | 2312/3599 [49:09:29<2:55:06,  8.16s/it]ERROR: [youtube] Xpzf_KB2kSU: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 64%|██████▍   | 2313/3599 [49:09:29<2:06:05,  5.88s/it]

 64%|██████▍   | 2314/3599 [49:09:36<2:12:12,  6.17s/it]

 64%|██████▍   | 2315/3599 [49:09:43<2:18:40,  6.48s/it]

 64%|██████▍   | 2316/3599 [49:10:10<4:26:40, 12.47s/it]

 64%|██████▍   | 2317/3599 [49:10:13<3:30:27,  9.85s/it]

 64%|██████▍   | 2318/3599 [49:10:19<3:02:19,  8.54s/it]

 64%|██████▍   | 2319/3599 [49:10:23<2:33:51,  7.21s/it]

 64%|██████▍   | 2320/3599 [49:10:37<3:16:28,  9.22s/it]

 64%|██████▍   | 2321/3599 [49:10:43<2:59:12,  8.41s/it]ERROR: [youtube] Y3Kxv9FIioM: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 65%|██████▍   | 2322/3599 [49:10:44<2:08:38,  6.04s/it]

 65%|██████▍   | 2323/3599 [49:10:49<2:05:25,  5.90s/it]

 65%|██████▍   | 2324/3599 [49:10:55<2:01:21,  5.71s/it]

 65%|██████▍   | 2325/3599 [49:11:01<2:02:29,  5.77s/it]ERROR: [youtube] Y8JpnMk8-TA: Video unavailable
 65%|██████▍   | 2326/3599 [49:11:01<1:29:03,  4.20s/it]

 65%|██████▍   | 2327/3599 [49:11:12<2:12:17,  6.24s/it]

 65%|██████▍   | 2328/3599 [49:11:21<2:27:28,  6.96s/it]

 65%|██████▍   | 2329/3599 [49:11:25<2:10:09,  6.15s/it]

 65%|██████▍   | 2330/3599 [49:11:29<1:57:31,  5.56s/it]

 65%|██████▍   | 2331/3599 [49:11:40<2:32:54,  7.24s/it]ERROR: [youtube] YIuTBnSPP6I: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 65%|██████▍   | 2332/3599 [49:11:41<1:50:13,  5.22s/it]

 65%|██████▍   | 2333/3599 [49:11:49<2:09:14,  6.12s/it]ERROR: [youtube] YK1lbXvL_ak: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 65%|██████▍   | 2334/3599 [49:11:50<1:34:06,  4.46s/it]

 65%|██████▍   | 2335/3599 [49:11:57<1:49:49,  5.21s/it]ERROR: [youtube] YPP6CKqQ7Fk: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 65%|██████▍   | 2336/3599 [49:11:57<1:20:36,  3.83s/it]

 65%|██████▍   | 2337/3599 [49:12:04<1:35:58,  4.56s/it]

 65%|██████▍   | 2338/3599 [49:12:10<1:46:46,  5.08s/it]ERROR: [youtube] YTEA0-hzSqs: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 65%|██████▍   | 2339/3599 [49:12:11<1:18:57,  3.76s/it]

 65%|██████▌   | 2340/3599 [49:12:17<1:37:48,  4.66s/it]ERROR: [youtube] YWFfOxKE65o: Video unavailable
 65%|██████▌   | 2341/3599 [49:12:18<1:12:12,  3.44s/it]

 65%|██████▌   | 2342/3599 [49:12:33<2:22:34,  6.81s/it]

 65%|██████▌   | 2343/3599 [49:12:50<3:29:02,  9.99s/it]

 65%|██████▌   | 2344/3599 [49:12:56<3:03:13,  8.76s/it]

 65%|██████▌   | 2345/3599 [49:13:01<2:43:23,  7.82s/it]

 65%|██████▌   | 2346/3599 [49:13:17<3:34:23, 10.27s/it]ERROR: [youtube] YrQ-xLs_iHA: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 65%|██████▌   | 2347/3599 [49:13:18<2:33:06,  7.34s/it]

 65%|██████▌   | 2348/3599 [49:13:30<3:01:21,  8.70s/it]

 65%|██████▌   | 2349/3599 [49:13:34<2:32:51,  7.34s/it]

 65%|██████▌   | 2350/3599 [49:13:43<2:43:29,  7.85s/it]

 65%|██████▌   | 2351/3599 [49:13:49<2:30:49,  7.25s/it]

 65%|██████▌   | 2352/3599 [49:13:53<2:11:48,  6.34s/it]

 65%|██████▌   | 2353/3599 [49:14:00<2:14:37,  6.48s/it]

 65%|██████▌   | 2354/3599 [49:14:04<2:01:29,  5.85s/it]

 65%|██████▌   | 2355/3599 [49:14:10<1:59:52,  5.78s/it]

 65%|██████▌   | 2356/3599 [49:14:14<1:50:43,  5.34s/it]

 65%|██████▌   | 2357/3599 [49:14:20<1:51:14,  5.37s/it]ERROR: [youtube] ZEkrw9jwHVE: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 66%|██████▌   | 2358/3599 [49:14:20<1:22:02,  3.97s/it]

 66%|██████▌   | 2359/3599 [49:14:27<1:37:13,  4.70s/it]

 66%|██████▌   | 2360/3599 [49:14:34<1:52:55,  5.47s/it]

 66%|██████▌   | 2361/3599 [49:14:41<2:02:41,  5.95s/it]

 66%|██████▌   | 2362/3599 [49:14:56<2:58:24,  8.65s/it]

 66%|██████▌   | 2363/3599 [49:15:06<3:03:32,  8.91s/it]

 66%|██████▌   | 2364/3599 [49:15:13<2:54:48,  8.49s/it]

 66%|██████▌   | 2365/3599 [49:15:36<4:23:48, 12.83s/it]

 66%|██████▌   | 2366/3599 [49:16:05<6:03:55, 17.71s/it]

 66%|██████▌   | 2367/3599 [49:16:11<4:51:51, 14.21s/it]

 66%|██████▌   | 2368/3599 [49:16:16<3:50:47, 11.25s/it]

 66%|██████▌   | 2369/3599 [49:16:20<3:05:55,  9.07s/it]

 66%|██████▌   | 2370/3599 [49:16:26<2:46:56,  8.15s/it]

 66%|██████▌   | 2371/3599 [49:16:31<2:27:52,  7.23s/it]

 66%|██████▌   | 2372/3599 [49:16:37<2:25:27,  7.11s/it]

 66%|██████▌   | 2373/3599 [49:16:43<2:14:54,  6.60s/it]

 66%|██████▌   | 2374/3599 [49:16:48<2:07:20,  6.24s/it]

 66%|██████▌   | 2375/3599 [49:16:55<2:08:51,  6.32s/it]

ERROR: unable to download video data: HTTP Error 403: Forbidden
 66%|██████▌   | 2376/3599 [49:17:07<2:42:42,  7.98s/it]ERROR: [youtube] ZkU87Mn3qAU: Video unavailable
 66%|██████▌   | 2377/3599 [49:17:07<1:58:51,  5.84s/it]

 66%|██████▌   | 2378/3599 [49:17:13<1:55:08,  5.66s/it]

 66%|██████▌   | 2379/3599 [49:18:00<6:11:22, 18.26s/it]

 66%|██████▌   | 2380/3599 [49:18:06<4:53:43, 14.46s/it]

 66%|██████▌   | 2381/3599 [49:18:20<4:49:43, 14.27s/it]

 66%|██████▌   | 2382/3599 [49:18:32<4:39:06, 13.76s/it]

 66%|██████▌   | 2383/3599 [49:18:36<3:39:17, 10.82s/it]

 66%|██████▌   | 2384/3599 [49:18:41<3:00:32,  8.92s/it]

 66%|██████▋   | 2385/3599 [49:18:55<3:34:20, 10.59s/it]

 66%|██████▋   | 2386/3599 [49:19:08<3:48:11, 11.29s/it]

 66%|██████▋   | 2387/3599 [49:19:14<3:14:14,  9.62s/it]

 66%|██████▋   | 2388/3599 [49:19:19<2:48:10,  8.33s/it]ERROR: [youtube] ZtNAbdZCWjs: Video unavailable
 66%|██████▋   | 2389/3599 [49:19:20<2:01:55,  6.05s/it]

 66%|██████▋   | 2390/3599 [49:19:26<2:01:02,  6.01s/it]

 66%|██████▋   | 2391/3599 [49:19:31<1:54:03,  5.66s/it]

 66%|██████▋   | 2392/3599 [49:19:36<1:49:05,  5.42s/it]

 66%|██████▋   | 2393/3599 [49:19:40<1:41:46,  5.06s/it]

 67%|██████▋   | 2394/3599 [49:19:46<1:48:03,  5.38s/it]ERROR: [youtube] _1Wpd4sweuQ: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 67%|██████▋   | 2395/3599 [49:19:46<1:18:49,  3.93s/it]

 67%|██████▋   | 2396/3599 [49:19:54<1:41:03,  5.04s/it]

 67%|██████▋   | 2397/3599 [49:19:59<1:37:38,  4.87s/it]ERROR: [youtube] _3VwmvYT3Yk: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 67%|██████▋   | 2398/3599 [49:19:59<1:12:12,  3.61s/it]

 67%|██████▋   | 2399/3599 [49:20:07<1:35:32,  4.78s/it]

 67%|██████▋   | 2400/3599 [49:20:12<1:39:39,  4.99s/it]

 67%|██████▋   | 2401/3599 [49:20:17<1:35:51,  4.80s/it]

 67%|██████▋   | 2402/3599 [49:20:27<2:07:58,  6.41s/it]

 67%|██████▋   | 2403/3599 [49:20:31<1:53:45,  5.71s/it]

 67%|██████▋   | 2404/3599 [49:20:37<1:56:32,  5.85s/it]ERROR: [youtube] _B5lHcJ0aBg: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 67%|██████▋   | 2405/3599 [49:20:38<1:24:41,  4.26s/it]

 67%|██████▋   | 2406/3599 [49:20:48<1:58:51,  5.98s/it]ERROR: [youtube] _D-0WTSsc5w: Video unavailable. This video has been removed by the uploader
 67%|██████▋   | 2407/3599 [49:20:49<1:30:01,  4.53s/it]

 67%|██████▋   | 2408/3599 [49:20:55<1:40:15,  5.05s/it]

 67%|██████▋   | 2409/3599 [49:21:00<1:39:03,  4.99s/it]

 67%|██████▋   | 2410/3599 [49:21:05<1:42:27,  5.17s/it]

 67%|██████▋   | 2411/3599 [49:21:17<2:21:06,  7.13s/it]

 67%|██████▋   | 2412/3599 [49:21:24<2:17:11,  6.93s/it]

 67%|██████▋   | 2413/3599 [49:21:28<2:04:38,  6.31s/it]

 67%|██████▋   | 2414/3599 [49:21:32<1:50:07,  5.58s/it]

 67%|██████▋   | 2415/3599 [49:21:39<1:54:34,  5.81s/it]

 67%|██████▋   | 2416/3599 [49:21:45<1:57:01,  5.93s/it]

 67%|██████▋   | 2417/3599 [49:21:49<1:45:37,  5.36s/it]

 67%|██████▋   | 2418/3599 [49:21:53<1:39:33,  5.06s/it]

 67%|██████▋   | 2419/3599 [49:22:02<1:59:01,  6.05s/it]

 67%|██████▋   | 2420/3599 [49:22:07<1:54:48,  5.84s/it]

 67%|██████▋   | 2421/3599 [49:22:13<1:55:01,  5.86s/it]

 67%|██████▋   | 2422/3599 [49:22:31<3:08:54,  9.63s/it]

 67%|██████▋   | 2423/3599 [49:22:40<3:02:11,  9.30s/it]

 67%|██████▋   | 2424/3599 [49:22:47<2:47:08,  8.53s/it]

 67%|██████▋   | 2425/3599 [49:22:52<2:29:23,  7.64s/it]ERROR: [youtube] _YIbT_TETxo: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 67%|██████▋   | 2426/3599 [49:22:53<1:47:52,  5.52s/it]

 67%|██████▋   | 2427/3599 [49:23:00<1:59:20,  6.11s/it]

 67%|██████▋   | 2428/3599 [49:23:05<1:51:22,  5.71s/it]

 67%|██████▋   | 2429/3599 [49:23:08<1:38:32,  5.05s/it]

 68%|██████▊   | 2430/3599 [49:23:15<1:49:13,  5.61s/it]

 68%|██████▊   | 2431/3599 [49:23:23<1:59:38,  6.15s/it]

 68%|██████▊   | 2432/3599 [49:23:30<2:06:39,  6.51s/it]

 68%|██████▊   | 2433/3599 [49:23:35<1:54:55,  5.91s/it]

 68%|██████▊   | 2434/3599 [49:23:41<1:54:38,  5.90s/it]

 68%|██████▊   | 2435/3599 [49:23:47<1:56:21,  6.00s/it]

 68%|██████▊   | 2436/3599 [49:23:52<1:53:24,  5.85s/it]

 68%|██████▊   | 2437/3599 [49:23:57<1:44:02,  5.37s/it]

 68%|██████▊   | 2438/3599 [49:24:00<1:33:55,  4.85s/it]

 68%|██████▊   | 2439/3599 [49:24:26<3:35:50, 11.16s/it]

 68%|██████▊   | 2440/3599 [49:24:31<2:57:07,  9.17s/it]

 68%|██████▊   | 2441/3599 [49:24:35<2:29:35,  7.75s/it]

 68%|██████▊   | 2442/3599 [49:24:40<2:16:08,  7.06s/it]

 68%|██████▊   | 2443/3599 [49:24:47<2:11:20,  6.82s/it]

 68%|██████▊   | 2444/3599 [49:24:55<2:22:28,  7.40s/it]ERROR: [youtube] _zbVh5FM-wI: Video unavailable
 68%|██████▊   | 2445/3599 [49:24:56<1:42:33,  5.33s/it]

 68%|██████▊   | 2446/3599 [49:25:01<1:42:45,  5.35s/it]ERROR: [youtube] _zkcCBWuL3I: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 68%|██████▊   | 2447/3599 [49:25:02<1:15:14,  3.92s/it]

 68%|██████▊   | 2448/3599 [49:25:11<1:46:05,  5.53s/it]

 68%|██████▊   | 2449/3599 [49:25:20<2:06:35,  6.61s/it]ERROR: [youtube] a4qfT7lAf3Q: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 68%|██████▊   | 2450/3599 [49:25:21<1:31:36,  4.78s/it]

 68%|██████▊   | 2451/3599 [49:25:26<1:35:03,  4.97s/it]

 68%|██████▊   | 2452/3599 [49:25:32<1:38:29,  5.15s/it]

 68%|██████▊   | 2453/3599 [49:25:49<2:44:41,  8.62s/it]

 68%|██████▊   | 2454/3599 [49:25:56<2:35:28,  8.15s/it]

 68%|██████▊   | 2455/3599 [49:26:03<2:30:05,  7.87s/it]

 68%|██████▊   | 2456/3599 [49:26:24<3:47:07, 11.92s/it]ERROR: [youtube] aDhV48ZqfdA: Video unavailable
 68%|██████▊   | 2457/3599 [49:26:25<2:41:59,  8.51s/it]

 68%|██████▊   | 2458/3599 [49:26:31<2:28:00,  7.78s/it]

 68%|██████▊   | 2459/3599 [49:26:37<2:18:15,  7.28s/it]

 68%|██████▊   | 2460/3599 [49:26:45<2:24:26,  7.61s/it]

 68%|██████▊   | 2461/3599 [49:26:52<2:16:01,  7.17s/it]

ERROR: unable to download video data: HTTP Error 403: Forbidden
 68%|██████▊   | 2462/3599 [49:26:58<2:09:32,  6.84s/it]ERROR: [youtube] aMJ1L7Dbe3Q: Video unavailable
 68%|██████▊   | 2463/3599 [49:26:58<1:33:41,  4.95s/it]ERROR: [youtube] aOVqoLYZS-E: Video unavailable
 68%|██████▊   | 2464/3599 [49:26:59<1:09:00,  3.65s/it]

 68%|██████▊   | 2465/3599 [49:27:10<1:52:35,  5.96s/it]

 69%|██████▊   | 2466/3599 [49:27:14<1:39:28,  5.27s/it]

 69%|██████▊   | 2467/3599 [49:27:18<1:35:22,  5.06s/it]

 69%|██████▊   | 2468/3599 [49:27:26<1:52:16,  5.96s/it]

 69%|██████▊   | 2469/3599 [49:27:56<4:07:36, 13.15s/it]

 69%|██████▊   | 2470/3599 [49:28:00<3:13:46, 10.30s/it]

 69%|██████▊   | 2471/3599 [49:28:19<4:03:15, 12.94s/it]ERROR: [youtube] aaBkDgm_zKw: Video unavailable
 69%|██████▊   | 2472/3599 [49:28:20<2:53:31,  9.24s/it]

 69%|██████▊   | 2473/3599 [49:28:30<2:58:35,  9.52s/it]ERROR: [youtube] ab8teCSQkis: Video unavailable
 69%|██████▊   | 2474/3599 [49:28:30<2:08:34,  6.86s/it]

 69%|██████▉   | 2475/3599 [49:28:45<2:49:14,  9.03s/it]

 69%|██████▉   | 2476/3599 [49:28:50<2:30:25,  8.04s/it]

 69%|██████▉   | 2477/3599 [49:29:00<2:37:49,  8.44s/it]

 69%|██████▉   | 2478/3599 [49:29:10<2:46:03,  8.89s/it]

 69%|██████▉   | 2479/3599 [49:29:15<2:27:53,  7.92s/it]

 69%|██████▉   | 2480/3599 [49:29:23<2:26:54,  7.88s/it]

 69%|██████▉   | 2481/3599 [49:29:28<2:08:48,  6.91s/it]

 69%|██████▉   | 2482/3599 [49:29:36<2:18:10,  7.42s/it]

 69%|██████▉   | 2483/3599 [49:29:42<2:11:14,  7.06s/it]

 69%|██████▉   | 2484/3599 [49:29:48<2:01:53,  6.56s/it]ERROR: [youtube] akYv-1BVMT4: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 69%|██████▉   | 2485/3599 [49:29:48<1:28:24,  4.76s/it]

 69%|██████▉   | 2486/3599 [49:29:54<1:32:50,  5.00s/it]

 69%|██████▉   | 2487/3599 [49:30:03<1:57:17,  6.33s/it]ERROR: [youtube] an3cNcN_l4k: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 69%|██████▉   | 2488/3599 [49:30:04<1:25:32,  4.62s/it]

 69%|██████▉   | 2489/3599 [49:30:16<2:06:35,  6.84s/it]

 69%|██████▉   | 2490/3599 [49:30:26<2:22:41,  7.72s/it]

 69%|██████▉   | 2491/3599 [49:30:30<2:01:42,  6.59s/it]

 69%|██████▉   | 2492/3599 [49:30:55<3:43:58, 12.14s/it]

 69%|██████▉   | 2493/3599 [49:31:03<3:20:45, 10.89s/it]

 69%|██████▉   | 2494/3599 [49:31:09<2:54:55,  9.50s/it]

 69%|██████▉   | 2495/3599 [49:31:15<2:32:14,  8.27s/it]

 69%|██████▉   | 2496/3599 [49:31:21<2:19:27,  7.59s/it]

 69%|██████▉   | 2497/3599 [49:31:25<2:02:46,  6.68s/it]

 69%|██████▉   | 2498/3599 [49:31:30<1:50:06,  6.00s/it]

 69%|██████▉   | 2499/3599 [49:31:35<1:44:43,  5.71s/it]

 69%|██████▉   | 2500/3599 [49:31:40<1:45:45,  5.77s/it]

 69%|██████▉   | 2501/3599 [49:32:25<5:15:53, 17.26s/it]ERROR: [youtube] b7icrYVhiMk: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 70%|██████▉   | 2502/3599 [49:32:25<3:44:23, 12.27s/it]

 70%|██████▉   | 2503/3599 [49:32:35<3:33:16, 11.68s/it]ERROR: [youtube] bAlnbxh9NKI: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 70%|██████▉   | 2504/3599 [49:32:36<2:32:18,  8.35s/it]

 70%|██████▉   | 2505/3599 [49:32:41<2:11:00,  7.18s/it]

 70%|██████▉   | 2506/3599 [49:33:10<4:11:40, 13.82s/it]

 70%|██████▉   | 2507/3599 [49:33:14<3:17:33, 10.86s/it]

 70%|██████▉   | 2508/3599 [49:33:26<3:23:18, 11.18s/it]ERROR: [youtube] bEpHMdr9LF0: Video unavailable
 70%|██████▉   | 2509/3599 [49:33:26<2:25:22,  8.00s/it]

 70%|██████▉   | 2510/3599 [49:33:30<2:03:47,  6.82s/it]

 70%|██████▉   | 2511/3599 [49:34:32<7:04:00, 23.38s/it]

ERROR: unable to download video data: HTTP Error 403: Forbidden
 70%|██████▉   | 2512/3599 [49:34:39<5:31:00, 18.27s/it]

 70%|██████▉   | 2513/3599 [49:34:42<4:10:53, 13.86s/it]

 70%|██████▉   | 2514/3599 [49:34:59<4:23:40, 14.58s/it]

 70%|██████▉   | 2515/3599 [49:35:04<3:35:38, 11.94s/it]ERROR: [youtube] bOtXf9klg_c: Video unavailable
 70%|██████▉   | 2516/3599 [49:35:05<2:33:55,  8.53s/it]

 70%|██████▉   | 2517/3599 [49:35:10<2:16:02,  7.54s/it]

 70%|██████▉   | 2518/3599 [49:35:17<2:10:23,  7.24s/it]ERROR: [youtube] bUyY1Q6OXiA: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 70%|██████▉   | 2519/3599 [49:35:17<1:34:41,  5.26s/it]

 70%|███████   | 2520/3599 [49:35:43<3:27:02, 11.51s/it]

 70%|███████   | 2521/3599 [49:35:58<3:43:27, 12.44s/it]

 70%|███████   | 2522/3599 [49:36:02<2:57:51,  9.91s/it]

 70%|███████   | 2523/3599 [49:36:12<3:00:06, 10.04s/it]

 70%|███████   | 2524/3599 [49:36:21<2:54:31,  9.74s/it]

 70%|███████   | 2525/3599 [49:36:35<3:16:28, 10.98s/it]

 70%|███████   | 2526/3599 [49:36:40<2:42:38,  9.09s/it]

 70%|███████   | 2527/3599 [49:36:46<2:23:53,  8.05s/it]

 70%|███████   | 2528/3599 [49:36:54<2:25:23,  8.15s/it]

 70%|███████   | 2529/3599 [49:37:02<2:24:43,  8.12s/it]

 70%|███████   | 2530/3599 [49:37:06<2:00:41,  6.77s/it]ERROR: [youtube] bgsB0fkXIYQ: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 70%|███████   | 2531/3599 [49:37:06<1:27:44,  4.93s/it]

 70%|███████   | 2532/3599 [49:37:22<2:27:31,  8.30s/it]

 70%|███████   | 2533/3599 [49:37:26<2:04:01,  6.98s/it]ERROR: [youtube] blYGoqISklo: Video unavailable
[download] Got error: HTTP Error 500: Internal Server ErrorOR:
 70%|███████   | 2535/3599 [49:37:47<2:50:20,  9.61s/it]

[download]  14.6% of   67.69MiB at    5.96MiB/s ETA 00:09

ERROR: unable to download video data: HTTP Error 403: Forbidden
 70%|███████   | 2536/3599 [49:37:51<2:19:48,  7.89s/it]

 70%|███████   | 2537/3599 [49:37:55<1:57:55,  6.66s/it]

 71%|███████   | 2538/3599 [49:38:01<1:55:58,  6.56s/it]

 71%|███████   | 2539/3599 [49:38:09<2:01:00,  6.85s/it]

 71%|███████   | 2540/3599 [49:38:55<5:31:05, 18.76s/it]

 71%|███████   | 2541/3599 [49:38:59<4:13:59, 14.40s/it]ERROR: [youtube] bzXQrIPD2Iw: Video unavailable
 71%|███████   | 2542/3599 [49:39:00<3:00:54, 10.27s/it]ERROR: [youtube] c0LU-woKhsw: This video has been removed for violating YouTube's policy on violent or graphic content
 71%|███████   | 2543/3599 [49:39:01<2:09:20,  7.35s/it]

 71%|███████   | 2544/3599 [49:39:05<1:54:54,  6.54s/it]

 71%|███████   | 2545/3599 [49:39:53<5:34:03, 19.02s/it]

 71%|███████   | 2546/3599 [49:40:01<4:33:37, 15.59s/it]

 71%|███████   | 2547/3599 [49:40:15<4:24:10, 15.07s/it]

 71%|███████   | 2548/3599 [49:40:24<3:52:09, 13.25s/it]

 71%|███████   | 2549/3599 [49:40:30<3:14:52, 11.14s/it]ERROR: [youtube] c8K7QTnrldI: Video unavailable
 71%|███████   | 2550/3599 [49:40:31<2:19:07,  7.96s/it]ERROR: [youtube] c9f1MvUsOFs: Video unavailable. This video contains content from ThePowerHDTV. It is not available in your country.
 71%|███████   | 2551/3599 [49:40:32<1:42:26,  5.86s/it]

 71%|███████   | 2552/3599 [49:43:30<16:43:32, 57.51s/it]ERROR: [youtube] cFRGfoYhZSg: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 71%|███████   | 2553/3599 [49:43:31<11:47:02, 40.56s/it]

 71%|███████   | 2554/3599 [49:45:02<16:14:14, 55.94s/it]

 71%|███████   | 2555/3599 [49:45:29<13:38:58, 47.07s/it]

 71%|███████   | 2556/3599 [49:45:33<9:57:24, 34.37s/it]

 71%|███████   | 2557/3599 [49:45:53<8:41:44, 30.04s/it]

 71%|███████   | 2558/3599 [49:46:00<6:38:12, 22.95s/it]

 71%|███████   | 2559/3599 [49:46:15<5:56:21, 20.56s/it]

 71%|███████   | 2560/3599 [49:51:15<30:08:07, 104.42s/it]

ERROR: unable to download video data: HTTP Error 403: Forbidden
 71%|███████   | 2561/3599 [49:51:54<24:25:24, 84.71s/it]

 71%|███████   | 2562/3599 [49:51:58<17:28:56, 60.69s/it]

 71%|███████   | 2563/3599 [49:52:12<13:24:53, 46.62s/it]

 71%|███████   | 2564/3599 [49:52:24<10:26:56, 36.34s/it]

 71%|███████▏  | 2565/3599 [49:52:29<7:43:47, 26.91s/it]

 71%|███████▏  | 2566/3599 [49:52:37<6:03:02, 21.09s/it]

 71%|███████▏  | 2567/3599 [49:52:47<5:08:29, 17.94s/it]

 71%|███████▏  | 2568/3599 [49:52:51<3:55:25, 13.70s/it]

 71%|███████▏  | 2569/3599 [49:52:56<3:08:31, 10.98s/it]

 71%|███████▏  | 2570/3599 [49:54:42<11:16:41, 39.46s/it]

 71%|███████▏  | 2571/3599 [49:54:53<8:52:32, 31.08s/it]

 71%|███████▏  | 2572/3599 [49:55:00<6:48:15, 23.85s/it]

 71%|███████▏  | 2573/3599 [49:55:04<5:06:57, 17.95s/it]

 72%|███████▏  | 2574/3599 [49:55:09<3:58:05, 13.94s/it]

 72%|███████▏  | 2575/3599 [49:55:16<3:22:25, 11.86s/it]

 72%|███████▏  | 2576/3599 [49:55:23<2:59:12, 10.51s/it]

 72%|███████▏  | 2577/3599 [49:55:29<2:34:33,  9.07s/it]

 72%|███████▏  | 2578/3599 [49:55:36<2:20:44,  8.27s/it]

 72%|███████▏  | 2579/3599 [49:55:40<2:02:42,  7.22s/it]ERROR: [youtube] cp2Pz-FKeEA: Video unavailable
 72%|███████▏  | 2580/3599 [49:55:41<1:28:38,  5.22s/it]

 72%|███████▏  | 2581/3599 [49:55:47<1:33:58,  5.54s/it]ERROR: [youtube] cqCy6O8Mibo: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 72%|███████▏  | 2582/3599 [49:55:48<1:08:27,  4.04s/it]

 72%|███████▏  | 2583/3599 [49:55:55<1:26:45,  5.12s/it]

 72%|███████▏  | 2584/3599 [49:56:16<2:47:51,  9.92s/it]ERROR: [youtube] cuPcf5kWLmE: Video unavailable
 72%|███████▏  | 2585/3599 [49:56:17<2:00:09,  7.11s/it]

 72%|███████▏  | 2586/3599 [49:56:23<1:54:58,  6.81s/it]

 72%|███████▏  | 2587/3599 [49:56:27<1:41:36,  6.02s/it]

 72%|███████▏  | 2588/3599 [49:56:31<1:30:34,  5.38s/it]ERROR: [youtube] cyxb5bS8NDk: Video unavailable
 72%|███████▏  | 2589/3599 [49:56:32<1:06:03,  3.92s/it]ERROR: [youtube] d43Cy3Iaf3s: This video has been removed for violating YouTube's policy on violent or graphic content
 72%|███████▏  | 2590/3599 [49:56:32<49:06,  2.92s/it]

 72%|███████▏  | 2591/3599 [49:56:43<1:27:04,  5.18s/it]ERROR: [youtube] d6CsjCMyCqM: Video unavailable
 72%|███████▏  | 2592/3599 [49:56:43<1:03:50,  3.80s/it]

 72%|███████▏  | 2593/3599 [49:57:01<2:13:30,  7.96s/it]

 72%|███████▏  | 2594/3599 [49:57:06<1:56:06,  6.93s/it]

 72%|███████▏  | 2595/3599 [49:57:14<2:05:17,  7.49s/it]ERROR: [youtube] dA8oR5IgaT4: Video unavailable
 72%|███████▏  | 2596/3599 [49:57:15<1:30:12,  5.40s/it]

 72%|███████▏  | 2597/3599 [49:57:20<1:27:46,  5.26s/it]

 72%|███████▏  | 2598/3599 [49:57:24<1:20:39,  4.83s/it]

 72%|███████▏  | 2599/3599 [49:57:30<1:28:17,  5.30s/it]

 72%|███████▏  | 2600/3599 [49:57:34<1:21:23,  4.89s/it]

 72%|███████▏  | 2601/3599 [49:57:40<1:29:37,  5.39s/it]

 72%|███████▏  | 2602/3599 [49:57:48<1:38:01,  5.90s/it]

 72%|███████▏  | 2603/3599 [49:57:52<1:32:54,  5.60s/it]

 72%|███████▏  | 2604/3599 [49:57:57<1:25:22,  5.15s/it]

 72%|███████▏  | 2605/3599 [49:58:01<1:22:52,  5.00s/it]

 72%|███████▏  | 2606/3599 [49:58:06<1:21:47,  4.94s/it]

 72%|███████▏  | 2607/3599 [49:58:14<1:34:44,  5.73s/it]ERROR: [youtube] dXcWD1udOxs: Video unavailable
 72%|███████▏  | 2608/3599 [49:58:14<1:08:56,  4.17s/it]

 72%|███████▏  | 2609/3599 [49:58:21<1:24:10,  5.10s/it]

 73%|███████▎  | 2610/3599 [49:58:28<1:32:58,  5.64s/it]ERROR: [youtube] deaCxapFE7Q: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 73%|███████▎  | 2611/3599 [49:58:29<1:07:37,  4.11s/it]

 73%|███████▎  | 2612/3599 [49:58:33<1:09:25,  4.22s/it]ERROR: [youtube] dj_03QcBtWM: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 73%|███████▎  | 2613/3599 [49:58:34<51:15,  3.12s/it]  ERROR: [youtube] dk4Ap1wQJsA: Video unavailable
 73%|███████▎  | 2614/3599 [49:58:34<38:42,  2.36s/it]

 73%|███████▎  | 2615/3599 [49:58:39<49:39,  3.03s/it]

 73%|███████▎  | 2616/3599 [49:58:46<1:08:17,  4.17s/it]

 73%|███████▎  | 2617/3599 [49:58:50<1:10:11,  4.29s/it]

 73%|███████▎  | 2618/3599 [49:58:57<1:19:25,  4.86s/it]

 73%|███████▎  | 2619/3599 [49:59:04<1:31:09,  5.58s/it]

 73%|███████▎  | 2620/3599 [49:59:11<1:37:46,  5.99s/it]

 73%|███████▎  | 2621/3599 [49:59:17<1:39:20,  6.09s/it]

 73%|███████▎  | 2622/3599 [49:59:28<2:01:16,  7.45s/it]ERROR: [youtube] e7d6R63EF0c: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 73%|███████▎  | 2623/3599 [49:59:28<1:27:35,  5.39s/it]ERROR: [youtube] e7noNP0p6Jw: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 73%|███████▎  | 2624/3599 [49:59:29<1:03:44,  3.92s/it]

 73%|███████▎  | 2625/3599 [49:59:45<2:04:17,  7.66s/it]

 73%|███████▎  | 2626/3599 [50:00:09<3:22:35, 12.49s/it]

 73%|███████▎  | 2627/3599 [50:00:14<2:47:25, 10.34s/it]

 73%|███████▎  | 2628/3599 [50:00:24<2:45:58, 10.26s/it]

 73%|███████▎  | 2629/3599 [50:00:30<2:21:39,  8.76s/it]

 73%|███████▎  | 2630/3599 [50:00:37<2:16:28,  8.45s/it]

 73%|███████▎  | 2631/3599 [50:00:42<1:56:54,  7.25s/it]

 73%|███████▎  | 2632/3599 [50:00:53<2:13:58,  8.31s/it]

 73%|███████▎  | 2633/3599 [50:00:57<1:54:06,  7.09s/it]ERROR: [youtube] eMqzDGo5Fnw: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 73%|███████▎  | 2634/3599 [50:00:57<1:22:11,  5.11s/it]

 73%|███████▎  | 2635/3599 [50:01:04<1:28:59,  5.54s/it]

 73%|███████▎  | 2636/3599 [50:01:11<1:35:20,  5.94s/it]

 73%|███████▎  | 2637/3599 [50:01:20<1:49:18,  6.82s/it]

 73%|███████▎  | 2638/3599 [50:01:29<2:01:00,  7.56s/it]

 73%|███████▎  | 2639/3599 [50:01:37<2:04:06,  7.76s/it]

 73%|███████▎  | 2640/3599 [50:01:43<1:55:14,  7.21s/it]ERROR: [youtube] eTF0gpdFIGQ: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 73%|███████▎  | 2641/3599 [50:01:44<1:22:57,  5.20s/it]

 73%|███████▎  | 2642/3599 [50:01:51<1:31:54,  5.76s/it]

 73%|███████▎  | 2643/3599 [50:01:56<1:29:49,  5.64s/it]

 73%|███████▎  | 2644/3599 [50:02:01<1:26:30,  5.44s/it]

 73%|███████▎  | 2645/3599 [50:02:15<2:05:10,  7.87s/it]

 74%|███████▎  | 2646/3599 [50:02:24<2:11:28,  8.28s/it]

 74%|███████▎  | 2647/3599 [50:02:28<1:50:50,  6.99s/it]

 74%|███████▎  | 2648/3599 [50:02:32<1:36:30,  6.09s/it]

 74%|███████▎  | 2649/3599 [50:02:36<1:29:11,  5.63s/it]

 74%|███████▎  | 2650/3599 [50:02:45<1:44:46,  6.62s/it]

 74%|███████▎  | 2651/3599 [50:02:50<1:34:40,  5.99s/it]

 74%|███████▎  | 2652/3599 [50:03:00<1:55:56,  7.35s/it]ERROR: [youtube] ecXddV-N0_g: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 74%|███████▎  | 2653/3599 [50:03:01<1:23:36,  5.30s/it]

 74%|███████▎  | 2654/3599 [50:03:04<1:14:34,  4.74s/it]ERROR: [youtube] efmB8h4mlZo: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 74%|███████▍  | 2655/3599 [50:03:05<54:49,  3.48s/it]

 74%|███████▍  | 2656/3599 [50:03:12<1:13:05,  4.65s/it]

 74%|███████▍  | 2657/3599 [50:03:16<1:09:33,  4.43s/it]

 74%|███████▍  | 2658/3599 [50:03:23<1:20:45,  5.15s/it]

 74%|███████▍  | 2659/3599 [50:03:39<2:14:19,  8.57s/it]

 74%|███████▍  | 2660/3599 [50:03:43<1:51:25,  7.12s/it]

 74%|███████▍  | 2661/3599 [50:03:51<1:57:01,  7.49s/it]

 74%|███████▍  | 2662/3599 [50:04:05<2:25:27,  9.31s/it]

 74%|███████▍  | 2663/3599 [50:04:15<2:27:18,  9.44s/it]

 74%|███████▍  | 2664/3599 [50:04:20<2:06:24,  8.11s/it]

 74%|███████▍  | 2665/3599 [50:04:26<1:55:30,  7.42s/it]

 74%|███████▍  | 2666/3599 [50:04:42<2:39:25, 10.25s/it]

 74%|███████▍  | 2667/3599 [50:04:47<2:13:41,  8.61s/it]

 74%|███████▍  | 2668/3599 [50:04:53<1:59:03,  7.67s/it]

 74%|███████▍  | 2669/3599 [50:04:58<1:48:43,  7.01s/it]

 74%|███████▍  | 2670/3599 [50:05:03<1:37:05,  6.27s/it]

 74%|███████▍  | 2671/3599 [50:05:10<1:40:39,  6.51s/it]ERROR: [youtube] f2RCCyZfRo8: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 74%|███████▍  | 2672/3599 [50:05:10<1:12:39,  4.70s/it]

 74%|███████▍  | 2673/3599 [50:05:14<1:09:08,  4.48s/it]

 74%|███████▍  | 2674/3599 [50:05:24<1:33:18,  6.05s/it]

 74%|███████▍  | 2675/3599 [50:05:29<1:27:45,  5.70s/it]

 74%|███████▍  | 2676/3599 [50:05:35<1:30:24,  5.88s/it]ERROR: [youtube] f7HEcAl8PvM: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 74%|███████▍  | 2677/3599 [50:05:36<1:05:51,  4.29s/it]

 74%|███████▍  | 2678/3599 [50:05:44<1:25:32,  5.57s/it]

 74%|███████▍  | 2679/3599 [50:05:51<1:32:30,  6.03s/it]

 74%|███████▍  | 2680/3599 [50:05:59<1:40:23,  6.55s/it]

 74%|███████▍  | 2681/3599 [50:06:04<1:33:15,  6.09s/it]

 75%|███████▍  | 2682/3599 [50:06:09<1:27:05,  5.70s/it]

 75%|███████▍  | 2683/3599 [50:06:12<1:16:08,  4.99s/it]

 75%|███████▍  | 2684/3599 [50:06:20<1:26:47,  5.69s/it]

 75%|███████▍  | 2685/3599 [50:06:36<2:16:52,  8.99s/it]

 75%|███████▍  | 2686/3599 [50:06:41<1:57:47,  7.74s/it]

 75%|███████▍  | 2687/3599 [50:06:48<1:55:06,  7.57s/it]

 75%|███████▍  | 2688/3599 [50:06:54<1:44:56,  6.91s/it]

 75%|███████▍  | 2689/3599 [50:06:57<1:28:46,  5.85s/it]

 75%|███████▍  | 2690/3599 [50:07:02<1:22:14,  5.43s/it]

 75%|███████▍  | 2691/3599 [50:07:06<1:17:21,  5.11s/it]

 75%|███████▍  | 2692/3599 [50:07:10<1:13:43,  4.88s/it]

 75%|███████▍  | 2693/3599 [50:07:16<1:16:57,  5.10s/it]

 75%|███████▍  | 2694/3599 [50:07:25<1:36:19,  6.39s/it]

 75%|███████▍  | 2695/3599 [50:07:30<1:31:03,  6.04s/it]

 75%|███████▍  | 2696/3599 [50:07:36<1:29:37,  5.95s/it]ERROR: [youtube] fa2PMfej7rU: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 75%|███████▍  | 2697/3599 [50:07:37<1:04:58,  4.32s/it]ERROR: [youtube] fab-G9I6fGw: Video unavailable
 75%|███████▍  | 2698/3599 [50:07:37<47:50,  3.19s/it]

 75%|███████▍  | 2699/3599 [50:07:50<1:32:35,  6.17s/it]

 75%|███████▌  | 2700/3599 [50:07:56<1:31:33,  6.11s/it]

 75%|███████▌  | 2701/3599 [50:08:10<2:04:58,  8.35s/it]

 75%|███████▌  | 2702/3599 [50:08:22<2:22:03,  9.50s/it]

 75%|███████▌  | 2703/3599 [50:08:26<1:56:42,  7.81s/it]

 75%|███████▌  | 2704/3599 [50:08:30<1:38:43,  6.62s/it]

 75%|███████▌  | 2705/3599 [50:08:36<1:37:18,  6.53s/it]

 75%|███████▌  | 2706/3599 [50:08:43<1:40:28,  6.75s/it]

 75%|███████▌  | 2707/3599 [50:08:53<1:51:45,  7.52s/it]ERROR: [youtube] foOlh1-Ke-Y: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 75%|███████▌  | 2708/3599 [50:08:53<1:20:29,  5.42s/it]ERROR: [youtube] foZ3pTY1hVs: Video unavailable
 75%|███████▌  | 2709/3599 [50:08:54<58:28,  3.94s/it]

 75%|███████▌  | 2710/3599 [50:08:59<1:02:01,  4.19s/it]

 75%|███████▌  | 2711/3599 [50:09:03<1:02:43,  4.24s/it]

 75%|███████▌  | 2712/3599 [50:09:08<1:06:27,  4.50s/it]ERROR: [youtube] g0GNB23iVMQ: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 75%|███████▌  | 2713/3599 [50:09:08<48:42,  3.30s/it]  ERROR: [youtube] g0zl7rO8VdU: Video unavailable
 75%|███████▌  | 2714/3599 [50:09:09<36:06,  2.45s/it]ERROR: [youtube] g1FKrHNAB-Y: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 75%|███████▌  | 2715/3599 [50:09:09<27:31,  1.87s/it]ERROR: [youtube] g26dIn9rxu4: Video unavailable
 75%|███████▌  | 2716/3599 [50:09:10<21:34,  1.47s/it]

 75%|███████▌  | 2717/3599 [50:09:15<35:52,  2.44s/it]

 76%|███████▌  | 2718/3599 [50:09:19<44:13,  3.01s/it]

 76%|███████▌  | 2719/3599 [50:09:24<51:12,  3.49s/it]

 76%|███████▌  | 2720/3599 [50:09:29<1:00:42,  4.14s/it]

 76%|███████▌  | 2721/3599 [50:09:36<1:11:22,  4.88s/it]

 76%|███████▌  | 2722/3599 [50:09:43<1:22:32,  5.65s/it]

 76%|███████▌  | 2723/3599 [50:09:49<1:23:44,  5.74s/it]

 76%|███████▌  | 2724/3599 [50:09:55<1:21:43,  5.60s/it]

 76%|███████▌  | 2725/3599 [50:09:59<1:16:08,  5.23s/it]

 76%|███████▌  | 2726/3599 [50:10:04<1:14:16,  5.11s/it]

 76%|███████▌  | 2727/3599 [50:10:11<1:22:07,  5.65s/it]ERROR: [youtube] gNg_jo1Os6g: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 76%|███████▌  | 2728/3599 [50:10:11<59:43,  4.11s/it]

 76%|███████▌  | 2729/3599 [50:10:18<1:09:58,  4.83s/it]

 76%|███████▌  | 2730/3599 [50:10:23<1:11:30,  4.94s/it]

 76%|███████▌  | 2731/3599 [50:10:27<1:07:10,  4.64s/it]

 76%|███████▌  | 2732/3599 [50:10:32<1:08:47,  4.76s/it]

 76%|███████▌  | 2733/3599 [50:10:36<1:05:27,  4.54s/it]

 76%|███████▌  | 2734/3599 [50:10:44<1:21:30,  5.65s/it]

 76%|███████▌  | 2735/3599 [50:10:50<1:22:25,  5.72s/it]

 76%|███████▌  | 2736/3599 [50:10:55<1:17:29,  5.39s/it]

 76%|███████▌  | 2737/3599 [50:11:00<1:17:03,  5.36s/it]ERROR: [youtube] gaqwp2R8Vm4: Video unavailable
 76%|███████▌  | 2738/3599 [50:11:01<56:31,  3.94s/it]  ERROR: [youtube] gdPuTpV63SA: Video unavailable
 76%|███████▌  | 2739/3599 [50:11:01<41:50,  2.92s/it]

 76%|███████▌  | 2740/3599 [50:11:10<1:06:31,  4.65s/it]

 76%|███████▌  | 2741/3599 [50:11:14<1:05:29,  4.58s/it]

 76%|███████▌  | 2742/3599 [50:11:20<1:11:05,  4.98s/it]

 76%|███████▌  | 2743/3599 [50:11:24<1:04:59,  4.56s/it]

 76%|███████▌  | 2744/3599 [50:11:28<1:04:28,  4.53s/it]

 76%|███████▋  | 2745/3599 [50:11:33<1:05:33,  4.61s/it]

 76%|███████▋  | 2746/3599 [50:11:48<1:51:32,  7.85s/it]

 76%|███████▋  | 2747/3599 [50:12:00<2:07:49,  9.00s/it]

 76%|███████▋  | 2748/3599 [50:12:04<1:45:03,  7.41s/it]ERROR: [youtube] gscaZnbR0y4: This video has been removed for violating YouTube's policy on violent or graphic content
 76%|███████▋  | 2749/3599 [50:12:04<1:15:46,  5.35s/it]

 76%|███████▋  | 2750/3599 [50:12:09<1:14:15,  5.25s/it]

 76%|███████▋  | 2751/3599 [50:12:16<1:18:33,  5.56s/it]

 76%|███████▋  | 2752/3599 [50:12:22<1:22:38,  5.85s/it]

 76%|███████▋  | 2753/3599 [50:12:46<2:40:12, 11.36s/it]

 77%|███████▋  | 2754/3599 [50:12:51<2:10:00,  9.23s/it]

 77%|███████▋  | 2755/3599 [50:12:56<1:54:10,  8.12s/it]

 77%|███████▋  | 2756/3599 [50:13:03<1:47:18,  7.64s/it]

 77%|███████▋  | 2757/3599 [50:13:09<1:40:15,  7.14s/it]

 77%|███████▋  | 2758/3599 [50:13:16<1:42:49,  7.34s/it]

 77%|███████▋  | 2759/3599 [50:13:22<1:34:26,  6.75s/it]ERROR: [youtube] h9hJ1gFRHnw: Video unavailable
 77%|███████▋  | 2760/3599 [50:13:22<1:08:22,  4.89s/it]

 77%|███████▋  | 2761/3599 [50:13:27<1:09:23,  4.97s/it]

 77%|███████▋  | 2762/3599 [50:13:32<1:09:17,  4.97s/it]

 77%|███████▋  | 2763/3599 [50:13:37<1:07:55,  4.87s/it]ERROR: [youtube] hLWaV1ggsoo: Video unavailable
 77%|███████▋  | 2764/3599 [50:13:38<52:33,  3.78s/it]

 77%|███████▋  | 2765/3599 [50:13:43<54:26,  3.92s/it]

 77%|███████▋  | 2766/3599 [50:13:48<1:00:33,  4.36s/it]

 77%|███████▋  | 2767/3599 [50:13:55<1:10:55,  5.12s/it]

 77%|███████▋  | 2768/3599 [50:14:36<3:39:09, 15.82s/it]

 77%|███████▋  | 2769/3599 [50:14:48<3:26:03, 14.90s/it]

 77%|███████▋  | 2770/3599 [50:14:53<2:43:02, 11.80s/it]ERROR: [youtube] hczZPbDqons: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 77%|███████▋  | 2771/3599 [50:14:53<1:56:05,  8.41s/it]

 77%|███████▋  | 2772/3599 [50:15:00<1:46:20,  7.72s/it]

 77%|███████▋  | 2773/3599 [50:15:06<1:39:17,  7.21s/it]

 77%|███████▋  | 2774/3599 [50:15:11<1:30:00,  6.55s/it]

 77%|███████▋  | 2775/3599 [50:15:16<1:24:40,  6.17s/it]

 77%|███████▋  | 2776/3599 [50:15:22<1:23:19,  6.08s/it]

 77%|███████▋  | 2777/3599 [50:15:27<1:18:27,  5.73s/it]

 77%|███████▋  | 2778/3599 [50:15:30<1:08:54,  5.04s/it]

 77%|███████▋  | 2779/3599 [50:15:34<1:05:44,  4.81s/it]

 77%|███████▋  | 2780/3599 [50:15:40<1:11:00,  5.20s/it]

 77%|███████▋  | 2781/3599 [50:15:44<1:05:44,  4.82s/it]

 77%|███████▋  | 2782/3599 [50:15:52<1:16:21,  5.61s/it]

 77%|███████▋  | 2783/3599 [50:15:59<1:23:06,  6.11s/it]

 77%|███████▋  | 2784/3599 [50:16:07<1:29:29,  6.59s/it]

 77%|███████▋  | 2785/3599 [50:16:12<1:24:38,  6.24s/it]

 77%|███████▋  | 2786/3599 [50:16:36<2:36:51, 11.58s/it]

 77%|███████▋  | 2787/3599 [50:16:45<2:23:15, 10.59s/it]

 77%|███████▋  | 2788/3599 [50:16:50<2:01:18,  8.97s/it]

 77%|███████▋  | 2789/3599 [50:16:58<1:59:27,  8.85s/it]ERROR: [youtube] hymbiSegpcc: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 78%|███████▊  | 2790/3599 [50:16:59<1:25:43,  6.36s/it]

 78%|███████▊  | 2791/3599 [50:17:04<1:22:21,  6.12s/it]

 78%|███████▊  | 2792/3599 [50:17:09<1:17:41,  5.78s/it]ERROR: [youtube] i1bEu_tSqMA: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 78%|███████▊  | 2793/3599 [50:17:10<56:15,  4.19s/it]

 78%|███████▊  | 2794/3599 [50:17:14<55:08,  4.11s/it]

 78%|███████▊  | 2795/3599 [50:17:21<1:05:59,  4.93s/it]

 78%|███████▊  | 2796/3599 [50:17:28<1:17:09,  5.77s/it]

 78%|███████▊  | 2797/3599 [50:17:33<1:13:01,  5.46s/it]

 78%|███████▊  | 2798/3599 [50:17:38<1:09:29,  5.21s/it]

 78%|███████▊  | 2799/3599 [50:17:43<1:07:54,  5.09s/it]

 78%|███████▊  | 2800/3599 [50:17:48<1:09:39,  5.23s/it]

 78%|███████▊  | 2801/3599 [50:17:54<1:10:38,  5.31s/it]

 78%|███████▊  | 2802/3599 [50:18:01<1:18:55,  5.94s/it]

 78%|███████▊  | 2803/3599 [50:18:06<1:15:36,  5.70s/it]

 78%|███████▊  | 2804/3599 [50:18:24<2:04:48,  9.42s/it]

 78%|███████▊  | 2805/3599 [50:18:30<1:48:42,  8.21s/it]

 78%|███████▊  | 2806/3599 [50:18:42<2:05:12,  9.47s/it]

 78%|███████▊  | 2807/3599 [50:18:53<2:10:07,  9.86s/it]

 78%|███████▊  | 2808/3599 [50:18:57<1:48:08,  8.20s/it]

 78%|███████▊  | 2809/3599 [50:19:03<1:39:43,  7.57s/it]

 78%|███████▊  | 2810/3599 [50:19:09<1:34:01,  7.15s/it]

 78%|███████▊  | 2811/3599 [50:19:19<1:44:44,  7.97s/it]

 78%|███████▊  | 2812/3599 [50:19:29<1:50:14,  8.41s/it]

 78%|███████▊  | 2813/3599 [50:19:35<1:40:07,  7.64s/it]

 78%|███████▊  | 2814/3599 [50:19:39<1:25:53,  6.57s/it]

 78%|███████▊  | 2815/3599 [50:19:44<1:22:49,  6.34s/it]

 78%|███████▊  | 2816/3599 [50:19:49<1:17:11,  5.91s/it]ERROR: [youtube] ilhGu76uifo: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 78%|███████▊  | 2817/3599 [50:19:50<55:55,  4.29s/it]

 78%|███████▊  | 2818/3599 [50:19:54<56:04,  4.31s/it]

 78%|███████▊  | 2819/3599 [50:20:11<1:44:54,  8.07s/it]

 78%|███████▊  | 2820/3599 [50:20:25<2:07:42,  9.84s/it]

 78%|███████▊  | 2821/3599 [50:20:30<1:48:22,  8.36s/it]

 78%|███████▊  | 2822/3599 [50:20:35<1:36:04,  7.42s/it]

 78%|███████▊  | 2823/3599 [50:20:42<1:34:12,  7.28s/it]

 78%|███████▊  | 2824/3599 [50:20:50<1:37:04,  7.52s/it]

 78%|███████▊  | 2825/3599 [50:20:56<1:30:09,  6.99s/it]

 79%|███████▊  | 2826/3599 [50:21:17<2:22:30, 11.06s/it]

 79%|███████▊  | 2827/3599 [50:21:21<1:58:43,  9.23s/it]

 79%|███████▊  | 2828/3599 [50:21:27<1:45:03,  8.18s/it]

 79%|███████▊  | 2829/3599 [50:21:32<1:32:45,  7.23s/it]

 79%|███████▊  | 2830/3599 [50:21:38<1:28:30,  6.91s/it]

 79%|███████▊  | 2831/3599 [50:21:42<1:16:07,  5.95s/it]

 79%|███████▊  | 2832/3599 [50:21:47<1:11:34,  5.60s/it]

 79%|███████▊  | 2833/3599 [50:21:51<1:06:04,  5.18s/it]

 79%|███████▊  | 2834/3599 [50:21:56<1:03:26,  4.98s/it]

 79%|███████▉  | 2835/3599 [50:22:05<1:21:07,  6.37s/it]ERROR: [youtube] j6XZF_1hj9U: Video unavailable
 79%|███████▉  | 2836/3599 [50:22:06<58:37,  4.61s/it]

 79%|███████▉  | 2837/3599 [50:22:23<1:45:35,  8.31s/it]

 79%|███████▉  | 2838/3599 [50:22:27<1:30:00,  7.10s/it]ERROR: [youtube] jDbKL2z3anU: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 79%|███████▉  | 2839/3599 [50:22:27<1:05:00,  5.13s/it]

 79%|███████▉  | 2840/3599 [50:22:45<1:53:35,  8.98s/it]

 79%|███████▉  | 2841/3599 [50:22:51<1:41:49,  8.06s/it]

 79%|███████▉  | 2842/3599 [50:22:57<1:31:43,  7.27s/it]

 79%|███████▉  | 2843/3599 [50:23:17<2:19:03, 11.04s/it]

 79%|███████▉  | 2844/3599 [50:23:22<1:56:06,  9.23s/it]

 79%|███████▉  | 2845/3599 [50:23:31<1:58:20,  9.42s/it]ERROR: [youtube] jIcBprYurJg: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 79%|███████▉  | 2846/3599 [50:23:32<1:24:38,  6.74s/it]

 79%|███████▉  | 2847/3599 [50:24:31<4:41:03, 22.42s/it]ERROR: unable to download video data: HTTP Error 403: Forbidden
 79%|███████▉  | 2848/3599 [50:24:33<3:22:53, 16.21s/it]

 79%|███████▉  | 2849/3599 [50:24:40<2:51:06, 13.69s/it]

 79%|███████▉  | 2850/3599 [50:24:48<2:29:26, 11.97s/it]

 79%|███████▉  | 2851/3599 [50:24:54<2:04:18,  9.97s/it]

 79%|███████▉  | 2852/3599 [50:24:59<1:45:28,  8.47s/it]

 79%|███████▉  | 2853/3599 [50:25:07<1:44:39,  8.42s/it]

 79%|███████▉  | 2854/3599 [50:25:12<1:30:54,  7.32s/it]

 79%|███████▉  | 2855/3599 [50:25:20<1:34:20,  7.61s/it]

 79%|███████▉  | 2856/3599 [50:25:24<1:19:30,  6.42s/it]

 79%|███████▉  | 2857/3599 [50:25:31<1:24:04,  6.80s/it]ERROR: [youtube] jXmARLj23WM: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 79%|███████▉  | 2858/3599 [50:25:32<1:00:41,  4.91s/it]

 79%|███████▉  | 2859/3599 [50:25:37<1:02:00,  5.03s/it]

 79%|███████▉  | 2860/3599 [50:25:45<1:12:29,  5.89s/it]

 79%|███████▉  | 2861/3599 [50:25:50<1:09:32,  5.65s/it]

 80%|███████▉  | 2862/3599 [50:25:54<1:01:28,  5.00s/it]

 80%|███████▉  | 2863/3599 [50:26:01<1:10:37,  5.76s/it]

 80%|███████▉  | 2864/3599 [50:26:07<1:10:02,  5.72s/it]

 80%|███████▉  | 2865/3599 [50:26:11<1:05:29,  5.35s/it]

 80%|███████▉  | 2866/3599 [50:26:16<1:03:32,  5.20s/it]ERROR: [youtube] jgREpBfnWo0: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 80%|███████▉  | 2867/3599 [50:26:17<46:35,  3.82s/it]

 80%|███████▉  | 2868/3599 [50:26:21<49:33,  4.07s/it]

 80%|███████▉  | 2869/3599 [50:26:25<49:26,  4.06s/it]ERROR: [youtube] jkVO1-T2_1Y: Video unavailable
 80%|███████▉  | 2870/3599 [50:26:26<36:40,  3.02s/it]

 80%|███████▉  | 2871/3599 [50:26:31<42:25,  3.50s/it]

 80%|███████▉  | 2872/3599 [50:26:35<44:17,  3.66s/it]

 80%|███████▉  | 2873/3599 [50:27:07<2:26:46, 12.13s/it]

 80%|███████▉  | 2874/3599 [50:27:20<2:31:30, 12.54s/it]

 80%|███████▉  | 2875/3599 [50:27:26<2:06:46, 10.51s/it]

 80%|███████▉  | 2876/3599 [50:27:31<1:47:08,  8.89s/it]

 80%|███████▉  | 2877/3599 [50:27:36<1:32:13,  7.66s/it]ERROR: [youtube] jzvUsBJRmiI: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 80%|███████▉  | 2878/3599 [50:27:36<1:06:27,  5.53s/it]

 80%|███████▉  | 2879/3599 [50:27:41<1:02:15,  5.19s/it]ERROR: [youtube] k19EzWshYyo: Video unavailable
 80%|████████  | 2880/3599 [50:27:41<45:21,  3.79s/it]

 80%|████████  | 2881/3599 [50:27:46<49:26,  4.13s/it]

 80%|████████  | 2882/3599 [50:27:53<59:06,  4.95s/it]

 80%|████████  | 2883/3599 [50:28:02<1:14:39,  6.26s/it]ERROR: [youtube] k4nDRzECe7Y: Video unavailable
 80%|████████  | 2884/3599 [50:28:03<54:15,  4.55s/it]

 80%|████████  | 2885/3599 [50:28:19<1:36:27,  8.11s/it]

 80%|████████  | 2886/3599 [50:28:33<1:57:46,  9.91s/it]

 80%|████████  | 2887/3599 [50:28:39<1:43:04,  8.69s/it]

 80%|████████  | 2888/3599 [50:28:47<1:40:51,  8.51s/it]

 80%|████████  | 2889/3599 [50:28:54<1:35:02,  8.03s/it]

 80%|████████  | 2890/3599 [50:29:00<1:26:19,  7.30s/it]

 80%|████████  | 2891/3599 [50:29:06<1:22:17,  6.97s/it]

 80%|████████  | 2892/3599 [50:31:10<8:16:41, 42.15s/it]

 80%|████████  | 2893/3599 [50:31:16<6:05:38, 31.07s/it]

 80%|████████  | 2894/3599 [50:31:19<4:28:46, 22.87s/it]

 80%|████████  | 2895/3599 [50:31:40<4:20:14, 22.18s/it]

 80%|████████  | 2896/3599 [50:31:44<3:16:11, 16.74s/it]

 80%|████████  | 2897/3599 [50:31:48<2:31:51, 12.98s/it]

 81%|████████  | 2898/3599 [50:31:56<2:12:15, 11.32s/it]

 81%|████████  | 2899/3599 [50:32:02<1:53:22,  9.72s/it]

 81%|████████  | 2900/3599 [50:32:09<1:46:28,  9.14s/it]ERROR: [youtube] kSxnCjzxV9o: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 81%|████████  | 2901/3599 [50:32:10<1:16:11,  6.55s/it]

 81%|████████  | 2902/3599 [50:32:14<1:06:57,  5.76s/it]

 81%|████████  | 2903/3599 [50:32:21<1:12:05,  6.21s/it]

 81%|████████  | 2904/3599 [50:32:26<1:08:19,  5.90s/it]ERROR: [youtube] k_doXhccu8U: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 81%|████████  | 2905/3599 [50:32:27<49:31,  4.28s/it]

 81%|████████  | 2906/3599 [50:32:36<1:06:45,  5.78s/it]

 81%|████████  | 2907/3599 [50:32:41<1:04:44,  5.61s/it]

 81%|████████  | 2908/3599 [50:32:53<1:24:49,  7.37s/it]

 81%|████████  | 2909/3599 [50:33:01<1:29:07,  7.75s/it]

 81%|████████  | 2910/3599 [50:33:11<1:36:40,  8.42s/it]

 81%|████████  | 2911/3599 [50:33:17<1:27:47,  7.66s/it]ERROR: [youtube] ke7YJy1ocLo: Video unavailable
 81%|████████  | 2912/3599 [50:33:18<1:03:22,  5.53s/it]

 81%|████████  | 2913/3599 [50:33:23<1:01:56,  5.42s/it]

 81%|████████  | 2914/3599 [50:33:28<59:40,  5.23s/it]  ERROR: [youtube] kfU6OJoEZ58: Video unavailable
 81%|████████  | 2915/3599 [50:33:28<44:20,  3.89s/it]

 81%|████████  | 2916/3599 [50:33:36<55:32,  4.88s/it]

 81%|████████  | 2917/3599 [50:33:53<1:37:58,  8.62s/it]

 81%|████████  | 2918/3599 [50:33:58<1:26:01,  7.58s/it]

 81%|████████  | 2919/3599 [50:34:03<1:15:19,  6.65s/it]

[download]  31.9% of   60.62MiB at    7.91MiB/s ETA 00:05

ERROR: unable to download video data: HTTP Error 403: Forbidden
 81%|████████  | 2920/3599 [50:34:08<1:12:41,  6.42s/it]

 81%|████████  | 2921/3599 [50:34:13<1:05:36,  5.81s/it]ERROR: [youtube] knUZN5ZP6bE: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 81%|████████  | 2922/3599 [50:34:13<47:47,  4.24s/it]  ERROR: [youtube] kne7hZ9Zs0k: Video unavailable
 81%|████████  | 2923/3599 [50:34:14<35:10,  3.12s/it]

 81%|████████  | 2924/3599 [50:34:18<38:04,  3.38s/it]ERROR: [youtube] krkkm1RrvAY: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 81%|████████▏ | 2925/3599 [50:34:18<28:20,  2.52s/it]

 81%|████████▏ | 2926/3599 [50:34:38<1:24:38,  7.55s/it]

 81%|████████▏ | 2927/3599 [50:34:42<1:12:11,  6.45s/it]

 81%|████████▏ | 2928/3599 [50:34:48<1:12:52,  6.52s/it]

 81%|████████▏ | 2929/3599 [50:35:03<1:39:20,  8.90s/it]

 81%|████████▏ | 2930/3599 [50:35:11<1:36:39,  8.67s/it]

ERROR: unable to download video data: HTTP Error 403: Forbidden
 81%|████████▏ | 2931/3599 [50:35:18<1:31:45,  8.24s/it]

 81%|████████▏ | 2932/3599 [50:35:23<1:19:16,  7.13s/it]ERROR: [youtube] kzYR0Oc5RVY: Video unavailable
 81%|████████▏ | 2933/3599 [50:35:23<57:18,  5.16s/it]

 82%|████████▏ | 2934/3599 [50:36:08<3:09:08, 17.07s/it]

 82%|████████▏ | 2935/3599 [50:36:12<2:24:44, 13.08s/it]

 82%|████████▏ | 2936/3599 [50:36:17<1:56:44, 10.57s/it]

 82%|████████▏ | 2937/3599 [50:36:23<1:42:06,  9.25s/it]

 82%|████████▏ | 2938/3599 [50:36:34<1:48:23,  9.84s/it]ERROR: [youtube] lF3gOGj2oNE: Video unavailable
 82%|████████▏ | 2939/3599 [50:36:35<1:17:39,  7.06s/it]

 82%|████████▏ | 2940/3599 [50:36:39<1:08:57,  6.28s/it]

 82%|████████▏ | 2941/3599 [50:36:49<1:22:13,  7.50s/it]

 82%|████████▏ | 2942/3599 [50:37:05<1:47:58,  9.86s/it]

 82%|████████▏ | 2943/3599 [50:37:10<1:31:53,  8.40s/it]

 82%|████████▏ | 2944/3599 [50:37:13<1:16:37,  7.02s/it]ERROR: [youtube] lNa1Eu3fJoM: Video unavailable
 82%|████████▏ | 2945/3599 [50:37:14<55:21,  5.08s/it]  ERROR: [youtube] lS-JKK7nNu0: Video unavailable
 82%|████████▏ | 2946/3599 [50:37:15<40:31,  3.72s/it]ERROR: [youtube] lU14qnb4i30: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 82%|████████▏ | 2947/3599 [50:37:15<30:08,  2.77s/it]

 82%|████████▏ | 2948/3599 [50:37:23<45:30,  4.19s/it]

 82%|████████▏ | 2949/3599 [50:37:49<1:56:54, 10.79s/it]

 82%|████████▏ | 2950/3599 [50:37:54<1:37:14,  8.99s/it]

 82%|████████▏ | 2951/3599 [50:38:00<1:27:31,  8.10s/it]

 82%|████████▏ | 2952/3599 [50:38:08<1:27:34,  8.12s/it]

 82%|████████▏ | 2953/3599 [50:38:13<1:16:56,  7.15s/it]

 82%|████████▏ | 2954/3599 [50:38:22<1:23:41,  7.79s/it]

 82%|████████▏ | 2955/3599 [50:38:28<1:16:58,  7.17s/it]

 82%|████████▏ | 2956/3599 [50:38:34<1:13:42,  6.88s/it]

 82%|████████▏ | 2957/3599 [50:38:40<1:10:45,  6.61s/it]

 82%|████████▏ | 2958/3599 [50:38:52<1:27:32,  8.19s/it]ERROR: [youtube] lkDUVA2dlYI: Video unavailable
 82%|████████▏ | 2959/3599 [50:38:52<1:02:59,  5.91s/it]

 82%|████████▏ | 2960/3599 [50:38:57<58:17,  5.47s/it]

 82%|████████▏ | 2961/3599 [50:39:03<59:22,  5.58s/it]

 82%|████████▏ | 2962/3599 [50:39:08<58:38,  5.52s/it]

 82%|████████▏ | 2963/3599 [50:39:19<1:15:38,  7.14s/it]

 82%|████████▏ | 2964/3599 [50:39:23<1:06:20,  6.27s/it]

 82%|████████▏ | 2965/3599 [50:39:27<59:45,  5.66s/it]

 82%|████████▏ | 2966/3599 [50:39:34<1:03:22,  6.01s/it]

 82%|████████▏ | 2967/3599 [50:39:39<1:00:27,  5.74s/it]ERROR: [youtube] lxmC4M7S5RI: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 82%|████████▏ | 2968/3599 [50:39:40<43:53,  4.17s/it]

 82%|████████▏ | 2969/3599 [50:39:44<43:18,  4.12s/it]

 83%|████████▎ | 2970/3599 [50:39:50<49:12,  4.69s/it]ERROR: [youtube] m23E0cE_7T8: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 83%|████████▎ | 2971/3599 [50:39:51<37:24,  3.57s/it]

 83%|████████▎ | 2972/3599 [50:39:56<41:43,  3.99s/it]

 83%|████████▎ | 2973/3599 [50:40:09<1:09:34,  6.67s/it]

 83%|████████▎ | 2974/3599 [50:40:13<1:03:08,  6.06s/it]

 83%|████████▎ | 2975/3599 [50:40:21<1:07:53,  6.53s/it]

 83%|████████▎ | 2976/3599 [50:40:26<1:01:56,  5.97s/it]ERROR: [youtube] m8-9eQHic1Y: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 83%|████████▎ | 2977/3599 [50:40:26<44:56,  4.34s/it]

 83%|████████▎ | 2978/3599 [50:40:31<46:51,  4.53s/it]

 83%|████████▎ | 2979/3599 [50:40:42<1:06:49,  6.47s/it]

 83%|████████▎ | 2980/3599 [50:40:47<1:02:55,  6.10s/it]ERROR: [youtube] mF510j0PABA: Video unavailable
 83%|████████▎ | 2981/3599 [50:40:48<45:36,  4.43s/it]

 83%|████████▎ | 2982/3599 [50:40:52<45:09,  4.39s/it]

 83%|████████▎ | 2983/3599 [50:40:58<48:31,  4.73s/it]

 83%|████████▎ | 2984/3599 [50:41:03<49:37,  4.84s/it]

 83%|████████▎ | 2985/3599 [50:41:07<47:51,  4.68s/it]

 83%|████████▎ | 2986/3599 [50:41:13<49:50,  4.88s/it]

 83%|████████▎ | 2987/3599 [50:41:18<51:53,  5.09s/it]ERROR: [youtube] mM3jXRuj4xo: Video unavailable
 83%|████████▎ | 2988/3599 [50:41:19<37:53,  3.72s/it]

 83%|████████▎ | 2989/3599 [50:41:23<39:54,  3.93s/it]

 83%|████████▎ | 2990/3599 [50:41:32<56:33,  5.57s/it]

 83%|████████▎ | 2991/3599 [50:41:39<1:00:07,  5.93s/it]

 83%|████████▎ | 2992/3599 [50:41:43<54:17,  5.37s/it]

 83%|████████▎ | 2993/3599 [50:41:48<51:46,  5.13s/it]

 83%|████████▎ | 2994/3599 [50:41:53<52:59,  5.25s/it]

 83%|████████▎ | 2995/3599 [50:41:57<48:54,  4.86s/it]

 83%|████████▎ | 2996/3599 [50:42:11<1:15:57,  7.56s/it]

 83%|████████▎ | 2997/3599 [50:42:25<1:35:29,  9.52s/it]

 83%|████████▎ | 2998/3599 [50:42:30<1:20:17,  8.02s/it]

 83%|████████▎ | 2999/3599 [50:42:39<1:22:30,  8.25s/it]

 83%|████████▎ | 3000/3599 [50:42:42<1:08:32,  6.87s/it]

 83%|████████▎ | 3001/3599 [50:42:46<58:37,  5.88s/it]

 83%|████████▎ | 3002/3599 [50:43:02<1:28:44,  8.92s/it]

 83%|████████▎ | 3003/3599 [50:43:05<1:12:38,  7.31s/it]

 83%|████████▎ | 3004/3599 [50:43:58<3:27:08, 20.89s/it]

 83%|████████▎ | 3005/3599 [50:44:06<2:48:38, 17.03s/it]

 84%|████████▎ | 3006/3599 [50:44:13<2:19:47, 14.14s/it]

 84%|████████▎ | 3007/3599 [50:44:18<1:50:02, 11.15s/it]ERROR: [youtube] mmgh56BrzxU: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 84%|████████▎ | 3008/3599 [50:44:18<1:18:27,  7.97s/it]

 84%|████████▎ | 3009/3599 [50:44:27<1:20:43,  8.21s/it]

 84%|████████▎ | 3010/3599 [50:44:35<1:19:17,  8.08s/it]

 84%|████████▎ | 3011/3599 [50:44:39<1:08:36,  7.00s/it]

 84%|████████▎ | 3012/3599 [50:44:43<58:54,  6.02s/it]

 84%|████████▎ | 3013/3599 [50:44:47<54:16,  5.56s/it]

 84%|████████▎ | 3014/3599 [50:44:57<1:05:54,  6.76s/it]

 84%|████████▍ | 3015/3599 [50:45:01<58:12,  5.98s/it]  ERROR: [youtube] n1183UTJjcY: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 84%|████████▍ | 3016/3599 [50:45:02<42:15,  4.35s/it]

 84%|████████▍ | 3017/3599 [50:45:10<52:55,  5.46s/it]

 84%|████████▍ | 3018/3599 [50:45:17<59:20,  6.13s/it]

 84%|████████▍ | 3019/3599 [50:45:22<54:43,  5.66s/it]

 84%|████████▍ | 3020/3599 [50:45:28<56:00,  5.80s/it]

 84%|████████▍ | 3021/3599 [50:45:34<55:06,  5.72s/it]

 84%|████████▍ | 3022/3599 [50:45:38<51:20,  5.34s/it]

 84%|████████▍ | 3023/3599 [50:45:44<53:38,  5.59s/it]

 84%|████████▍ | 3024/3599 [50:45:49<51:24,  5.36s/it]

 84%|████████▍ | 3025/3599 [50:45:53<48:31,  5.07s/it]

 84%|████████▍ | 3026/3599 [50:45:58<46:17,  4.85s/it]

[download]  85.7% of   22.63MiB at    8.35MiB/s ETA 00:00

ERROR: unable to download video data: HTTP Error 403: Forbidden
 84%|████████▍ | 3027/3599 [50:46:02<45:44,  4.80s/it]

 84%|████████▍ | 3028/3599 [50:46:16<1:10:06,  7.37s/it]

 84%|████████▍ | 3029/3599 [50:46:21<1:03:39,  6.70s/it]

 84%|████████▍ | 3030/3599 [50:46:25<56:48,  5.99s/it]

 84%|████████▍ | 3031/3599 [50:46:31<55:31,  5.86s/it]

 84%|████████▍ | 3032/3599 [50:46:37<55:45,  5.90s/it]

 84%|████████▍ | 3033/3599 [50:46:42<52:50,  5.60s/it]

 84%|████████▍ | 3034/3599 [50:46:46<50:07,  5.32s/it]

 84%|████████▍ | 3035/3599 [50:46:54<57:22,  6.10s/it]ERROR: [youtube] nLpsFq_xE0w: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 84%|████████▍ | 3036/3599 [50:46:55<42:16,  4.50s/it]ERROR: [youtube] nMIlGQGgyWU: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 84%|████████▍ | 3037/3599 [50:46:56<30:53,  3.30s/it]

 84%|████████▍ | 3038/3599 [50:46:59<31:55,  3.41s/it]ERROR: [youtube] nPCdDmMfF7E: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 84%|████████▍ | 3039/3599 [50:47:00<23:39,  2.54s/it]

 84%|████████▍ | 3040/3599 [50:47:05<30:14,  3.25s/it]

 84%|████████▍ | 3041/3599 [50:47:36<1:47:22, 11.55s/it]ERROR: [youtube] nTM2vJGiP4w: Video unavailable
 85%|████████▍ | 3042/3599 [50:47:36<1:16:38,  8.26s/it]

 85%|████████▍ | 3043/3599 [50:47:47<1:25:01,  9.17s/it]

 85%|████████▍ | 3044/3599 [50:47:52<1:12:20,  7.82s/it]ERROR: [youtube] nX36YqfEO-8: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 85%|████████▍ | 3045/3599 [50:47:53<52:02,  5.64s/it]  ERROR: [youtube] nXgirzULnbA: Video unavailable
 85%|████████▍ | 3046/3599 [50:47:53<37:48,  4.10s/it]

 85%|████████▍ | 3047/3599 [50:47:59<41:24,  4.50s/it]

 85%|████████▍ | 3048/3599 [50:48:08<55:23,  6.03s/it]

 85%|████████▍ | 3049/3599 [50:48:12<50:15,  5.48s/it]ERROR: [youtube] nadr7T_WbY8: Video unavailable
 85%|████████▍ | 3050/3599 [50:48:13<36:35,  4.00s/it]

 85%|████████▍ | 3051/3599 [50:48:17<35:37,  3.90s/it]

 85%|████████▍ | 3052/3599 [50:48:22<40:34,  4.45s/it]

 85%|████████▍ | 3053/3599 [50:48:32<54:16,  5.96s/it]

 85%|████████▍ | 3054/3599 [50:48:36<49:55,  5.50s/it]

 85%|████████▍ | 3055/3599 [50:48:40<45:59,  5.07s/it]

 85%|████████▍ | 3056/3599 [50:48:45<43:40,  4.83s/it]

[download]  71.4% of   18.90MiB at    3.94MiB/s ETA 00:01

[download] Got error: 4715374 bytes read, 5137531 more expected
 85%|████████▍ | 3057/3599 [50:49:18<2:00:55, 13.39s/it]

 85%|████████▍ | 3058/3599 [50:49:23<1:37:06, 10.77s/it]

 85%|████████▍ | 3059/3599 [50:49:28<1:22:28,  9.16s/it]

 85%|████████▌ | 3060/3599 [50:49:32<1:09:41,  7.76s/it]ERROR: [youtube] o0fS4uZQOw4: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 85%|████████▌ | 3061/3599 [50:49:33<50:13,  5.60s/it]

 85%|████████▌ | 3062/3599 [50:49:42<57:56,  6.47s/it]ERROR: [youtube] o38OQmcl_cQ: Video unavailable
 85%|████████▌ | 3063/3599 [50:49:42<41:50,  4.68s/it]

 85%|████████▌ | 3064/3599 [50:49:48<46:23,  5.20s/it]

 85%|████████▌ | 3065/3599 [50:49:55<49:14,  5.53s/it]

 85%|████████▌ | 3066/3599 [50:50:01<51:19,  5.78s/it]

 85%|████████▌ | 3067/3599 [50:50:07<50:30,  5.70s/it]

 85%|████████▌ | 3068/3599 [50:50:12<49:09,  5.55s/it]

 85%|████████▌ | 3069/3599 [50:50:19<53:58,  6.11s/it]

 85%|████████▌ | 3070/3599 [50:50:26<54:09,  6.14s/it]

 85%|████████▌ | 3071/3599 [50:50:31<53:00,  6.02s/it]ERROR: [youtube] oI1w4S9au70: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 85%|████████▌ | 3072/3599 [50:50:32<38:31,  4.39s/it]

 85%|████████▌ | 3073/3599 [50:50:35<35:47,  4.08s/it]

 85%|████████▌ | 3074/3599 [50:50:39<34:35,  3.95s/it]

 85%|████████▌ | 3075/3599 [50:50:44<38:02,  4.36s/it]

 85%|████████▌ | 3076/3599 [50:50:48<35:54,  4.12s/it]

 85%|████████▌ | 3077/3599 [50:50:53<39:52,  4.58s/it]

 86%|████████▌ | 3078/3599 [50:50:58<38:59,  4.49s/it]

 86%|████████▌ | 3079/3599 [50:51:04<43:18,  5.00s/it]ERROR: [youtube] oOeeqBqz8VM: Video unavailable
 86%|████████▌ | 3080/3599 [50:51:04<31:36,  3.65s/it]ERROR: [youtube] oT2E9RLpC9Y: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 86%|████████▌ | 3081/3599 [50:51:05<23:34,  2.73s/it]

 86%|████████▌ | 3082/3599 [50:51:08<25:28,  2.96s/it]

 86%|████████▌ | 3083/3599 [50:51:13<30:46,  3.58s/it]

 86%|████████▌ | 3084/3599 [50:51:19<35:27,  4.13s/it]

 86%|████████▌ | 3085/3599 [50:51:23<36:15,  4.23s/it]

 86%|████████▌ | 3086/3599 [50:51:27<35:19,  4.13s/it]

 86%|████████▌ | 3087/3599 [50:51:32<37:36,  4.41s/it]

 86%|████████▌ | 3088/3599 [50:51:36<36:56,  4.34s/it]ERROR: [youtube] oaCLxwy9Nck: Video unavailable
 86%|████████▌ | 3089/3599 [50:51:37<27:22,  3.22s/it]ERROR: [youtube] ob1-BjmbAuw: This video has been removed for violating YouTube's Terms of Service
 86%|████████▌ | 3090/3599 [50:51:38<20:28,  2.41s/it]

 86%|████████▌ | 3091/3599 [50:51:41<23:34,  2.78s/it]

 86%|████████▌ | 3092/3599 [50:51:45<27:08,  3.21s/it]ERROR: [youtube] oc05iRSJncM: Video unavailable
 86%|████████▌ | 3093/3599 [50:51:46<20:22,  2.42s/it]

 86%|████████▌ | 3094/3599 [50:52:05<1:01:09,  7.27s/it]ERROR: [youtube] oetou91aXK0: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 86%|████████▌ | 3095/3599 [50:52:05<44:02,  5.24s/it]

 86%|████████▌ | 3096/3599 [50:52:09<41:47,  4.98s/it]

 86%|████████▌ | 3097/3599 [50:52:16<44:44,  5.35s/it]

 86%|████████▌ | 3098/3599 [50:52:23<49:23,  5.92s/it]

 86%|████████▌ | 3099/3599 [50:52:27<44:54,  5.39s/it]

 86%|████████▌ | 3100/3599 [50:52:32<43:53,  5.28s/it]

 86%|████████▌ | 3101/3599 [50:52:38<44:07,  5.32s/it]ERROR: [youtube] orW0QtYyOVo: Video unavailable
 86%|████████▌ | 3102/3599 [50:52:38<32:04,  3.87s/it]

 86%|████████▌ | 3103/3599 [50:52:45<39:15,  4.75s/it]

 86%|████████▌ | 3104/3599 [50:52:49<37:10,  4.51s/it]

 86%|████████▋ | 3105/3599 [50:52:53<35:19,  4.29s/it]

 86%|████████▋ | 3106/3599 [50:52:57<34:50,  4.24s/it]

 86%|████████▋ | 3107/3599 [50:53:04<41:36,  5.08s/it]ERROR: [youtube] p0glqwun2r0: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 86%|████████▋ | 3108/3599 [50:53:04<30:35,  3.74s/it]

 86%|████████▋ | 3109/3599 [50:53:09<33:56,  4.16s/it]

 86%|████████▋ | 3110/3599 [50:53:13<33:26,  4.10s/it]

 86%|████████▋ | 3111/3599 [50:53:18<33:24,  4.11s/it]

 86%|████████▋ | 3112/3599 [50:53:23<35:36,  4.39s/it]

 86%|████████▋ | 3113/3599 [50:53:26<33:54,  4.19s/it]

 87%|████████▋ | 3114/3599 [50:53:34<41:57,  5.19s/it]

 87%|████████▋ | 3115/3599 [50:53:41<47:01,  5.83s/it]ERROR: [youtube] pBXZyD7pVA8: Video unavailable
 87%|████████▋ | 3116/3599 [50:53:42<34:05,  4.24s/it]

 87%|████████▋ | 3117/3599 [50:53:47<37:28,  4.67s/it]

 87%|████████▋ | 3118/3599 [50:54:12<1:25:57, 10.72s/it]

 87%|████████▋ | 3119/3599 [50:54:18<1:14:44,  9.34s/it]

 87%|████████▋ | 3120/3599 [50:54:27<1:12:47,  9.12s/it]

 87%|████████▋ | 3121/3599 [50:54:33<1:04:30,  8.10s/it]ERROR: [youtube] pKXL2fzkyS0: Video unavailable
 87%|████████▋ | 3122/3599 [50:54:33<46:18,  5.83s/it]

 87%|████████▋ | 3123/3599 [50:54:38<43:35,  5.49s/it]

 87%|████████▋ | 3124/3599 [50:54:42<40:34,  5.13s/it]

 87%|████████▋ | 3125/3599 [50:54:53<54:23,  6.88s/it]ERROR: [youtube] pQEVnoHpxyM: Video unavailable
 87%|████████▋ | 3126/3599 [50:54:54<39:15,  4.98s/it]

 87%|████████▋ | 3127/3599 [50:54:59<38:58,  4.95s/it]

 87%|████████▋ | 3128/3599 [50:55:07<47:06,  6.00s/it]

 87%|████████▋ | 3129/3599 [50:55:14<50:01,  6.39s/it]ERROR: [youtube] p_mq93uPYbs: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 87%|████████▋ | 3130/3599 [50:55:15<36:08,  4.62s/it]

 87%|████████▋ | 3131/3599 [50:55:25<48:48,  6.26s/it]

 87%|████████▋ | 3132/3599 [50:55:30<47:01,  6.04s/it]ERROR: [youtube] pc44o8yg7D0: Video unavailable
 87%|████████▋ | 3133/3599 [50:55:31<34:02,  4.38s/it]

 87%|████████▋ | 3134/3599 [50:55:36<35:50,  4.63s/it]

 87%|████████▋ | 3135/3599 [50:55:42<39:10,  5.07s/it]

 87%|████████▋ | 3136/3599 [50:55:51<46:57,  6.09s/it]

 87%|████████▋ | 3137/3599 [50:56:00<53:50,  6.99s/it]

 87%|████████▋ | 3138/3599 [50:56:05<49:39,  6.46s/it]

 87%|████████▋ | 3139/3599 [50:56:10<45:59,  6.00s/it]

 87%|████████▋ | 3140/3599 [50:56:15<42:59,  5.62s/it]

 87%|████████▋ | 3141/3599 [50:57:56<4:22:06, 34.34s/it]

 87%|████████▋ | 3142/3599 [50:58:03<3:18:52, 26.11s/it]

 87%|████████▋ | 3143/3599 [50:58:09<2:33:32, 20.20s/it]

 87%|████████▋ | 3144/3599 [50:58:15<1:59:52, 15.81s/it]ERROR: [youtube] prJP0gOUEms: Video unavailable
 87%|████████▋ | 3145/3599 [50:58:15<1:24:52, 11.22s/it]

 87%|████████▋ | 3146/3599 [50:58:22<1:15:06,  9.95s/it]

 87%|████████▋ | 3147/3599 [50:58:33<1:15:30, 10.02s/it]

 87%|████████▋ | 3148/3599 [50:58:41<1:11:27,  9.51s/it]

 87%|████████▋ | 3149/3599 [50:58:47<1:03:45,  8.50s/it]

 88%|████████▊ | 3150/3599 [50:58:56<1:04:52,  8.67s/it]

 88%|████████▊ | 3151/3599 [50:59:00<53:10,  7.12s/it]

 88%|████████▊ | 3152/3599 [50:59:11<1:02:38,  8.41s/it]

 88%|████████▊ | 3153/3599 [50:59:15<53:31,  7.20s/it]

 88%|████████▊ | 3154/3599 [50:59:20<48:21,  6.52s/it]ERROR: [youtube] q4sugO4S-UU: Video unavailable
 88%|████████▊ | 3155/3599 [50:59:21<34:55,  4.72s/it]ERROR: [youtube] q5iETSg2uN4: This video has been removed for violating YouTube's Terms of Service
 88%|████████▊ | 3156/3599 [50:59:21<25:33,  3.46s/it]ERROR: [youtube] q63hrrtCORw: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 88%|████████▊ | 3157/3599 [50:59:22<19:04,  2.59s/it]ERROR: [youtube] q7S4UagUWa8: Video unavailable
 88%|████████▊ | 3158/3599 [50:59:23<14:38,  1.99s/it]ERROR: [youtube] qBZ5Xkix4XM: Video unavailable
 88%|████████▊ | 3159/3599 [50:59:23<11:24,  1.56s/it]

 88%|████████▊ | 3160/3599 [50:59:28<18:10,  2.48s/it]ERROR: [youtube] qGCzeeDJRbo: Video unavailable
 88%|████████▊ | 3161/3599 [50:59:28<13:50,  1.90s/it]

 88%|████████▊ | 3162/3599 [50:59:41<36:36,  5.03s/it]

 88%|████████▊ | 3163/3599 [50:59:46<38:05,  5.24s/it]

 88%|████████▊ | 3164/3599 [50:59:55<45:30,  6.28s/it]ERROR: [youtube] qHsWqsXros0: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 88%|████████▊ | 3165/3599 [50:59:56<33:50,  4.68s/it]

 88%|████████▊ | 3166/3599 [51:00:01<34:01,  4.71s/it]

 88%|████████▊ | 3167/3599 [51:00:06<35:15,  4.90s/it]

 88%|████████▊ | 3168/3599 [51:00:12<36:33,  5.09s/it]

 88%|████████▊ | 3169/3599 [51:00:16<34:02,  4.75s/it]ERROR: [youtube] qKTLTK7x57A: Video unavailable. This video contains content from ThePowerHDTV. It is not available in your country.
 88%|████████▊ | 3170/3599 [51:00:17<26:06,  3.65s/it]

 88%|████████▊ | 3171/3599 [51:00:21<28:10,  3.95s/it]ERROR: [youtube] qLzJr7GWYp4: This video has been removed for violating YouTube's policy on violent or graphic content
 88%|████████▊ | 3172/3599 [51:00:22<20:45,  2.92s/it]ERROR: [youtube] qO9uT00yiHw: Video unavailable. This video is no longer available due to a copyright claim by soezimax
 88%|████████▊ | 3173/3599 [51:00:22<15:39,  2.21s/it]ERROR: [youtube] qPvu2b25iWU: This video has been removed for violating YouTube's policy on violent or graphic content
 88%|████████▊ | 3174/3599 [51:00:23<12:07,  1.71s/it]

 88%|████████▊ | 3175/3599 [51:00:28<19:00,  2.69s/it]ERROR: [youtube] qSpPnWFhIPg: Video unavailable
 88%|████████▊ | 3176/3599 [51:00:28<14:25,  2.05s/it]ERROR: [youtube] qTPajWZReK0: This video has been removed for violating YouTube's policy on violent or graphic content
 88%|████████▊ | 3177/3599 [51:00:29<11:19,  1.61s/it]

 88%|████████▊ | 3178/3599 [51:00:34<18:58,  2.70s/it]

 88%|████████▊ | 3179/3599 [51:00:39<22:19,  3.19s/it]

 88%|████████▊ | 3180/3599 [51:00:42<23:31,  3.37s/it]

 88%|████████▊ | 3181/3599 [51:00:46<24:49,  3.56s/it]

 88%|████████▊ | 3182/3599 [51:00:55<34:13,  4.93s/it]

 88%|████████▊ | 3183/3599 [51:00:59<32:34,  4.70s/it]

 88%|████████▊ | 3184/3599 [51:01:03<32:16,  4.67s/it]

 88%|████████▊ | 3185/3599 [51:01:09<34:29,  5.00s/it]

 89%|████████▊ | 3186/3599 [51:01:14<33:58,  4.93s/it]

 89%|████████▊ | 3187/3599 [51:01:22<41:04,  5.98s/it]

 89%|████████▊ | 3188/3599 [51:01:38<1:01:14,  8.94s/it]ERROR: [youtube] qbdCw6_nbvs: Video unavailable
 89%|████████▊ | 3189/3599 [51:01:39<43:47,  6.41s/it]

 89%|████████▊ | 3190/3599 [51:01:45<42:59,  6.31s/it]

 89%|████████▊ | 3191/3599 [51:01:49<39:49,  5.86s/it]

ERROR: unable to download video data: HTTP Error 403: Forbidden
 89%|████████▊ | 3192/3599 [51:01:58<44:49,  6.61s/it]

 89%|████████▊ | 3193/3599 [51:02:02<40:09,  5.93s/it]

 89%|████████▊ | 3194/3599 [51:02:12<47:12,  6.99s/it]ERROR: [youtube] qjdMCrvqi-Q: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 89%|████████▉ | 3195/3599 [51:02:12<34:04,  5.06s/it]

 89%|████████▉ | 3196/3599 [51:02:26<52:27,  7.81s/it]

 89%|████████▉ | 3197/3599 [51:02:33<50:30,  7.54s/it]

 89%|████████▉ | 3198/3599 [51:02:39<47:09,  7.06s/it]

 89%|████████▉ | 3199/3599 [51:02:43<40:51,  6.13s/it]ERROR: [youtube] qxJsBJeVw80: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 89%|████████▉ | 3200/3599 [51:02:44<29:35,  4.45s/it]

 89%|████████▉ | 3201/3599 [51:02:48<30:04,  4.53s/it]

 89%|████████▉ | 3202/3599 [51:02:54<31:33,  4.77s/it]

 89%|████████▉ | 3203/3599 [51:03:01<36:56,  5.60s/it]

 89%|████████▉ | 3204/3599 [51:03:07<37:23,  5.68s/it]

 89%|████████▉ | 3205/3599 [51:03:12<36:00,  5.48s/it]

 89%|████████▉ | 3206/3599 [51:03:16<33:07,  5.06s/it]ERROR: [youtube] r5smfrf6dko: Video unavailable
 89%|████████▉ | 3207/3599 [51:03:17<24:24,  3.74s/it]

 89%|████████▉ | 3208/3599 [51:03:22<27:19,  4.19s/it]

 89%|████████▉ | 3209/3599 [51:03:27<28:42,  4.42s/it]

 89%|████████▉ | 3210/3599 [51:03:32<30:11,  4.66s/it]ERROR: [youtube] rGLmQdWDoZE: This video has been removed for violating YouTube's policy on harassment and bullying
 89%|████████▉ | 3211/3599 [51:03:33<22:05,  3.42s/it]

 89%|████████▉ | 3212/3599 [51:03:40<28:40,  4.45s/it]

 89%|████████▉ | 3213/3599 [51:03:50<39:01,  6.07s/it]

 89%|████████▉ | 3214/3599 [51:04:52<2:27:07, 22.93s/it]

 89%|████████▉ | 3215/3599 [51:04:57<1:52:48, 17.63s/it]

 89%|████████▉ | 3216/3599 [51:05:19<2:00:04, 18.81s/it]

 89%|████████▉ | 3217/3599 [51:05:27<1:39:06, 15.57s/it]

 89%|████████▉ | 3218/3599 [51:05:34<1:23:58, 13.22s/it]

 89%|████████▉ | 3219/3599 [51:05:39<1:07:08, 10.60s/it]

 89%|████████▉ | 3220/3599 [51:05:44<55:45,  8.83s/it]

 89%|████████▉ | 3221/3599 [51:05:48<48:01,  7.62s/it]

 90%|████████▉ | 3222/3599 [51:05:52<40:21,  6.42s/it]

 90%|████████▉ | 3223/3599 [51:05:56<35:56,  5.73s/it]

 90%|████████▉ | 3224/3599 [51:06:00<33:05,  5.30s/it]

 90%|████████▉ | 3225/3599 [51:06:05<31:03,  4.98s/it]

 90%|████████▉ | 3226/3599 [51:06:09<28:51,  4.64s/it]

 90%|████████▉ | 3227/3599 [51:06:13<28:45,  4.64s/it]

 90%|████████▉ | 3228/3599 [51:06:30<51:27,  8.32s/it]

 90%|████████▉ | 3229/3599 [51:06:37<48:59,  7.94s/it]

 90%|████████▉ | 3230/3599 [51:06:47<52:11,  8.49s/it]

 90%|████████▉ | 3231/3599 [51:07:09<1:16:57, 12.55s/it]

 90%|████████▉ | 3232/3599 [51:07:13<1:01:41, 10.09s/it]

 90%|████████▉ | 3233/3599 [51:07:17<50:42,  8.31s/it]  ERROR: [youtube] rmX7XBEohvY: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 90%|████████▉ | 3234/3599 [51:07:18<36:20,  5.97s/it]

 90%|████████▉ | 3235/3599 [51:07:23<35:06,  5.79s/it]

 90%|████████▉ | 3236/3599 [51:07:38<50:27,  8.34s/it]ERROR: [youtube] rp66PomYgmI: Video unavailable. This video contains content from Paramount Global (PMN), who has blocked it on copyright grounds
 90%|████████▉ | 3237/3599 [51:07:39<37:06,  6.15s/it]

 90%|████████▉ | 3238/3599 [51:07:49<44:48,  7.45s/it]

 90%|████████▉ | 3239/3599 [51:07:54<40:25,  6.74s/it]ERROR: [youtube] rrnYgVhAd9w: Video unavailable
 90%|█████████ | 3240/3599 [51:07:55<29:12,  4.88s/it]

 90%|█████████ | 3241/3599 [51:08:03<34:58,  5.86s/it]ERROR: [youtube] rtMmx4ZODJ4: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 90%|█████████ | 3242/3599 [51:08:03<25:22,  4.26s/it]

 90%|█████████ | 3243/3599 [51:08:08<25:36,  4.31s/it]

 90%|█████████ | 3244/3599 [51:08:13<26:42,  4.51s/it]

 90%|█████████ | 3245/3599 [51:08:36<59:43, 10.12s/it]

 90%|█████████ | 3246/3599 [51:08:40<48:39,  8.27s/it]

 90%|█████████ | 3247/3599 [51:08:47<46:05,  7.86s/it]ERROR: [youtube] s3MTbspnr5I: This video has been removed for violating YouTube's Community Guidelines
 90%|█████████ | 3248/3599 [51:08:47<33:06,  5.66s/it]

 90%|█████████ | 3249/3599 [51:09:02<48:04,  8.24s/it]

 90%|█████████ | 3250/3599 [51:09:11<49:28,  8.50s/it]ERROR: [youtube] s5Lp1qsdZuU: Video unavailable
 90%|█████████ | 3251/3599 [51:09:11<35:36,  6.14s/it]

 90%|█████████ | 3252/3599 [51:09:15<31:21,  5.42s/it]ERROR: [youtube] s8wBG-Ui8F8: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 90%|█████████ | 3253/3599 [51:09:16<22:45,  3.95s/it]

 90%|█████████ | 3254/3599 [51:09:19<21:48,  3.79s/it]

 90%|█████████ | 3255/3599 [51:09:23<21:45,  3.80s/it]

 90%|█████████ | 3256/3599 [51:09:29<26:24,  4.62s/it]

 90%|█████████ | 3257/3599 [51:09:33<24:18,  4.27s/it]ERROR: [youtube] sLPB7FzM0lY: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 91%|█████████ | 3258/3599 [51:09:33<17:49,  3.14s/it]ERROR: [youtube] sMnAk5WGQv0: Video unavailable
 91%|█████████ | 3259/3599 [51:09:34<13:21,  2.36s/it]ERROR: [youtube] sNTaujeCvec: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 91%|█████████ | 3260/3599 [51:09:35<10:16,  1.82s/it]

 91%|█████████ | 3261/3599 [51:09:39<15:25,  2.74s/it]

 91%|█████████ | 3262/3599 [51:09:48<25:04,  4.46s/it]

 91%|█████████ | 3263/3599 [51:09:52<23:55,  4.27s/it]

 91%|█████████ | 3264/3599 [51:09:57<25:00,  4.48s/it]

 91%|█████████ | 3265/3599 [51:10:04<28:56,  5.20s/it]

 91%|█████████ | 3266/3599 [51:10:09<29:22,  5.29s/it]

 91%|█████████ | 3267/3599 [51:10:14<28:24,  5.14s/it]

 91%|█████████ | 3268/3599 [51:10:18<26:43,  4.84s/it]

 91%|█████████ | 3269/3599 [51:10:23<27:40,  5.03s/it]

 91%|█████████ | 3270/3599 [51:10:28<26:08,  4.77s/it]

 91%|█████████ | 3271/3599 [51:10:35<29:52,  5.46s/it]

 91%|█████████ | 3272/3599 [51:10:40<29:09,  5.35s/it]

 91%|█████████ | 3273/3599 [51:10:47<31:39,  5.83s/it]

 91%|█████████ | 3274/3599 [51:11:02<47:22,  8.75s/it]

 91%|█████████ | 3275/3599 [51:11:19<59:46, 11.07s/it]ERROR: [youtube] smx4O_Riqos: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 91%|█████████ | 3276/3599 [51:11:19<42:35,  7.91s/it]

 91%|█████████ | 3277/3599 [51:11:30<46:24,  8.65s/it]

 91%|█████████ | 3278/3599 [51:11:38<45:36,  8.53s/it]

 91%|█████████ | 3279/3599 [51:11:43<39:57,  7.49s/it]

 91%|█████████ | 3280/3599 [51:12:24<1:33:48, 17.64s/it]

 91%|█████████ | 3281/3599 [51:12:29<1:13:21, 13.84s/it]

 91%|█████████ | 3282/3599 [51:12:38<1:04:39, 12.24s/it]

 91%|█████████ | 3283/3599 [51:12:43<52:33,  9.98s/it]

 91%|█████████ | 3284/3599 [51:12:47<43:03,  8.20s/it]

 91%|█████████▏| 3285/3599 [51:13:03<56:29, 10.79s/it]

 91%|█████████▏| 3286/3599 [51:13:12<52:16, 10.02s/it]

 91%|█████████▏| 3287/3599 [51:13:18<47:07,  9.06s/it]

 91%|█████████▏| 3288/3599 [51:13:22<39:02,  7.53s/it]

 91%|█████████▏| 3289/3599 [51:13:29<37:12,  7.20s/it]

 91%|█████████▏| 3290/3599 [51:13:34<34:27,  6.69s/it]

 91%|█████████▏| 3291/3599 [51:13:43<37:14,  7.25s/it]ERROR: [youtube] tDekJGfoavc: This video has been removed for violating YouTube's policy on violent or graphic content
 91%|█████████▏| 3292/3599 [51:13:44<27:00,  5.28s/it]

 91%|█████████▏| 3293/3599 [51:13:48<25:22,  4.97s/it]ERROR: [youtube] tJ9cYaqP0SA: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 92%|█████████▏| 3294/3599 [51:13:48<18:37,  3.67s/it]

 92%|█████████▏| 3295/3599 [51:13:53<20:08,  3.98s/it]

 92%|█████████▏| 3296/3599 [51:13:58<21:44,  4.31s/it]

 92%|█████████▏| 3297/3599 [51:14:05<25:11,  5.01s/it]

 92%|█████████▏| 3298/3599 [51:14:14<31:35,  6.30s/it]

 92%|█████████▏| 3299/3599 [51:14:25<38:50,  7.77s/it]ERROR: [youtube] tTYNaO4z5-I: Video unavailable
 92%|█████████▏| 3300/3599 [51:14:26<27:53,  5.60s/it]

 92%|█████████▏| 3301/3599 [51:14:31<27:01,  5.44s/it]

 92%|█████████▏| 3302/3599 [51:14:38<29:56,  6.05s/it]

 92%|█████████▏| 3303/3599 [51:14:44<29:05,  5.90s/it]

 92%|█████████▏| 3304/3599 [51:14:48<26:32,  5.40s/it]

 92%|█████████▏| 3305/3599 [51:14:52<23:40,  4.83s/it]ERROR: [youtube] thSPzjDQPl4: Video unavailable
 92%|█████████▏| 3306/3599 [51:14:52<17:14,  3.53s/it]

 92%|█████████▏| 3307/3599 [51:14:59<21:18,  4.38s/it]

 92%|█████████▏| 3308/3599 [51:15:07<27:46,  5.73s/it]ERROR: [youtube] tljb_ktM4ow: Video unavailable
 92%|█████████▏| 3309/3599 [51:15:08<20:05,  4.16s/it]

 92%|█████████▏| 3310/3599 [51:15:14<22:11,  4.61s/it]

 92%|█████████▏| 3311/3599 [51:15:20<24:04,  5.02s/it]ERROR: [youtube] trETWIjnjgQ: Video unavailable
 92%|█████████▏| 3312/3599 [51:15:20<17:34,  3.67s/it]

 92%|█████████▏| 3313/3599 [51:15:26<20:34,  4.32s/it]

 92%|█████████▏| 3314/3599 [51:15:32<23:17,  4.90s/it]

 92%|█████████▏| 3315/3599 [51:15:44<32:52,  6.94s/it]

[download]  73.7% of   13.18MiB at    6.54MiB/s ETA 00:00

ERROR: unable to download video data: HTTP Error 403: Forbidden
 92%|█████████▏| 3316/3599 [51:15:47<27:22,  5.80s/it]

 92%|█████████▏| 3317/3599 [51:15:53<27:11,  5.79s/it]

 92%|█████████▏| 3318/3599 [51:16:17<52:25, 11.19s/it]

 92%|█████████▏| 3319/3599 [51:16:23<45:48,  9.82s/it]

 92%|█████████▏| 3320/3599 [51:16:29<39:33,  8.51s/it]

 92%|█████████▏| 3321/3599 [51:16:35<36:25,  7.86s/it]

 92%|█████████▏| 3322/3599 [51:16:45<38:58,  8.44s/it]ERROR: [youtube] u4FzmdtX9KU: Video unavailable. This video is no longer available due to a copyright claim by Stephen H. Klein
 92%|█████████▏| 3323/3599 [51:16:45<28:01,  6.09s/it]

 92%|█████████▏| 3324/3599 [51:17:03<43:53,  9.58s/it]

 92%|█████████▏| 3325/3599 [51:17:15<46:59, 10.29s/it]

 92%|█████████▏| 3326/3599 [51:17:19<38:44,  8.52s/it]

 92%|█████████▏| 3327/3599 [51:18:36<2:10:29, 28.79s/it]

 92%|█████████▏| 3328/3599 [51:18:42<1:39:04, 21.94s/it]

 92%|█████████▏| 3329/3599 [51:18:47<1:17:05, 17.13s/it]

 93%|█████████▎| 3330/3599 [51:19:09<1:22:57, 18.50s/it]

 93%|█████████▎| 3331/3599 [51:19:27<1:21:23, 18.22s/it]ERROR: [youtube] uGEr3KgieFo: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 93%|█████████▎| 3332/3599 [51:19:27<57:30, 12.92s/it]

 93%|█████████▎| 3333/3599 [51:19:49<1:09:25, 15.66s/it]ERROR: [youtube] uIx0bjjMnpA: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 93%|█████████▎| 3334/3599 [51:19:50<49:06, 11.12s/it]

 93%|█████████▎| 3335/3599 [51:20:09<59:55, 13.62s/it]

 93%|█████████▎| 3336/3599 [51:20:16<50:56, 11.62s/it]

 93%|█████████▎| 3337/3599 [51:20:22<42:44,  9.79s/it]

 93%|█████████▎| 3338/3599 [51:20:28<38:30,  8.85s/it]

 93%|█████████▎| 3339/3599 [51:20:48<51:56, 11.99s/it]

 93%|█████████▎| 3340/3599 [51:20:53<42:55,  9.95s/it]ERROR: [youtube] uTwz4aaM6Lg: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 93%|█████████▎| 3341/3599 [51:20:54<30:56,  7.20s/it]

 93%|█████████▎| 3342/3599 [51:21:00<30:04,  7.02s/it]

 93%|█████████▎| 3343/3599 [51:21:05<26:35,  6.23s/it]

 93%|█████████▎| 3344/3599 [51:21:12<28:01,  6.60s/it]

 93%|█████████▎| 3345/3599 [51:21:16<24:54,  5.88s/it]

 93%|█████████▎| 3346/3599 [51:21:33<38:54,  9.23s/it]

 93%|█████████▎| 3347/3599 [51:21:38<32:20,  7.70s/it]

 93%|█████████▎| 3348/3599 [51:21:44<30:29,  7.29s/it]

 93%|█████████▎| 3349/3599 [51:22:00<41:37,  9.99s/it]

 93%|█████████▎| 3350/3599 [51:23:11<1:57:41, 28.36s/it]

 93%|█████████▎| 3351/3599 [51:23:17<1:28:54, 21.51s/it]

ERROR: unable to download video data: HTTP Error 403: Forbidden
 93%|█████████▎| 3352/3599 [51:23:27<1:14:26, 18.08s/it]

 93%|█████████▎| 3353/3599 [51:23:40<1:07:17, 16.41s/it]ERROR: [youtube] uuBS1zv-zDo: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 93%|█████████▎| 3354/3599 [51:23:40<47:33, 11.65s/it]  ERROR: [youtube] uu_63r6M9nU: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 93%|█████████▎| 3355/3599 [51:23:41<33:48,  8.31s/it]

 93%|█████████▎| 3356/3599 [51:23:45<28:58,  7.16s/it]

 93%|█████████▎| 3357/3599 [51:23:52<29:09,  7.23s/it]

 93%|█████████▎| 3358/3599 [51:24:02<31:38,  7.88s/it]

 93%|█████████▎| 3359/3599 [51:24:07<28:24,  7.10s/it]

 93%|█████████▎| 3360/3599 [51:24:11<24:21,  6.11s/it]

 93%|█████████▎| 3361/3599 [51:24:15<22:24,  5.65s/it]

 93%|█████████▎| 3362/3599 [51:24:21<22:29,  5.69s/it]

 93%|█████████▎| 3363/3599 [51:24:27<22:22,  5.69s/it]

 93%|█████████▎| 3364/3599 [51:24:32<21:25,  5.47s/it]

 93%|█████████▎| 3365/3599 [51:24:38<21:59,  5.64s/it]

 94%|█████████▎| 3366/3599 [51:24:42<20:29,  5.28s/it]

 94%|█████████▎| 3367/3599 [51:24:47<19:59,  5.17s/it]

 94%|█████████▎| 3368/3599 [51:24:53<20:03,  5.21s/it]

 94%|█████████▎| 3369/3599 [51:25:02<24:38,  6.43s/it]

 94%|█████████▎| 3370/3599 [51:25:10<26:31,  6.95s/it]

 94%|█████████▎| 3371/3599 [51:27:10<2:34:56, 40.78s/it]

 94%|█████████▎| 3372/3599 [51:27:15<1:54:03, 30.15s/it]

 94%|█████████▎| 3373/3599 [51:27:19<1:23:24, 22.14s/it]

 94%|█████████▎| 3374/3599 [51:27:25<1:05:11, 17.39s/it]ERROR: [youtube] vKP8DVDKtDI: Video unavailable
 94%|█████████▍| 3375/3599 [51:27:26<46:34, 12.48s/it]

 94%|█████████▍| 3376/3599 [51:27:32<38:48, 10.44s/it]

 94%|█████████▍| 3377/3599 [51:27:35<31:01,  8.39s/it]

 94%|█████████▍| 3378/3599 [51:27:40<26:47,  7.28s/it]

 94%|█████████▍| 3379/3599 [51:28:07<48:08, 13.13s/it]ERROR: [youtube] vU2PdefHTm4: Video unavailable
 94%|█████████▍| 3380/3599 [51:28:07<34:15,  9.39s/it]

 94%|█████████▍| 3381/3599 [51:28:16<33:10,  9.13s/it]

 94%|█████████▍| 3382/3599 [51:28:26<34:34,  9.56s/it]ERROR: [youtube] vWuEDSbtmlc: Video unavailable
 94%|█████████▍| 3383/3599 [51:28:27<24:41,  6.86s/it]

 94%|█████████▍| 3384/3599 [51:28:33<23:53,  6.67s/it]

 94%|█████████▍| 3385/3599 [51:28:38<21:32,  6.04s/it]

 94%|█████████▍| 3386/3599 [51:28:43<20:52,  5.88s/it]

 94%|█████████▍| 3387/3599 [51:28:48<19:08,  5.42s/it]

 94%|█████████▍| 3388/3599 [51:29:24<51:41, 14.70s/it]

 94%|█████████▍| 3389/3599 [51:29:34<46:13, 13.21s/it]

 94%|█████████▍| 3390/3599 [51:29:42<40:42, 11.69s/it]

 94%|█████████▍| 3391/3599 [51:29:55<42:32, 12.27s/it]

 94%|█████████▍| 3392/3599 [51:30:04<38:35, 11.19s/it]

 94%|█████████▍| 3393/3599 [51:30:11<33:46,  9.84s/it]

 94%|█████████▍| 3394/3599 [51:30:15<28:06,  8.22s/it]

 94%|█████████▍| 3395/3599 [51:30:19<23:54,  7.03s/it]

 94%|█████████▍| 3396/3599 [51:30:34<31:17,  9.25s/it]

 94%|█████████▍| 3397/3599 [51:30:40<28:21,  8.42s/it]

 94%|█████████▍| 3398/3599 [51:30:48<27:12,  8.12s/it]ERROR: [youtube] vmYaUj98wdM: Video unavailable
 94%|█████████▍| 3399/3599 [51:30:48<19:32,  5.86s/it]

 94%|█████████▍| 3400/3599 [51:30:53<17:43,  5.35s/it]ERROR: [youtube] voa1GiW2Sfw: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 94%|█████████▍| 3401/3599 [51:30:53<12:57,  3.93s/it]

 95%|█████████▍| 3402/3599 [51:30:59<14:16,  4.35s/it]

 95%|█████████▍| 3403/3599 [51:31:10<21:33,  6.60s/it]

 95%|█████████▍| 3404/3599 [51:31:25<29:28,  9.07s/it]

 95%|█████████▍| 3405/3599 [51:31:30<25:28,  7.88s/it]

 95%|█████████▍| 3406/3599 [51:31:35<22:45,  7.07s/it]

 95%|█████████▍| 3407/3599 [51:31:47<26:48,  8.38s/it]

 95%|█████████▍| 3408/3599 [51:31:57<28:06,  8.83s/it]

 95%|█████████▍| 3409/3599 [51:32:01<23:09,  7.32s/it]

 95%|█████████▍| 3410/3599 [51:32:05<20:33,  6.52s/it]ERROR: [youtube] w-s7ZNuZuAo: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 95%|█████████▍| 3411/3599 [51:32:06<14:50,  4.74s/it]

 95%|█████████▍| 3412/3599 [51:32:12<16:08,  5.18s/it]

 95%|█████████▍| 3413/3599 [51:32:18<16:29,  5.32s/it]

 95%|█████████▍| 3414/3599 [51:32:24<16:56,  5.49s/it]

 95%|█████████▍| 3415/3599 [51:32:32<19:18,  6.29s/it]

 95%|█████████▍| 3416/3599 [51:32:37<18:25,  6.04s/it]

 95%|█████████▍| 3417/3599 [51:32:57<31:02, 10.23s/it]

 95%|█████████▍| 3418/3599 [51:33:04<27:49,  9.22s/it]

 95%|█████████▍| 3419/3599 [51:33:07<22:25,  7.48s/it]

 95%|█████████▌| 3420/3599 [51:33:11<19:05,  6.40s/it]

 95%|█████████▌| 3421/3599 [51:33:16<17:26,  5.88s/it]

 95%|█████████▌| 3422/3599 [51:33:28<22:19,  7.57s/it]

 95%|█████████▌| 3423/3599 [51:33:35<22:10,  7.56s/it]

 95%|█████████▌| 3424/3599 [51:33:39<18:49,  6.45s/it]

 95%|█████████▌| 3425/3599 [51:33:44<17:52,  6.16s/it]

 95%|█████████▌| 3426/3599 [51:34:00<25:46,  8.94s/it]

 95%|█████████▌| 3427/3599 [51:34:06<22:58,  8.01s/it]

 95%|█████████▌| 3428/3599 [51:34:11<20:17,  7.12s/it]ERROR: [youtube] wPZGhx9Q_Jc: Video unavailable
 95%|█████████▌| 3429/3599 [51:34:11<14:34,  5.14s/it]

 95%|█████████▌| 3430/3599 [51:34:56<48:04, 17.07s/it]

 95%|█████████▌| 3431/3599 [51:35:03<39:02, 13.95s/it]ERROR: [youtube] wZAxwjumwKU: This video has been removed for violating YouTube's policy on violent or graphic content
 95%|█████████▌| 3432/3599 [51:35:04<27:46,  9.98s/it]ERROR: [youtube] wZnvIR6GSpQ: Video unavailable
 95%|█████████▌| 3433/3599 [51:35:04<19:47,  7.15s/it]

 95%|█████████▌| 3434/3599 [51:35:08<17:23,  6.32s/it]

 95%|█████████▌| 3435/3599 [51:35:14<16:30,  6.04s/it]ERROR: [youtube] waYwpbHkKjE: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 95%|█████████▌| 3436/3599 [51:35:14<11:59,  4.41s/it]

 95%|█████████▌| 3437/3599 [51:35:19<11:56,  4.42s/it]

 96%|█████████▌| 3438/3599 [51:35:45<28:58, 10.80s/it]

 96%|█████████▌| 3439/3599 [51:35:50<24:46,  9.29s/it]

 96%|█████████▌| 3440/3599 [51:36:09<32:19, 12.20s/it]

 96%|█████████▌| 3441/3599 [51:36:15<27:04, 10.28s/it]

 96%|█████████▌| 3442/3599 [51:36:20<22:14,  8.50s/it]ERROR: [youtube] weSEam9wX8E: Video unavailable
 96%|█████████▌| 3443/3599 [51:36:20<15:52,  6.11s/it]

 96%|█████████▌| 3444/3599 [51:36:26<15:20,  5.94s/it]

 96%|█████████▌| 3445/3599 [51:36:47<27:32, 10.73s/it]

 96%|█████████▌| 3446/3599 [51:36:52<22:31,  8.83s/it]

 96%|█████████▌| 3447/3599 [51:36:57<19:28,  7.69s/it]

 96%|█████████▌| 3448/3599 [51:37:03<18:14,  7.25s/it]

 96%|█████████▌| 3449/3599 [51:37:13<19:48,  7.93s/it]

 96%|█████████▌| 3450/3599 [51:37:22<21:06,  8.50s/it]

 96%|█████████▌| 3451/3599 [51:37:27<17:59,  7.29s/it]

 96%|█████████▌| 3452/3599 [51:38:20<51:11, 20.89s/it]ERROR: [youtube] wyCoAM9c6wA: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 96%|█████████▌| 3453/3599 [51:38:20<35:59, 14.79s/it]ERROR: [youtube] wyiLc4syeug: Video unavailable
 96%|█████████▌| 3454/3599 [51:38:21<25:28, 10.54s/it]

 96%|█████████▌| 3455/3599 [51:38:28<23:03,  9.61s/it]

 96%|█████████▌| 3456/3599 [51:38:32<18:47,  7.88s/it]

 96%|█████████▌| 3457/3599 [51:38:38<17:11,  7.26s/it]

 96%|█████████▌| 3458/3599 [51:38:43<15:55,  6.78s/it]

 96%|█████████▌| 3459/3599 [51:38:51<16:28,  7.06s/it]

 96%|█████████▌| 3460/3599 [51:38:56<14:58,  6.46s/it]ERROR: [youtube] xBmT_GvfhGM: Video unavailable
 96%|█████████▌| 3461/3599 [51:38:57<10:49,  4.71s/it]

 96%|█████████▌| 3462/3599 [51:39:03<11:29,  5.03s/it]

 96%|█████████▌| 3463/3599 [51:39:07<10:55,  4.82s/it]

 96%|█████████▌| 3464/3599 [51:39:11<10:11,  4.53s/it]ERROR: [youtube] xIMy0BO8gtk: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 96%|█████████▋| 3465/3599 [51:39:11<07:25,  3.32s/it]

 96%|█████████▋| 3466/3599 [51:39:20<10:39,  4.81s/it]

 96%|█████████▋| 3467/3599 [51:39:24<10:17,  4.68s/it]

 96%|█████████▋| 3468/3599 [51:39:31<11:26,  5.24s/it]

 96%|█████████▋| 3469/3599 [51:39:39<13:14,  6.11s/it]ERROR: unable to download video data: HTTP Error 403: Forbidden
 96%|█████████▋| 3470/3599 [51:39:40<10:08,  4.72s/it]

 96%|█████████▋| 3471/3599 [51:39:46<10:29,  4.92s/it]

 96%|█████████▋| 3472/3599 [51:39:50<10:14,  4.84s/it]

 96%|█████████▋| 3473/3599 [51:39:55<10:17,  4.90s/it]

 97%|█████████▋| 3474/3599 [51:40:00<10:05,  4.85s/it]

 97%|█████████▋| 3475/3599 [51:40:08<12:00,  5.81s/it]

 97%|█████████▋| 3476/3599 [51:40:15<12:29,  6.09s/it]

ERROR: unable to download video data: HTTP Error 403: Forbidden
 97%|█████████▋| 3477/3599 [51:40:26<15:34,  7.66s/it]

 97%|█████████▋| 3478/3599 [51:40:31<13:53,  6.89s/it]

 97%|█████████▋| 3479/3599 [51:40:36<12:23,  6.19s/it]

 97%|█████████▋| 3480/3599 [51:40:41<11:33,  5.83s/it]

 97%|█████████▋| 3481/3599 [51:40:57<17:45,  9.03s/it]

 97%|█████████▋| 3482/3599 [51:41:17<24:03, 12.34s/it]

 97%|█████████▋| 3483/3599 [51:41:22<19:35, 10.13s/it]

 97%|█████████▋| 3484/3599 [51:41:43<25:37, 13.37s/it]

 97%|█████████▋| 3485/3599 [51:41:56<25:05, 13.20s/it]

 97%|█████████▋| 3486/3599 [51:42:02<20:36, 10.94s/it]

 97%|█████████▋| 3487/3599 [51:42:06<16:36,  8.90s/it]ERROR: [youtube] xki4mu9o2nA: Video unavailable
 97%|█████████▋| 3488/3599 [51:42:06<11:49,  6.39s/it]

 97%|█████████▋| 3489/3599 [51:42:13<11:56,  6.51s/it]

 97%|█████████▋| 3490/3599 [51:42:18<10:49,  5.96s/it]

 97%|█████████▋| 3491/3599 [51:42:23<10:27,  5.81s/it]

 97%|█████████▋| 3492/3599 [51:42:28<09:51,  5.52s/it]

 97%|█████████▋| 3493/3599 [51:42:40<13:19,  7.55s/it]

 97%|█████████▋| 3494/3599 [51:42:45<11:26,  6.54s/it]

 97%|█████████▋| 3495/3599 [51:42:51<11:10,  6.45s/it]

 97%|█████████▋| 3496/3599 [51:42:55<10:04,  5.87s/it]

 97%|█████████▋| 3497/3599 [51:43:01<09:47,  5.76s/it]

 97%|█████████▋| 3498/3599 [51:43:11<11:42,  6.96s/it]ERROR: [youtube] y399ZfbscuE: Video unavailable
 97%|█████████▋| 3499/3599 [51:43:11<08:24,  5.05s/it]

 97%|█████████▋| 3500/3599 [51:43:15<07:46,  4.72s/it]

 97%|█████████▋| 3501/3599 [51:43:23<09:13,  5.64s/it]

 97%|█████████▋| 3502/3599 [51:43:27<08:20,  5.16s/it]

 97%|█████████▋| 3503/3599 [51:43:32<08:24,  5.26s/it]

 97%|█████████▋| 3504/3599 [51:43:40<09:16,  5.86s/it]

 97%|█████████▋| 3505/3599 [51:43:49<10:45,  6.87s/it]

 97%|█████████▋| 3506/3599 [51:43:54<09:58,  6.43s/it]

 97%|█████████▋| 3507/3599 [51:43:58<08:32,  5.57s/it]

 97%|█████████▋| 3508/3599 [51:44:03<08:00,  5.28s/it]

 97%|█████████▋| 3509/3599 [51:44:08<08:02,  5.37s/it]

 98%|█████████▊| 3510/3599 [51:44:12<07:19,  4.94s/it]

 98%|█████████▊| 3511/3599 [51:44:18<07:28,  5.09s/it]

 98%|█████████▊| 3512/3599 [51:44:26<08:52,  6.12s/it]

 98%|█████████▊| 3513/3599 [51:44:31<08:21,  5.84s/it]

 98%|█████████▊| 3514/3599 [51:44:37<08:16,  5.84s/it]

 98%|█████████▊| 3515/3599 [51:44:44<08:30,  6.08s/it]

 98%|█████████▊| 3516/3599 [51:44:50<08:35,  6.20s/it]ERROR: [youtube] yT6GGzok2Wk: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 98%|█████████▊| 3517/3599 [51:44:51<06:09,  4.51s/it]

 98%|█████████▊| 3518/3599 [51:45:01<08:30,  6.30s/it]

 98%|█████████▊| 3519/3599 [51:45:14<10:52,  8.15s/it]

 98%|█████████▊| 3520/3599 [51:45:20<10:04,  7.66s/it]

 98%|█████████▊| 3521/3599 [51:45:25<08:53,  6.84s/it]ERROR: [youtube] yYofGpDTok4: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 98%|█████████▊| 3522/3599 [51:45:26<06:22,  4.97s/it]ERROR: [youtube] yZqRd36Cw0A: This video has been removed for violating YouTube's Terms of Service
 98%|█████████▊| 3523/3599 [51:45:26<04:36,  3.64s/it]

 98%|█████████▊| 3524/3599 [51:45:31<04:51,  3.89s/it]

 98%|█████████▊| 3525/3599 [51:45:37<05:32,  4.49s/it]

 98%|█████████▊| 3526/3599 [51:45:47<07:26,  6.11s/it]

 98%|█████████▊| 3527/3599 [51:45:53<07:34,  6.31s/it]

 98%|█████████▊| 3528/3599 [51:46:10<11:15,  9.51s/it]

 98%|█████████▊| 3529/3599 [51:46:17<09:57,  8.53s/it]

 98%|█████████▊| 3530/3599 [51:46:22<08:34,  7.46s/it]

 98%|█████████▊| 3531/3599 [51:46:32<09:23,  8.29s/it]

 98%|█████████▊| 3532/3599 [51:46:43<10:06,  9.05s/it]

 98%|█████████▊| 3533/3599 [51:46:51<09:43,  8.84s/it]

 98%|█████████▊| 3534/3599 [51:46:58<08:55,  8.23s/it]ERROR: [youtube] ylOtyrLGj7I: Video unavailable
 98%|█████████▊| 3535/3599 [51:46:58<06:18,  5.92s/it]ERROR: [youtube] yo9hYU_D7is: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 98%|█████████▊| 3536/3599 [51:46:59<04:31,  4.31s/it]ERROR: [youtube] yrgZqLQZ994: Video unavailable
 98%|█████████▊| 3537/3599 [51:46:59<03:16,  3.17s/it]

 98%|█████████▊| 3538/3599 [51:47:05<04:01,  3.95s/it]

 98%|█████████▊| 3539/3599 [51:47:11<04:38,  4.64s/it]

 98%|█████████▊| 3540/3599 [51:47:15<04:14,  4.31s/it]

 98%|█████████▊| 3541/3599 [51:47:20<04:32,  4.70s/it]

 98%|█████████▊| 3542/3599 [51:47:49<11:09, 11.74s/it]ERROR: [youtube] yxaYxVDRqUE: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
 98%|█████████▊| 3543/3599 [51:47:49<07:49,  8.38s/it]

 98%|█████████▊| 3544/3599 [51:47:55<07:04,  7.72s/it]

 98%|█████████▊| 3545/3599 [51:48:00<06:10,  6.86s/it]

 99%|█████████▊| 3546/3599 [51:48:05<05:31,  6.25s/it]

 99%|█████████▊| 3547/3599 [51:48:12<05:37,  6.49s/it]

 99%|█████████▊| 3548/3599 [51:48:17<05:13,  6.15s/it]

 99%|█████████▊| 3549/3599 [51:48:24<05:13,  6.28s/it]

 99%|█████████▊| 3550/3599 [51:48:30<04:57,  6.08s/it]

 99%|█████████▊| 3551/3599 [51:48:57<09:57, 12.45s/it]ERROR: [youtube] z9tlw8N1u08: Video unavailable
 99%|█████████▊| 3552/3599 [51:48:57<06:57,  8.88s/it]

 99%|█████████▊| 3553/3599 [51:49:11<07:45, 10.13s/it]ERROR: [youtube] zAE0VhzHqCI: Sign in to confirm your age. This video may be inappropriate for some users. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 99%|█████████▊| 3554/3599 [51:49:12<05:42,  7.61s/it]

 99%|█████████▉| 3555/3599 [51:49:17<05:01,  6.86s/it]

 99%|█████████▉| 3556/3599 [51:49:23<04:35,  6.41s/it]

 99%|█████████▉| 3557/3599 [51:49:28<04:14,  6.05s/it]

 99%|█████████▉| 3558/3599 [51:49:35<04:18,  6.30s/it]ERROR: [youtube] zFZHsniFPJ8: Video unavailable
 99%|█████████▉| 3559/3599 [51:49:35<03:02,  4.57s/it]

 99%|█████████▉| 3560/3599 [51:49:42<03:21,  5.17s/it]

 99%|█████████▉| 3561/3599 [51:49:54<04:40,  7.38s/it]

 99%|█████████▉| 3562/3599 [51:49:59<03:57,  6.43s/it]

 99%|█████████▉| 3563/3599 [51:50:11<04:54,  8.17s/it]

 99%|█████████▉| 3564/3599 [51:50:19<04:44,  8.12s/it]

 99%|█████████▉| 3565/3599 [51:50:25<04:13,  7.46s/it]

 99%|█████████▉| 3566/3599 [51:50:32<04:03,  7.38s/it]ERROR: [youtube] zN53YAwStxU: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
 99%|█████████▉| 3567/3599 [51:50:33<02:50,  5.34s/it]

 99%|█████████▉| 3568/3599 [51:50:37<02:37,  5.08s/it]

 99%|█████████▉| 3569/3599 [51:50:42<02:32,  5.10s/it]

 99%|█████████▉| 3570/3599 [51:50:50<02:49,  5.86s/it]

 99%|█████████▉| 3571/3599 [51:51:37<08:34, 18.37s/it]

 99%|█████████▉| 3572/3599 [51:51:46<06:58, 15.50s/it]

 99%|█████████▉| 3573/3599 [51:52:04<07:00, 16.19s/it]

 99%|█████████▉| 3574/3599 [51:52:12<05:41, 13.65s/it]

 99%|█████████▉| 3575/3599 [51:52:16<04:19, 10.82s/it]

 99%|█████████▉| 3576/3599 [51:52:24<03:46,  9.84s/it]

 99%|█████████▉| 3577/3599 [51:52:36<03:52, 10.56s/it]

 99%|█████████▉| 3578/3599 [51:52:44<03:28,  9.91s/it]

 99%|█████████▉| 3579/3599 [51:52:50<02:53,  8.67s/it]

 99%|█████████▉| 3580/3599 [51:53:01<02:59,  9.46s/it]

 99%|█████████▉| 3581/3599 [51:53:14<03:06, 10.36s/it]

100%|█████████▉| 3582/3599 [51:53:19<02:32,  8.99s/it]

100%|█████████▉| 3583/3599 [51:53:32<02:39,  9.96s/it]

100%|█████████▉| 3584/3599 [51:53:36<02:03,  8.22s/it]

100%|█████████▉| 3585/3599 [51:53:41<01:41,  7.28s/it]

100%|█████████▉| 3586/3599 [51:53:47<01:29,  6.86s/it]

100%|█████████▉| 3587/3599 [51:53:56<01:31,  7.59s/it]

100%|█████████▉| 3588/3599 [51:54:01<01:16,  6.91s/it]ERROR: [youtube] zkHyLHhh3Pg: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
100%|█████████▉| 3589/3599 [51:54:02<00:50,  5.01s/it]

100%|█████████▉| 3590/3599 [51:54:11<00:55,  6.17s/it]

100%|█████████▉| 3591/3599 [51:54:16<00:46,  5.78s/it]

100%|█████████▉| 3592/3599 [51:54:25<00:46,  6.67s/it]

100%|█████████▉| 3593/3599 [51:55:05<01:40, 16.70s/it]

100%|█████████▉| 3594/3599 [51:55:54<02:12, 26.54s/it]

100%|█████████▉| 3595/3599 [51:55:59<01:19, 19.99s/it]

100%|█████████▉| 3596/3599 [51:56:04<00:47, 15.68s/it]ERROR: [youtube] zudIqNa5vHk: Video unavailable
100%|█████████▉| 3597/3599 [51:56:05<00:22, 11.16s/it]

100%|█████████▉| 3598/3599 [51:56:11<00:09,  9.47s/it]

100%|██████████| 3599/3599 [51:56:21<00:00, 51.95s/it]

# Staeling even mORE MOOREE DATA FROM YOUTUUBEEEE

In [1]:
import json
from pathlib import Path
import time

crawled_ids = []
with open("logs/additional_videos_crawled.json", "r") as f:
    crawled_ids = json.load(f)
crawled_ids[:3]

[{'id': 'XuXLSagyZcU'}, {'id': 'd3dmIPox05o'}, {'id': 'JjNwVWsIm8U'}]

In [19]:
import os
from yt_dlp import YoutubeDL


def download_video(video_idx: str, output_folder: str = "downloads") -> dict:

    os.makedirs(output_folder, exist_ok=True)
    url = f"https://www.youtube.com/watch?v={video_idx}"

    base_opts = {
        "quiet": True,
        "js_runtimes": {"node": {}}
    }

    try:
        # ---- metadata check ----
        with YoutubeDL(base_opts) as ydl:
            info = ydl.extract_info(url, download=False)

        # Estimated filesize in bytes
        video_filesize = info.get("filesize") or info.get("filesize_approx")
        duration = info.get("duration")

        if duration is None or duration > 1800:
            return {"video_id": video_idx, "error": "video too long"}

        if video_filesize and video_filesize > 500 * 1024 * 1024:
            return {"video_id": video_idx, "error": "video too large"}

        # ---- video download ----
        video_opts = {
            **base_opts,
            "format": "bestvideo[height<=1080][ext=mp4]/bestvideo[height<=1080]/bestvideo/best",
            "outtmpl": os.path.join(output_folder, "%(id)s_video.%(ext)s"),
            "max_filesize": 500 * 1024 * 1024,
            "noplaylist": True,
            "retries": 3,
            "fragment_retries": 3
        }

        with YoutubeDL(video_opts) as ydl:
            ydl.download([url])

        # ---- audio download ----
        audio_opts = {
            **base_opts,
            "format": "bestaudio[ext=m4a]/bestaudio/best",
            "outtmpl": os.path.join(output_folder, "%(id)s_audio.%(ext)s"),
            "postprocessors": [{
                "key": "FFmpegExtractAudio",
                "preferredcodec": "mp3",
                "preferredquality": "192"
            }],
            "noplaylist": True,
            "retries": 3,
            "fragment_retries": 3
        }

        with YoutubeDL(audio_opts) as ydl:
            ydl.download([url])

        return {
            "video_id": info["id"],
            "title": info.get("title"),
            "video_file": f"{info['id']}_video.mp4",
            "audio_file": f"{info['id']}_audio.mp3"
        }

    except Exception as e:
        return {"video_id": video_idx, "error": str(e)}

In [20]:
output_jsonl = Path("logs/downloaded_crawled_videos.jsonl")
output_jsonl.parent.mkdir(parents=True, exist_ok=True)

total = len(crawled_ids)

with open(output_jsonl, "a", buffering=1) as f:
    for i, item in enumerate(crawled_ids, start=1):

        vid = item["id"]

        result = download_video(
            video_idx=vid,
            output_folder="crawled_downloads"
        )

        if "error" in result:
            record = {
                "id": vid,
                "status": "error",
                "error": result["error"]
            }
        else:
            record = {
                "id": vid,
                "status": "success"
            }

        f.write(json.dumps(record) + "\n")

        if i % 100 == 0:
            print(f"processed {i} / {total}")

        time.sleep(1)

WARNING: [youtube] XuXLSagyZcU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] 7xFlk6YKJYK: Video unavailable
ERROR: [youtube] kSuVatp3xpQ: This video is not available

WARNING: [youtube] wjFlmKd6J1E: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] RAsYSKjHsOk: This video is not available
WARNING: [youtube] 0ulzZFnBAD4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] [jsc] Remote component challenge solver script (node) was skipped. It may be required to solve JS challenges. You can enable the download with  --remote-components ejs:github  (recommended). For more information and alternatives, refer to  https://github.com/yt-dlp/yt-dlp/wiki/EJS
WARNING: [youtube] QIVeA0mo8eM: n challenge solving failed: Some formats may be missing. Ensure you have a supported JavaScript runtime and challenge solver script distribution installed. Review any warnings presented before this message. For more details, refer to  https://github.com/yt-dlp/yt-dlp/wiki/EJS

WARNING: [youtube] swhUAMWApB4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] uCYAbMfIt58: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] mixNHFsh6nY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] EaWHUjNt2cs: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 7z9KPTI5ixI: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] yWHbBD0GuE0: This video is not available

ERROR: [youtube] Oaw3S5AmiRo: This video is not available

WARNING: [youtube] h273UuGeLPE: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] X2OLOYKGxGs: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] A9YWsHm4VyU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] TkqD6n1UPjg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] S11xAkqr5lU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] oARpjtRLcT8: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] yFvWAOPhXps: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

[download] Got error: (<HTTPSConnection(host='rr2---sn-a5oxu-uoal.googlevideo.com', port=443) at 0x126317a50>, 'Connection to rr2---sn-a5oxu-uoal.googlevideo.com timed out. (connect timeout=20.0)'). Giving up after 3 retries

WARNING: [youtube] x8GWgKuB9Oc: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] SpCYIvo7hwY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] TOAN8xG1L78: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

processed 100 / 8259

WARNING: [youtube] eTeXqanfpCY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] OpyIY7ixgI8: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] qp7ic5RMiDE: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] XD7cnmvlc3E: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] eRRH48mwBn0: This video is not available

WARNING: [youtube] rxAOHZoqwnk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 2yRmaXJYEbs: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] 2yRmaXJYEbs: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] k9cbTr2To8Y: This video is not available

WARNING: [youtube] d4HwO3ZUCUw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] DUY9K457dig: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 0QtrG4xb90k: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 4WyblnmqPe8: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] oyW001b1Ye8: This video is not available

WARNING: [youtube] 6l5a2RNUid4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] lTiLwpaqiVY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] xhiMP0PXmPc: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] G5BWB4JCKe4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] KpvNE7IT2f8: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] HWpAhOuS78M: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] A5GKvcaZsiM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 0uUybjevBBE: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Zs8Dwpl7zcA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] qghpWJPvtWc: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] qghpWJPvtWc: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] MD5Crr7AmDg: This video is not available

WARNING: [youtube] oe7pO740tsk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 1TP1iySJSWU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] xeCjHjMJAq0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] kfD1oJ3iMfI: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

processed 200 / 8259

WARNING: [youtube] QkPMiyVnf0U: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] QkPMiyVnf0U: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] nkNgXNQgLNw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] qvToGSSf34M: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 8pwAvHXPg94: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] N31370YSr90: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 8kpPJNUrQvU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 6jHclW25PDc: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] 6jHclW25PDc: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] k3FjKHiH860: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] k3FjKHiH860: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] rE9T7MgQT3A: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] 9TrI6Gu9wH8: This video is not available

WARNING: [youtube] UPPCoSuXzK4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] gqqTcrRP5h4: This video is not available

WARNING: [youtube] kLuodAXWTFo: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] EUxgt3tbquM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 5IMkCOQVTe0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
[download] Got error: (<HTTPSConnection(host='rr4---sn-a5oxu-uoae.googlevideo.com', port=443) at 0x125c93250>, 'Connection to rr4---sn-a5oxu-uoae.googlevideo.com timed out. (connect timeout=20.0)'). Giving up after 3 retries
[download] Got error: (<HTTPSConnection(host='rr4---sn-a5oxu-uoae.googlevideo.com', port=443) at 0x1262a41d0>, 'Connection to rr4---sn-a5oxu-uoae.googlevideo.com timed out. (connect timeout=20.0)'). Giving up after 3 retries

WARNING: [youtube] 3jU1Eo6AdEk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Bx7i0Qyul60: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] rqno7K2zXi4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] goHKzhwdXiU: This video is not available

ERROR: [youtube] bi9rzbtBY4U: This video is not available

processed 300 / 8259

WARNING: [youtube] 9HZXnR3sM6A: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] GarNfja65WQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ln86TBdVdec: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] WMBdE6dfYPs: This video is not available

WARNING: [youtube] 76TRoGOlGZA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] j7NqPr6CxWs: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 9JlNWRp9bBQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 9JlNWRp9bBQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] D4zglMLEsWw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] XegfV1xSvj0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] bob5g1Vuu04: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] 5jlkUbFNGEs: This video is not available

WARNING: [youtube] 39mp0btDPSY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] vE3ElN3SQz0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] x4w2brVzyrQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Z2m2oeaU7KM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] sJxZUhJCUZw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] KL9mAVuO0LA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] W2qcNO1NKcM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] N9k4wUsu9j4: This video is not available

WARNING: [youtube] xYpZ1SWdcxg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] HJzRcKzsBcY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] HJzRcKzsBcY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 5gFZBnYXVgk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

[download] Got error: (<HTTPSConnection(host='rr2---sn-a5oxu-uoas.googlevideo.com', port=443) at 0x124d57110>, 'Connection to rr2---sn-a5oxu-uoas.googlevideo.com timed out. (connect timeout=20.0)'). Giving up after 3 retries

ERROR: [youtube] Yie9Bgo69m8: This video is not available

WARNING: [youtube] OqH9RoUNG24: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] KUT4jfwn5Yo: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] IHxqiWdV6rQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] OffTzMVhvDA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] OffTzMVhvDA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] R18hwf4YNoo: This video is not available

WARNING: [youtube] VLEhv46yad4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] 3hEqJg2K3Mw: Video unavailable

WARNING: [youtube] Mgm7DygTPvk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] VTrkDPUUQxw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 5hAaPl9OEXM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] PSfwcsk59II: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] 0NkhM0RiUUc: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] NkDdR3I6ALM: This video is not available

ERROR: [youtube] zkfMAE4FTe8: This video is not available

processed 400 / 8259

WARNING: [youtube] eQmNYjP6mJo: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ZOMiENsrhPU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] drEukAUzUuI: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] UvKTcoQyP4U: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] RX24fxxtUwo: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] poMesMZXRUg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] z5kY3brdmuQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] KegnZEFpczU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ssLzlChBejY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ssLzlChBejY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] I2okDrvzy2U: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] HbeIDdC9jDg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] JbeHav5oBEc: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] sXAEqY0utgs: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 2dk12LzjGjg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 2dk12LzjGjg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Ptv5XLC9u6E: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] emZqJiiKZJU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] ASvm8jcIrng: This video is not available
WARNING: [youtube] BH4rlk0NLkc: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 1ioFskl2Xpg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 1ioFskl2Xpg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] S89UAXtjOUU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] MaDFvaHWWu0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] d8hB1A1ohRI: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Au9ys3qtchc: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ByF7swYddEQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] bV86EZdREjw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] h2gaQwA78OY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] h2gaQwA78OY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] mkXdGEgK5o8: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] cnD85XIJfiI: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] trNCUTinbNg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] 1NQ0IFMiOZA: This video is not available

WARNING: [youtube] Nqq1e62T2w8: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] PZJrztZdcyw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] ouu5XGrBGOQ: This video is not available
WARNING: [youtube] psNe3VtgmpA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

processed 500 / 8259

WARNING: [youtube] VSbfDw8OSfY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] FVG8n1R2jKg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Wgo6ojpOTUk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] L0097jPH3NI: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] JjfjvqnuDhY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] P8GiOP0jv8g: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] P8GiOP0jv8g: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] cXNTzFlglYo: This video is not available

WARNING: [youtube] Nc1VpH49qCw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] ySSKkInqGpI: This video is not available
WARNING: [youtube] wcDGCQP7xRM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
[download] Got error: (<HTTPSConnection(host='rr4---sn-a5oxu-uoas.googlevideo.com', port=443) at 0x1260d9b10>, 'Connection to rr4---sn-a5oxu-uoas.googlevideo.com timed out. (connect timeout=20.0)'). Giving up after 3 retries
WARNING: [youtube] 8SVriqMaG1g: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 8SVriqMaG1g: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] lGoRLHzwkRY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

[download]  10.3% of   58.38MiB at  Unknown B/s ETA Unknown

[download] Got error: 2000 bytes read, 10011566 more expected. Giving up after 3 retries

WARNING: [youtube] 4DXOn3bSao0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] lREFt6TqapU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] tcuxKaDlHrc: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 2lY8XowfKEA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] fMFVZPpavO4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube:truncated_id] 8bh2Hewfp0: Incomplete YouTube ID 8bh2Hewfp0. URL https://www.youtube.com/watch?v=8bh2Hewfp0 looks truncated.
ERROR: [youtube] HvM5SD5st2o: This video is not available

WARNING: [youtube] BqDuJq6kcpA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] BqDuJq6kcpA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ksCiFCTQAiA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ksCiFCTQAiA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] DF90xW7sXUI: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] WegBlG25Mto: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] LsATOvq0Yws: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] KubShKFECJ0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] jUoNCYXvY5Q: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 3QwtNbCycJ0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] X2C96VJxYto: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ZPCJDAgNEBg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] zsdVdgEQsn8: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] y5g2EnQbUmg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 7c455TdSyKU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 9xekEnaXVAU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 9xekEnaXVAU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Jnckkfa57kY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] NSQ6Skkfozk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 6NqeFpPOPLg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] k7UhaeWFX8I: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] 4vlAphWQeuk: This video is not available

processed 600 / 8259

WARNING: [youtube] CQfASD0EbH4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] nDAhR1WODtw: This video is not available

ERROR: [youtube] Xb1FnTksZjo: This video is not available

WARNING: [youtube] KPVyPnwx2zk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] FGKo3Cen2cU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] LIZKDoCdv6I: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] EmfQKAA3XJw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] J5xgTECgHFQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] zRN97355yvA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

[download] Got error: HTTP Error 500: Internal Server Error. Giving up after 3 retries

ERROR: [youtube] quDJ7kTEWZc: This video is not available

WARNING: [youtube] JgjyITiVJQ4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] d9N7jr380C8: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] fbcOpyri4t0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] Ph60AEakiLQ: This video is not available

WARNING: [youtube] ZSZRmyqltPQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] tTjE7UDTbXM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 2FYujEIqRXM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ECLL30N0V0I: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] LAsLhBNT1kM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] caJHktV3LXY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] eCMJ6gFoCQM: This video is not available

ERROR: [youtube] 7vec8rF2Zlw: This video is not available

WARNING: [youtube] xqQb4vHgkOA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

processed 700 / 8259

WARNING: [youtube] 6G3ZZIcQ7nA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] In3OoKfqwCQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] o9koNh5oTHI: This video is not available

WARNING: [youtube] mIfUNWIBaKA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] Qd5tlPh4y70: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 5AYza0mbLZE: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] TDWMzsykVVI: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 0OTozoxb8cs: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 96Fw6H0ZG84: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] HGwIbKk1GqU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] i8T3UKprkRI: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] TXhQEiWCwyE: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] FjWKFxUSzTc: This video is not available

WARNING: [youtube] SU0JhyO6xU8: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] dQCIXqqoBuE: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] chn3um3hB3M: This video is not available
WARNING: [youtube] nLSegs05TZo: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 4vCqu9UIWGw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] NVVoLK6C2o8: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] WEMq58voE5Q: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] gsOLu22hvQI: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] XV8qeoMIjoQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] dsztx8Wu5PU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] u4DObpuRVWA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] tPzwrLyZmaI: This video is not available

ERROR: [youtube] AmJSp7fRFaE: Sign in to confirm your age. This video may be inappropriate for some users. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies

WARNING: [youtube] CXljDxHC0UE: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 7w9QigKZgmU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Y9ZvgUPPkSQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] CghPN6Cmx00: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

processed 800 / 8259
[download]  71.0% of   78.73MiB at    7.02MiB/s ETA 00:03

[download] Got error: 382955 bytes read, 9921286 more expected. Giving up after 3 retries

WARNING: [youtube] 4ZCpqywOiDs: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] BkPsX4TgJ1g: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] O4Iwkp0kVFc: This video is not available

WARNING: [youtube] Fj5Gnt7EuRg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] AlOqqHLZyaM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] AlOqqHLZyaM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] anFXfUAwxjQ: This video is not available
WARNING: [youtube] 0vFluDRpSGc: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Z8Pij5NNuHM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] yoCOpWLf3CM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 0TBejr71qGE: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 2HzwcnfQnu0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 6FUmapkqPn0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] imvmoTK59nc: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 4mgipJWlGng: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Ut8GWtFLDuE: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] jNstXdgO6qw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] BAgDdKOhjj0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] mrUMvhUoCzM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Ya0y1tLRqSs: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] gviLtf5jq14: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] gviLtf5jq14: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] F6pL0Nzyorg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ThWLBYts8RY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ThWLBYts8RY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] zlm1XSjpYLE: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] TYPyVeCen1s: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 4GIcaYVyf54: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] JtYdUJ092Kk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] JtYdUJ092Kk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] FDRqVYomTW4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] yVwhnkZE3aM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] L5Fr1NK9qnY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] L5Fr1NK9qnY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] elGBD3eGSIM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] g9R9IKQFJT0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] qeUM1WDoOGY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

processed 900 / 8259

WARNING: [youtube] RlwdTZIJvc4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] RlwdTZIJvc4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 16zGjyJDiOY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] 8jxK4KnaDQ0: This video is not available

ERROR: [youtube] QOx35v8c5nQ: This video is not available
ERROR: [youtube] SliD3HWzOKM: This video is not available

WARNING: [youtube] cjoKekWWEbI: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] J8YCXLFcoxU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 063cPw7uTMs: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] BrNFOSqAq04: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 5k5eF90n2kw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Z81lihoF4yE: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ftUkxuoAOJM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 0WWedPsHjFk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] rdmAqDkGEOA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 5s1R3uzRLtI: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 07KpGFkPK2E: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] zluwGmNkMdg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] sjHArKxcCQg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 2D8vd7mwcL8: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] qHGtCC0RC30: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] O58N8Mmv0QU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] e0knYSQgNV0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] cBH4HVLihUQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] cBH4HVLihUQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ZMBR8LiS5Og: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 8BIOwh59SiM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] 1XjicOeOJOQ: This video is not available
WARNING: [youtube] D4YAve2Upsk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] D4YAve2Upsk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] hH4WOTnNfzo: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] gbrIDRuvxX4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] sFPia3gITy0: This video is not available

WARNING: [youtube] 4GonaOW9y8Y: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] DqQvj2v85SI: This video is not available

WARNING: [youtube] 8CTfDDhb5CM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

processed 1000 / 8259

ERROR: [youtube] cWlxvqohZrM: This video is not available

WARNING: [youtube] be5x5u5i09I: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 2gF3decfnLA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] srtk6PwdR0Q: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] mJBDJYkLBZY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Nby0afEfBx0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] L5ywsyRpYTw: This video is not available
ERROR: [youtube] ee6r3JjujW4: This video is not available

WARNING: [youtube] dkuNmfFOZwU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] E0zGFv69pA4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] QQILo5JEzTY: This video is not available
WARNING: [youtube] teoCD9xKRsA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Apl9ZIep2Qg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] c5PXt6Ysf7s: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] c5PXt6Ysf7s: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] XmBApspOVdM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] KvrfOAqTj7E: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Hm7a4WUJDvM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] N2hssAyomdU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] TuPVPBLUOoY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 7PjoW6u1Y7c: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] jfZQ5AyA4oI: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ES0JdsFJcfU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ES0JdsFJcfU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] UZBReZE7b74: This video is not available
WARNING: [youtube] F8aeK3r237s: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Mg1nfNtCy7Y: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] sT8CHVceWTk: This video is not available
WARNING: [youtube] 8fgmbTOAkHY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] wDOWRGJpg70: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] zaoURh8yE00: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 0CnBJZqlHZc: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] f4RhCkdes0g: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] f4RhCkdes0g: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] f4RhCkdes0g: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 5gcsVn7nOZg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

processed 1100 / 8259

WARNING: [youtube] VZlNmoGOsD0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] sTzwttLZXYI: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] sTzwttLZXYI: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] ngrSavGNRlQ: This video is not available

WARNING: [youtube] CkOwbyipJ4A: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] yrsYTaKcQDA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] yrsYTaKcQDA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] QXaHtAVSm9g: This video is not available

WARNING: [youtube] T2nQvRB3aU0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 9QmMz8qKwvw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] PjMienp6usc: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] T9KtXolCZeI: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] T9KtXolCZeI: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] i3txesLa0kE: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 4i5hy9puxtk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Zj5wVUtTAgU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] kUXWVH8oH3Y: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] kUXWVH8oH3Y: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] 1txpepo455M: This video is not available

WARNING: [youtube] buhtYz7l64k: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] buhtYz7l64k: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] vvmHabWEWpI: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] bAWHxM0i7P4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] F58C8Y8Bt08: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] nKOFl4u9lXY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 8BZAW1tcnv0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] IDXrDJ9cNWM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] rrVbBMA9X4I: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 5nJrRUcYRZs: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] yf8QKGGUYOg: Video unavailable

WARNING: [youtube] FVeuv6QRwZ0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 99VohLdLgKo: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] K7NTi02kSpw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] JtVGSTKBK58: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] eu6EL9LWyBs: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

processed 1200 / 8259

ERROR: [youtube] c9XdTIaPnRk: This video is not available

WARNING: [youtube] hlajmIPiphk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 47Pe0pdmQE0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] jmgcgz5zSH0: This video is not available
WARNING: [youtube] PisBr8yd1Xg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] JdHZFZ6yceg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] hlrulKMcWk0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] hlrulKMcWk0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] hlrulKMcWk0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] xjuOyBWJFkI: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] TNBlVtpIuFk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] mjmQp4OSqbo: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] YukPleY6RHw: This video is not available

WARNING: [youtube] qiYBT5e8qKM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] NDk1GeKDd9s: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] qEeGgDhiizQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] W1OMcAOPDCs: This video is not available
WARNING: [youtube] byLwqLfzoO4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ZGLhbzhfR5M: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] HiMHLL6O3nw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] HiMHLL6O3nw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] m39lt0dHxDY: This video is not available

WARNING: [youtube] 2VPhXHwrHGk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Rxwsi3tbCyE: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ctuhi58SjTk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] obge50Drmhw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] fwsZcmg6MBg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] REmmAzuqKUY: This video is not available

processed 1300 / 8259

ERROR: [youtube] 3KgfuqrLonw: This video is not available
ERROR: [youtube] TJaoebi3OMg: Sign in to confirm your age. This video may be inappropriate for some users. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies

WARNING: [youtube] Ci6Ip122aFI: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] AEAg5LDjnG0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] AZSTtzDwBUM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] AhSgQbGrWFM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] RWto3kAcsIg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] qQl6j8VWJUk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] xEOlOIgzFXk: This video is not available

WARNING: [youtube] AnRe7jVVEew: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] THhlirFJh6Y: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Kx7aIjxls0s: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] xCvkVBKFu5k: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] C9GUSe0o328: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] C9GUSe0o328: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] qBkUESAGVTE: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] C62bkB1EazM: This video is not available
WARNING: [youtube] J0nvmg2Kl5s: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] cSWzh2cqIb4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] cSWzh2cqIb4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] sWsqph4TKo4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] zBe3igaCVPo: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ITWyVbdA9IU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] vTwFFNgeBNw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Y42pbuiiN8s: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] zcMcfaf3iiQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] lzjGfjb1RxQ: This video is not available

WARNING: [youtube] C0hh095VbHw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] psGDf2VrvK8: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ffOv6EH8KNg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] tcaJgnAm0pk: Video unavailable

WARNING: [youtube] SIn3kZAUnzM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

processed 1400 / 8259

WARNING: [youtube] cjJK429tPa0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] h0lSVNf71mQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] h0lSVNf71mQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] dDYiSJjMhqQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] dDYiSJjMhqQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] kZXpZdUunEk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] KrsBqc1ANzo: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] yBfKS6WRIXc: This video is not available

WARNING: [youtube] W7MgS9QnSJY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] jHjmpV9OpPs: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 5vumxXx5jfA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] FcZq4XvgEGc: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] l6fQVC9Usg4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] mPWgx5ZQuVw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] mPWgx5ZQuVw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 4OU3ajcqtio: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] It3DRGLS7jY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] oQpWPPrBJUM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] oQpWPPrBJUM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] nYGL1NvX3wM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ZJnDgd1ZlUA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] eU8GdAyCe5w: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] xDAPuVtqUzA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ryTk51KVtew: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 1rCFcu0hJsw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] NRN04GXdvFg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] 5kHLG1LmtGk: This video is not available

WARNING: [youtube] 5MIX2bbd0Mc: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 5MIX2bbd0Mc: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

processed 1500 / 8259

ERROR: [youtube] yNs8l2c4pvc: This video is not available

WARNING: [youtube] xrEEPdgafQo: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] xrEEPdgafQo: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] 6QwH73G8HgI: This video is not available
WARNING: [youtube] GrNA4h3gPqU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] GrNA4h3gPqU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 9b1sfsFmBF8: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] mwn8pnGbgHY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] algwn5OUSIk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] algwn5OUSIk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 4UNWzY9Y39s: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] mcKeXIDXreo: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] mcKeXIDXreo: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 5LGZ3StgLDw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] yRuTk4PcJeg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] dRyfKG7J6I0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] HfbHHb31p8g: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] HfbHHb31p8g: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] AQyviWQVTP8: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] RGBQX05MxPw: This video is not available
WARNING: [youtube] I3npB0y6sRM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 7Eb6BaFRNOs: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] oWlsVu5Ab08: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] mS36bcu3faM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

processed 1600 / 8259

WARNING: [youtube] DaczPZlPrYM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ZHbGTDlWeLU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ZHbGTDlWeLU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Z6EF1GNffp4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] fsGxDYlCZj4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] pIH65GMrgwg: This video is not available

WARNING: [youtube] e7FobRU9AuU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] y12uUTFLGqw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] b8iTTiU7Ot0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] VzhJNEcACj4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] gLe1LVgFGpY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] jcGIe27nwm8: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] pZZsfcNMJZ8: This video is not available

WARNING: [youtube] V0W5IiJBq1w: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] rTLybxoPuR8: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] Hy1dN6RsEm8: This video is not available

WARNING: [youtube] mLGPFM042ck: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] b1kkSZUDOG8: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] lJWi9ibVJ3g: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] lJWi9ibVJ3g: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] NYOY7bt9zBc: This video is not available

WARNING: [youtube] hc8xvhNXT6c: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] dLCt3T4z8xM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] dLCt3T4z8xM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Xgw6IVRXmuY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Z5EiqzfiCS8: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] hJgQtDYJUno: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] LJivC5Yd0gE: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] HNPV8XlzK6s: This video is not available
WARNING: [youtube] Ub24LTzSrMU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] WFEoqZS1hwQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

processed 1700 / 8259

WARNING: [youtube] S6q2ek6SjRM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] RJLZmJqdhcg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] pcsXDl01ec4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 3fc6qvlGEuk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] RuebfogRhhc: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] lbaOyiURqMs: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] cjONeMnBpp8: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 8WeII9Ix2jU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] PilKbv3SME0: This video is not available

WARNING: [youtube] thGKk8chz7E: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] thGKk8chz7E: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 1uwfK60ELac: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 1uwfK60ELac: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] MNkFK7y8Gjo: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] rnXDaIcxHIA: This video is not available
WARNING: [youtube] 2q36y9DIfc4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] oe4obNWY4eQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] xbSd1NcwbRI: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] AfGkV6CZnPk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Mv0qLFIMMvo: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] 27PR8SIngv8: This video is not available
ERROR: [youtube] FrsgjOyswQY: Sign in to confirm your age. This video may be inappropriate for some users. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies

WARNING: [youtube] snIKWLawPBE: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] WxF5Q0x4U5o: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] PwS2NEoyiJc: This video is not available

WARNING: [youtube] 83uPpXht0SU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] JNPhu4Yi8BI: This video is not available

WARNING: [youtube] CxTi1kCzcYU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] KKEdUPmJgAU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] ayknMXJ3u74: This video is not available

processed 1800 / 8259

WARNING: [youtube] vKthB8lYuyY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] T9uR2ZHTcQo: This video is not available

WARNING: [youtube] 5ujXKQvRrQQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
ERROR: [youtube] JwaZvSyr2M4: This video is not available

WARNING: [youtube] wuKpZcoV7T4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] MULbsT0P8MM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] BFNekjEgvuk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 3kwim8FZiTE: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] vE7LYFZgFpg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] KJkmKvBBYMs: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] KJkmKvBBYMs: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ySEJ66AwBTw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] ojIXB2jG7j0: Video unavailable
WARNING: [youtube] hLqYujY1a80: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] r7O8vCbTiDk: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] fHWWdhBVcxE: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] pz41eQPDArQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] iS62cxyfZvI: This video is not available

WARNING: [youtube] D4pCFAzBw6M: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] ThWLBYts7RY: Video unavailable

WARNING: [youtube] N2CihEYyS3w: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] PKFUbcDbZBU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] CebIikuT52U: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ikNXuwzoWEA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] o06kiU0qVfI: This video is not available

WARNING: [youtube] 0skcjUd0ts8: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] pWTQLFg7JEQ: This video is not available

WARNING: [youtube] OoDh8UEo36A: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

processed 1900 / 8259

ERROR: [youtube] QR9k0MixxBc: This video is not available

WARNING: [youtube] FU9o0jvWunU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 39KO4Q1pH2s: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] viNx8AXXFDs: This video is not available

WARNING: [youtube] KeOcfEhh5tM: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] ByRSxAqArzQ: This video is not available

WARNING: [youtube] GKUoqLRUE9U: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Q51fCVVnFew: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] Q51fCVVnFew: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] G98UAasVkA0: This video is not available

WARNING: [youtube] VnvqkUNBj6M: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] nK5ilKtqrhw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] jp5dLtfDpAA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] jp5dLtfDpAA: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] RzHKaynQ2KQ: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 5mbVLe1KJHc: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] WT6rhvVYVgg: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 4uASXLHcQJo: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] o8f4b1Zk0xw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] tbfSa95ZEq8: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] R1OavdSa5wI: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] biOpRaXq9x8: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] gyUlM1RAGUE: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] v9EXl5vqL3o: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 2G9hmheLeRE: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] ZxRT05CDk7o: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] HXUqdEePnb4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] HXUqdEePnb4: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] LDdHNmM4jJU: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] PSq3SIGWj9w: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

processed 2000 / 8259

WARNING: [youtube] sVDoDx1Xvhs: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] QqZ7YkTdGIY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] qnRLmSWmIM0: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] 32HPOouMs18: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

ERROR: [youtube] pWxkPFIBPdA: Private video. Sign in if you've been granted access to this video. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies

ERROR: [youtube] cpvHbqXu5n4: This video is not available

WARNING: [youtube] 57eMX3k4oqo: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] U37uFFwZNHY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] U37uFFwZNHY: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

WARNING: [youtube] cOPQaMjjTVw: Some android_vr client https formats have been skipped as they are missing a URL. YouTube may have enabled the SABR-only streaming experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

[download]  12.8% of  489.14MiB at    3.16MiB/s ETA 02:14

KeyboardInterrupt: